eng/build.yml
This requires the signing ICM to be approved.
=> Set MicroBuild to true

src/Tools/dotnet-monitor/GenerateApiKeyCommandHandler.cs
Also fixed accidental usage of `System.Console.*` instead of `IConsole.*`
=> Add ApiKeyHashType to output

.gitignore, eng/Versions.props, generate-dev-sln.ps1, src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj, src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
UseAppFilters for logs in .net 5+. See https://github.com/dotnet/runtime/pull/40165
=> Use App filters

documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/LoggingExtensions.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/RequestThrottling/RequestLimitAttribute.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/ResponseNames.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/StatusCodeStrings.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/TooManyRequestsResponseDocumentFilter.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/TooManyRequestsResponseOperationFilter.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Throttling.cs
- Note the limits I set here are somewhat arbitrary, and I was not planning on adding configurability.
TODO:
Add unit tests
=> Enable endpoint throttling for expensive operations

src/Microsoft.Diagnostics.Monitoring.RestServer/DiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/StorageOptions.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/StorageOptionsDefaults.cs, src/Tools/dotnet-monitor/AddressListenResults.cs, src/Tools/dotnet-monitor/ConfigurationKeys.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/UrlBindingChange.cs
Also add warning if we upgrade metrics endpoint to https
=> Configure temporary storage options for dump operation

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.RestServer/StorageOptions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Microsoft.Diagnostics.Monitoring.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Options/RootOptions.cs, src/Tools/dotnet-monitor/DiagnosticPortOptions.cs
=> Add storage schema

documentation/schema.json, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
- Also relax schema restrictions
#127 
#23
=> Change default values for top level properties.

documentation/api/pidvsuid.md, documentation/api/processes-env.md, documentation/api/processes-get.md, documentation/api/processes-list.md, documentation/api/processes.md
=> More /processes route notes and clarifications.

documentation/README.md, documentation/api/definitions.md, documentation/api/dump.md, documentation/api/gcdump.md, documentation/api/logs.md, documentation/api/processes-env.md, documentation/api/processes-get.md, documentation/api/trace-custom.md, documentation/api/trace-get.md
=> Additional API docs for /logs

src/Microsoft.Diagnostics.Monitoring.RestServer/ConfigurationHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tools/Common/CommandExtensions.cs, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/Egress/AzureBlobEgressFactory.cs, src/Tools/dotnet-monitor/Egress/Configuration/EgressConfigureOptions.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Program.cs
=> Adding new command to display configuration (#179)

documentation/api/dump.md, documentation/api/gcdump.md, documentation/api/logs.md, documentation/api/metrics.md, documentation/api/trace-custom.md, documentation/api/trace-get.md
Update metrics route with links to other docs.
=> Add egressProvider parameter to API docs.

documentation/README.md, documentation/api/README.md, documentation/api/pidvsuid.md, documentation/api/processes.md, documentation/authentication.md, documentation/building.md, documentation/configuration.md, documentation/setup.md
- Includes updates to the naming format adopted by the blog post.
- Additional small updates to the configuration doc
=> Doc naming update

src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs
Depends on https://github.com/dotnet/diagnostics/pull/2229
=> Add timestamp to logs

src/Microsoft.Diagnostics.Monitoring.RestServer/DiagProcessFilter.cs
=> Fix translation of default process CommandLine filter key.

src/Microsoft.Diagnostics.Monitoring.RestServer/DiagProcessFilter.cs
=> Fix translation of default process CommandLine filter key

src/Microsoft.Diagnostics.Monitoring.WebApi/IMetricsStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/MetricsLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/MetricsStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessKey.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/PrometheusDataModel.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ScopeState.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/MetricsExportTests.cs
=> Normalize prometheus metrics

src/Microsoft.Diagnostics.Monitoring.WebApi/Models/DotnetMonitorInfo.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj
Added in a basic test for the new info endpoint that checks whether the returned result has the expected values.
=> Add info endpoint testing

documentation/README.md, documentation/api/README.md, documentation/api/definitions.md, documentation/api/dump.md, documentation/api/gcdump.md, documentation/api/logs-custom.md, documentation/api/logs-get.md, documentation/api/operations-delete.md, documentation/api/operations-get.md, documentation/api/operations-list.md, documentation/api/operations.md, documentation/api/trace-custom.md, documentation/api/trace-get.md, documentation/egress.md
=> Operation documentation

documentation/authentication.md, documentation/configuration.md, documentation/setup.md
Just updating references to be up to date for any new users who might read our documentation when getting started. I skimmed the docs very quickly so it's possible there are other references I've missed.
=> Documentation Updates for Preview 6

src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
=> Add collection rules to config command

documentation/schema.json, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tools/dotnet-monitor/CollectionRules/Options/RegularExpressionsAttribute.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetResponseStatusOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/AspNetRequestCountTriggerFactory.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/AspNetRequestDurationTriggerFactory.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/AspNetResponseStatusTriggerFactory.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Depends on https://github.com/dotnet/diagnostics/pull/2592
=> Add support for Asp.net triggers

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleActionOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleActionOptionsDefaults.cs
=> Add Name and WaitForCompletion properties to action options.

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/ActionsServiceCollectionExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs, src/Tools/dotnet-monitor/CollectionRules/ActionListExecutor.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectDumpAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectGCDumpAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLogsAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionBase.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionFactoryProxy.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionOperations.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ExecuteAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ICollectionRuleAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ICollectionRuleActionFactory.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ICollectionRuleActionFactoryProxy.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ICollectionRuleActionOperations.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRulePipeline.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs, src/Tools/dotnet-monitor/CollectionRules/Configuration/CollectionRuleActionDescriptor.cs, src/Tools/dotnet-monitor/CollectionRules/Configuration/ICollectionRuleActionDescriptor.cs, src/Tools/dotnet-monitor/DisposableHelper.cs, src/Tools/dotnet-monitor/FilteredEndpointInfoSource.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
These changes refactor the collection rule actions to have separate start and completion notions as well as use the factory pattern for creating the actions. This will allow (in a future change) to asynchronously start actions in the action list and synchronously wait for actions to complete when necessary.
=> Refactor actions to allow for async start and completion.

src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs
Don't log collection rule application log items if collection rules are not configured.
=> No logging if no collection rules are configured.

documentation/collectionrules.md, documentation/configuration.md
This is the first pass at collection rule documentation, which includes documentation for each of the triggers and actions. In a separate PR, I will fill out of the filters, limits, and overall documentation of how collection rules work.
=> Collection rule documentation for triggers and actions.

documentation/releaseNotes/releaseNotes.md, documentation/releaseNotes/releaseNotes.template.md, documentation/releaseNotes/releaseNotes.v6.0.0-preview.8.21503.3.md
- Adds release notes for preview 8
- Adds counter interval change note to preview 8 notes
- Rotates notes and sets up for RC1 and GA
=> Add release notes for preview 8

dotnet-monitor.yml, eng/build.yml
Per https://github.com/dotnet/core-eng/issues/14276
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1404323&view=results
=> Switch to 1ES R&D pools on main

documentation/configuration.md, documentation/schema.json, eng/Version.Details.xml, eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/EventCounterSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/AspNetRequestDurationTriggerFactory.cs
Required https://github.com/dotnet/diagnostics/pull/2649
Note this PR includes the breaking changes from diag: https://github.com/dotnet/dotnet-monitor/pull/976
=> Use global interval for asp.net duration trigger

eng/Version.Details.xml
closes https://github.com/dotnet/core-eng/issues/14844
=> Fix bad merge in Version.Details.xml

documentation/configuration.md
Fix documentation on configuration to have up to date example with current authentication schema
=> Fix docs example in configuration.md

documentation/api/defaultprocess.md, documentation/api/gcdump.md, documentation/configuration.md, documentation/setup.md
Updated some versioning and fixed some typos/formatting.
=> Miscellaneous Documentation Updates

eng/Publishing.props, eng/release/DiagnosticsReleaseTool/DiagnosticsRepoHelpers.cs, src/Directory.Build.targets, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This is a port of #1122 for the `release/6.0` branch.
=> Publish nupkgs to blob storage.

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/DumpService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IDumpService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/OperationTrackerService.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/OperationTrackerServiceEndpointInfoSourceCallback.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
* Do not attempt to prune services during tracing
* PR Feedback + Log message for timeout
=> [Port from Release] Do not attempt to prune processes during tracing (#1103)

eng/build.yml
Update containers to newer versions.
=> Update pools to use servicing pools.

eng/PrepareRelease.yml
Makes the prepare release stage execute when building against `internal/release/`
=> Adds internal/release/ to publish branches

src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/Utilities.cs
=> Port - Resolving File Name Collisions 

documentation/releaseNotes/releaseNotes.md, documentation/releaseNotes/releaseNotes.template.md, documentation/releaseNotes/releaseNotes.v6.0.0-rc.1.21518.6.md, documentation/releaseNotes/releaseNotes.v6.0.0.md
=> Update release notes for 6.0.1 release.

eng/release/DiagnosticsReleaseTool/DarcHelpers.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsRepoHelpers.cs
* Update DarcHelpers to include support for internal mirror info
* Update links to have multiple possible URLs
* Update DiagnosticsReleaseRunner.cs
=> Update DarcHelpers to include support for internal mirror info

src/Tests/CrossTargeting.targets, src/Tests/Directory.Build.targets, src/Tests/MultiTarget.targets
=> Allow tests for each TFM of multi-target test projects to run.

documentation/configuration.md
=> Fix docs with DotnetMonitor env var prefix.

documentation/releaseNotes/releaseNotes.md, documentation/releaseNotes/releaseNotes.template.md, documentation/releaseNotes/releaseNotes.v6.0.1.md, eng/Versions.props
Reset current release notes.
Add prior release notes.
=> Bump version to 6.0.2

src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/DisposableHelper.cs, src/Tools/dotnet-monitor/GenerateApiKeyCommandHandler.cs
Ports PR #1050 back to `release/6.0` branch.
Ports PR #1121 back to `release/6.0` branch.
These 2 PRs are required to go in together as #1121 is the fix for the additional json section printout added in #1050.
resolves #1112
=> Port #1112 to release/6.0

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.CollectionRule.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs
Backport of #1234 to release/6.0
/cc @kelltrick
=> [release/6.0] Convert LoggingEventIds to enum

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/LoadProfilerAction.cs, src/Tools/dotnet-monitor/CollectionRules/KnownCollectionRuleActions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/LoadProfilerOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/RequiredGuidAttribute.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport #1199 to release/6.x
/cc @kelltrick
=> Add LoadProfiler action

eng/release/DiagnosticsReleaseTool/Core/Release.cs
Adds more debug code to diagnose build issues. 
Adds the loop tags to the error messages as well as the existing tags in trace messages
=> Add loop tags to error messages in DiagnosticsReleaseTool

src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/HostBuilderExtensions.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/HostBuilderSettings.cs
Refactor host building to better support unit testing.
Add extension methods for replacing environment configuration sources.
cc @kkeirstead
=> Add configuration ordering tests.

eng/PrepareRelease.yml
This is in response to https://github.com/dotnet/arcade/pull/8344
=> Remove cross stage variable reference

documentation/authentication.md, documentation/releaseNotes/releaseNotes.md, documentation/troubleshooting.md
- Incorporates PR feedback from #1431 , which I mistakenly checked in before pushing feedback changes.
- Update Authentication docs to explain `MachineJson` value for `--output` option.
=> Doc tweaks

documentation/releaseNotes/releaseNotes.md, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs
Removes unnecessary setting of `IncludeFields` flag in `JsonSerializerOptions`
=> Machine Json followup

documentation/releaseNotes/releaseNotes.md, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorGenerateKeyRunner.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/OutputFormat.cs
Backports MachineJson changes to 6.1 release. Includes changes:
- #1430 
- #1440
=> Backport MachineJson to 6.1

documentation/schema.json, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/DiagnosticPortPostConfigureOptions.cs
Backporting #1371 to release/6.x
=> Backport: Simplified Diagnostic Port Configuration

documentation/configuration.md, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortConfigurations/Connect.txt, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortConfigurations/FullListen.txt, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortConfigurations/SimplifiedListen.txt, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortTestsConstants.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Backporting #1415 to release/6.x
=> Backport: Simplified Diagnostic Port Configuration Testing

eng/release/Scripts/AcquireBuild.ps1
=> Use latest darc version

documentation/releaseNotes/releaseNotes.md
I think I got everything here - if I missed something, please let me know!
=> 6.1.0 Release Notes

documentation/releaseNotes/releaseNotes.md
I think I got everything here - if I missed something, please let me know!
=> Updating Release Notes for Release/7.x

eng/build.yml
Add test result upload for net7.0
=> Refactor test result upload into loop

documentation/releaseNotes/releaseNotes.md, documentation/releaseNotes/releaseNotes.template.md, eng/Versions.props
=> Update to Preview 3

dotnet-monitor-codeql.yml
Initial pipeline for running Semmle code analysis for C++ and C# on a daily basis during the work week.
=> Add CodeQL weekday pipeline

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/TestProfiler/DllMain.cpp
- Add required SAL annotations
- Suppress weak algorithm usage in tests
=> Fix Semmle issues

documentation/releaseNotes/releaseNotes.md, documentation/releaseNotes/releaseNotes.template.md, eng/Versions.props
Change channel to daily
Reset release notes
=> Update version to 6.2.0

documentation/releaseNotes/releaseNotes.md, src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/ExperienceSurvey.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
=> [main] Add experience survey link

eng/Version.Details.xml, eng/Versions.props
Rollback runtime to coherently match aspnetcore
=> Add coherent dependency from aspnetcore to runtime

documentation/releaseNotes/releaseNotes.md, eng/Versions.props
=> Update to Preview 4

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs
Similar change in #1656 but applied to gcdump
=> Allow gcdump action test to retry when gcdump is not produced

documentation/configuration.md, src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport of https://github.com/dotnet/dotnet-monitor/pull/1438 to release/6.x
/cc @kkeirstead
=> [release/6.x] Config Show - List configuration sources

documentation/collectionruleexamples.md, documentation/collectionrules.md, documentation/configuration.md
JSON samples now have corresponding environment variables.
=> Add Environment Variable examples in Configuration

documentation/releaseNotes/releaseNotes.md, eng/Versions.props
=> [release/6.1] Bump version to 6.1.2

documentation/collectionruleexamples.md, documentation/collectionrules.md, documentation/configuration.md
Previously: JSON and Environment Variables
Updated To: JSON, ConfigMap, and Kubernetes Environment Variables
=> Update Documentation Formats

src/MonitorProfiler/Logging/AggregateLogger.cpp, src/MonitorProfiler/Logging/AggregateLogger.h, src/MonitorProfiler/Logging/DebugLogger.cpp, src/MonitorProfiler/Logging/DebugLogger.h, src/MonitorProfiler/Logging/LogLevelHelper.h, src/MonitorProfiler/Logging/Logger.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/inc/tostream.h, src/inc/tstring.h
Addresses feedback from https://github.com/dotnet/dotnet-monitor/pull/1766#discussion_r853306326
=> Change logging to use tstring

documentation/releaseNotes/releaseNotes.md, eng/Versions.props
=> Update to Preview 5

src/MonitorProfiler/Environment/EnvironmentHelper.cpp, src/MonitorProfiler/Environment/EnvironmentHelper.h, src/MonitorProfiler/Logging/AggregateLogger.cpp, src/MonitorProfiler/Logging/AggregateLogger.h, src/MonitorProfiler/Logging/DebugLogger.cpp, src/MonitorProfiler/Logging/DebugLogger.h, src/MonitorProfiler/Logging/LogLevelHelper.h, src/MonitorProfiler/Logging/Logger.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp
Attempt read debug logger log level env var to control log level
=> Add ability to filter log messages based on log level

eng/Publishing.props, src/Directory.Build.targets, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Backport of #1834 to release/6.1
=> [release/6.1] Refactor blob group and package version file writing

documentation/collectionrules/collectionruleexamples.md, documentation/collectionrules/collectionrules.md, documentation/collectionrules/triggershortcuts.md, documentation/configuration.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/BuiltInTriggerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/KnownCollectionRuleTriggers.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/CPUUsageOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/CPUUsageOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/GCHeapSizeOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/GCHeapSizeOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/IEventCounterShortcuts.Validate.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/IEventCounterShortcuts.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/KnownEventCounterConstants.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/ThreadpoolQueueLengthOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterShortcuts/ThreadpoolQueueLengthOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/TriggerOptionsConstants.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/EventCounterTriggerFactory.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
=> [release/6.x] Built-In Shortcuts

documentation/configuration.md, documentation/schema.json, eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.Validate.cs, src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationService.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedConfigurations/EgressRedacted.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/EgressRedacted.json, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx, src/Tools/dotnet-monitor/dotnet-monitor.csproj
* Add support for Managed Identity authentication for egress.
* PR feedback
* Fix test baselines
=> [backport] Add support for Managed Identity authentication for egress. (#1884)

src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/Logging/Logger.h, src/MonitorProfiler/MainProfiler/ExceptionTracker.cpp, src/MonitorProfiler/MainProfiler/ExceptionTracker.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/MainProfiler/ThreadData.cpp, src/MonitorProfiler/MainProfiler/ThreadData.h, src/MonitorProfiler/MainProfiler/ThreadDataManager.cpp, src/MonitorProfiler/MainProfiler/ThreadDataManager.h
Backport of #1853 from `release/6.x` to `main`
=> Unhandled exception detection

NuGet.config, eng/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AsyncWaitScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/EnvironmentVariablesScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/SpinWaitScenario.cs, src/Tools/dotnet-monitor/Program.cs
=> Update OSS Versions

eng/Versions.props, src/Tests/Directory.Build.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Update Newtonsoft.Json version across affected projects to the latest version.
=> Update Newtonsoft.Json version

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx, src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressProvider.cs, src/Tools/dotnet-monitor/FilteredEndpointInfoSource.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport https://github.com/dotnet/dotnet-monitor/pull/2022 to release/6.1
=> Address "Swallow Everything" Exceptions

CONTRIBUTING.md
Based on https://github.com/dotnet/runtime/blob/d4ac72106c03781c4b458b04f37763ffda044f3e/CONTRIBUTING.md. I'll leave a few comments on the doc itself for areas where I wasn't sure what guidance we should/shouldn't give.
=> Adding Contributor Guidelines Document

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/PrometheusDataModel.cs, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/MetricsExportTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/PrometheusDataModelTests.cs
Closes https://github.com/dotnet/dotnet-monitor/issues/2021
=> Fix duplicated values for matric group

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptionsExtensions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport of #2164 to `release/6.2`
/cc @wiktork
=> [release/6.2] Delete endpoint on startup

documentation/api/collectionrules-all.md, documentation/api/collectionrules-individual.md, documentation/api/definitions.md, documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.Options/CollectionRuleFinishedStates.cs, src/Microsoft.Diagnostics.Monitoring.Options/CollectionRuleState.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/CollectionRulePipelineState.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ICollectionRuleService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CollectionRuleDescription.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CollectionRuleDetailedDescription.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleDescriptionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTestsHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/ActionsServiceCollectionExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRulePipeline.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport #1829 to `release/6.x`
=> [release/6.x] Backport: Querying For Collection Rule State

documentation/api/operations-get.md, documentation/api/operations-list.md, documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EgressOperationStatus.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperation.cs
Backport #2136 to `release/6.x`
=> [release/6.x] Operations Api shows RuntimeId, ProcessId, and ProcessName

dotnet-monitor-codeql.yml, dotnet-monitor.yml, eng/PrepareRelease.yml, eng/build.yml
Backport #2264 to `release/6.x`
=> [release/6.x] Update to newer Windows build images

dotnet-monitor-codeql.yml, dotnet-monitor.yml, eng/PrepareRelease.yml, eng/build.yml
Backport #2266 to `release/6.2`
=> Update to newer Windows build images

documentation/configuration.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/CollectionRuleMetadata.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/IEgressService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/PassThroughAction.cs, src/Tools/dotnet-monitor/CollectionRuleMetadataNames .cs, src/Tools/dotnet-monitor/CollectionRules/ActionListExecutor.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectDumpAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectGCDumpAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLogsAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionBase.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ExecuteAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/GetEnvironmentVariableAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ICollectionRuleAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/LoadProfilerAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/SetEnvironmentVariableAction.cs, src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs, src/Tools/dotnet-monitor/Egress/EgressArtifactSettings.cs, src/Tools/dotnet-monitor/Egress/EgressService.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport #2290 to `release/6.x`
=> [release/6.x] Backport: Additional Metadata For Azure Egress (#2290)

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedConfigurations/EgressRedacted.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/EgressRedacted.json, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
Inadvertently didn't include this in #2290
=> Added Metadata in ConfigurationJsonWriter

documentation/README.md, documentation/compatibility/7.0/README.md, documentation/compatibility/README.md
Document the breaking changes for each major version. In subsequent PRs, we can add documents for each breaking change to explain their details.
=> Breaking changes doc

documentation/configuration.md, src/Tools/dotnet-monitor/Egress/EgressService.cs
In reference to https://github.com/dotnet/dotnet-monitor/pull/2290#discussion_r947256331
=> Added DotnetMonitor_ prefix to built-in metadata

.github/fabricbot.json
=> Add Time of Day check for FabricBot Scheduled Search For Stale PRs

documentation/videos-and-tutorials.md, samples/AKS_Tutorial/README.md
Added links in our docs to the new AKS tutorial; also added the commands used (and their timestamps) for ease of copy-pasting.
=> Add documentation and command list for AKS Video

eng/Versions.props, global.json, src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/TemplateOptions.cs, src/Tools/dotnet-monitor/RootOptions.cs
Edit: I've made all of the options properties that have a type of `IDictionary<>` to be settable to work around this issue: https://github.com/dotnet/runtime/issues/75626
=> Update SDK to 7.0 RC 1 and runtimes to latest

src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Startup.cs
Use `IOptions<CorsConfigurationOptions>` instead of manually binding from configuration
=> Get CorsConfiguration through options service

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortConfigurations/Connect.txt, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/DefaultProcess.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/DiagnosticPort.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/URLs.json, src/Tools/dotnet-monitor/ConfigurationExtensions.cs, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs
Manual backport of #2550 to `release/6.x`
=> [release/6.x] Unwrap ChainedConfigurationProvider to get real provider

src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptionsExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/MetricsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Startup.cs
Manual backport of #2551 to `release/6.2`
=> [release/6.2] Move metrics services configuration out of Startup class

dotnet-monitor-codeql.yml, dotnet-monitor.yml, eng/PrepareRelease.yml, eng/build.yml, eng/release.yml
(identical images, different billing)
=> Move release-branch build over to -Svc pools 

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs
The refactors the logs functional tests to pull out the call to ApiClient.CaptureLogsAsync into anonymous functions which simplifies the remaining validation code into one code path. No behavioral changes or fixes are made with this refactor.
=> Small refactor of logs functional tests

generate-dev-sln.ps1, startvs.cmd, startvscode.cmd, startvscode.sh
These are the same scripts from https://github.com/dotnet/aspnetcore with a minor adjustment for the startvs.cmd script to automatically open the dotnet-monitor.sln file.
=> Scripts to launch VS and VS Code using local SDK

src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs
Changes in #2806 were not sufficient to handle all scenarios where exceptions are thrown during the creation of the `IProcessInfo` objects. This change moves the exception handling into a wrapper `Task`, handles all non-cancellation exceptions (and logs them), and returns either the `IProcessInfo` instance or `null`. These wrapper `Task` objects are always completed successfully unless the cancellation token passed to `GetProcessesAsync` is signaled.
=> Handle all non-cancellation exceptions when creating IProcessInfo

eng/Signing.props
Add AWS SDK libraries to be signed with 3rd party certificate.
=> Update 3rd party signed assemblies

documentation/compatibility/7.0/README.md
Add more details about the (few) breaking changes in 7.0
=> Update breaking changes with details

documentation/api/definitions.md, documentation/openapi.json, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypeUtilities.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypes.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/SpeedScopeStackResults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProfilerChannel.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/StacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs, src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/Utilities/ThreadUtilities.cpp, src/MonitorProfiler/Utilities/ThreadUtilities.h, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectStacksAction.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectStacksOptions.cs
Add support for speedscope format when capturing stacks. 
Add support for [speedscope](https://speedscope.app) format when capturing stacks.
=> Add support for speedscope format

eng/Versions.props
Update the ASP.NET authentication packages to the 7.0.0 GA version.
=> Update ASP.NET authentication packages to 7.0.0

documentation/docker.md, documentation/releases.md
Update the documentation for the current releases and the Dockerfiles.
=> Update release and Docker docs

eng/build.yml
=> Publish .NET 8 test results

documentation/release-process.md, eng/Versions.props, eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Manual backport of #3082 to `main`
=> [main] Allow pivoting on released vs development versions of diagnostics libraries

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/LoggingExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/ScenarioHelpers.cs
=> [release/7.x] Fixing broken links and typos (#2672)

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunnerExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppLogEventIds.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/OverlappingEventSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/LoggingExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/ScenarioHelpers.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AspNetScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExecuteScenario.cs, src/Tools/dotnet-monitor/DisposableHelper.cs
=> [release/7.x] Functional Tests For HTTP Trace Followed By AspNet* Triggers (#2654)

global.json
Update 7.0 runtime installation to use version managed by dependabot. Unblocks #3098
=> [release/7.x] Update runtime installation for 7.0

documentation/releases.md
=> Update 7.0 and 6.3 release information

documentation/learningPath/README.md, documentation/learningPath/sample-pull-request.md
I can add more detail if people want (branches, labels, automation, etc.) - I figured I'd keep this pretty basic so that it doesn't need to keep being updated as we make process improvements.
=> Learning Paths - Sample PR

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/StreamingCounterLogger.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/MetricsScenario.cs
To match https://github.com/dotnet/diagnostics/pull/3559
=> [feature branch, do not review] Update counter api, fixup metadata parsing

src/Tests/CollectionRuleActions.UnitTests/ActionListExecutorTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectDumpActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectGCDumpActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectLiveMetricsActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectLogsActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectTraceActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/ExecuteActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/LoadProfilerActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/TestCollections.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/CollectionRules/Actions/PassThroughAction.cs
Manual backport of #2881 to `release/7.x`
=> [release/7.x] Run collection rule action tests serially

dotnet-monitor.sln, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionProcessor.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionSourceBase.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipeline.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipelineBuilder.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipelineDelegate.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/FilterRepeatExceptionPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Microsoft.Diagnostics.Monitoring.StartupHook.csproj, src/Microsoft.Diagnostics.Monitoring.StartupHook/StartupHook.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/CurrentAppDomainExceptionSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/MockExceptionSource.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/ExceptionPipelineBuilderTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/ExceptionPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/Steps/AppendIntegerPipelineStep.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/Steps/FilterRepeatExceptionPipelineStepTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests.csproj, src/Tools/dotnet-monitor/DisposableHelper.cs
This is a merge from `release/7.x` to `main` to allow easy code flow of features developed in the 7.x minor versions up to the next version.
=> Merge `release/7.x` to `main`

documentation/releases.md
=> Update 6.2 to be out-of-support

eng/Version.Details.xml
=> Add missing entry for Microsoft.DotNet.BuildTasks.Archives dependency

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IMetricsOperationFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/CounterSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/AzureBlob/AzureBlobEgressProviderTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs, src/Tools/dotnet-monitor/Metrics/MetricsOperation.cs, src/Tools/dotnet-monitor/Metrics/MetricsOperationFactory.cs
Corresponds to https://github.com/dotnet/diagnostics/pull/3599
=> Merge to feature branch

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionIdentifier.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/ExceptionIdentifierTests.cs
Small building block for grouping thrown exceptions together by exception type and throwing location (method + IL offset).
=> Exception identification

eng/Build.props, eng/Signing.props, eng/Versions.props, eng/build.ps1, eng/build.sh, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/platform-matrix.yml, src/Directory.Build.props, src/Tools/Directory.Build.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/dotnet-monitor-archive.proj
Manual backport of #3204 to `release/7.0`; only conflict was in Version.props
=> [release/7.0] Create platform and TFM specific archives

documentation/openapi.json
Update the openapi.json file to what is expected to pass baseline validation in tests.
=> Regenerate OpenApi document

eng/Version.Details.xml, eng/Versions.props
=> [release/6.x] Fix Microsoft.DotNet.Build.Tasks.Archives version entry

eng/Version.Details.xml, eng/Versions.props
=> [main] Fix Microsoft.DotNet.Build.Tasks.Archives version entry

eng/Version.Details.xml, eng/Versions.props
=> [release/7.x] Fix Microsoft.DotNet.Build.Tasks.Archives version entry

documentation/learningPath/configuration.md, documentation/releaseNotes/releaseNotes.v7.0.0.md
=> Fix Dead Configuration Link In Learning Path

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
=> Use one payload for Histogram

documentation/openapi.json, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/CounterSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EventMetricsConfiguration.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs
=> [SDM] Added MetricType option for configuration

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IMetricsOperationFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs, src/Tools/dotnet-monitor/Metrics/MetricsOperation.cs, src/Tools/dotnet-monitor/Metrics/MetricsOperationFactory.cs
=> Pr feedback

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
=> Do not allow CounterEnded events to displace existing metrics

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
=> Deduplicate errors

.github/dependabot.template.yml, .github/dependabot.yml
=> Update dependabot for release/8.x

eng/Versions.props, eng/dependabot/nuget.org/Versions.props
=> Use shipped version of dotnet-diagnostics

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CommonTestTimeouts.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs
Attempting to stabilize flaky tests - if this doesn't work, I can put out another PR disabling these tests until we can figure out what's going on.
=> [SDM] Reverted duration seconds from 2 to 10 seconds

documentation/release-process.md
=> Update release docs

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
=> Fix quantile issue for summaries

documentation/api/definitions.md, documentation/api/livemetrics-custom.md, documentation/collectionrules/collectionruleexamples.md, documentation/configuration/metrics-configuration.md
@wiktork for the `System.Diagnostics.Metrics` updates.
=> Docs Updates

eng/Signing.props
=> Add 3P signing entries for Swashbuckle

documentation/releases.md
=> Update servicing release information

documentation/releases.md
=> Add 8.0 Preview 1 release information

eng/dependabot/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/StreamingCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/MetricsUtilities.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs
=> [release/7.0] Fix breaking changes from diagnostics package

eng/dependabot/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/StreamingCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/MetricsUtilities.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs
=> [release/6.x] Fix breaking changes from diagnostics package

src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tools/dotnet-monitor/CollectionRules/ActionOptionsDependencyAnalyzer.cs, src/Tools/dotnet-monitor/ConfigurationTokenParser.cs
=> Add substitution tokens for other process info

src/Microsoft.Diagnostics.Monitoring.WebApi/IInProcessFeatures.cs, src/Tools/dotnet-monitor/InProcessFeatures/InProcessFeatures.cs, src/Tools/dotnet-monitor/InProcessFeatures/InProcessFeaturesPostConfigureOptions.cs, src/Tools/dotnet-monitor/Profiler/ProfilerService.cs
=> Only load profiler for features that require it

documentation/configuration/egress-configuration.md, src/Tools/dotnet-monitor/Egress/S3/S3Storage.cs
=> S3 Egress: Use RegionEndpoint when ServiceURL is not specified

src/Tools/dotnet-monitor/Egress/S3/MultiPartUploadStream.cs
=> S3 Egress Fails Due to Part Number of 0

documentation/api/definitions.md, documentation/api/livemetrics-custom.md, documentation/configuration.md, documentation/openapi.json, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EventMetricsConfiguration.cs, src/Tests/CollectionRuleActions.UnitTests/CollectLiveMetricsActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLiveMetricsOptions.cs
=> Split meters from counters in the livemetrics route and action

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs
=> Split eventcounter and meters in metrics configuration

documentation/openapi.json, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EventMetricsConfiguration.cs
=> Fixup merge issues around schema splitting

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs
=> Change call to UseApiKey to match pattern used elsewhere in test code

documentation/learningPath/aks.md
I don't have too much experience doing this, but this is the workflow I use when testing using AKS (originally based on Wiktor's script). Let me know if you'd prefer a different workflow or if there's anything missing/unnecessary.
=> [Learning Path] Using AKS To Test Dotnet Monitor Development

eng/AfterSolutionBuild.targets, eng/Build.props, src/archives/S3Storage/Package.props, src/archives/S3Storage/ProjectsToBuild.props, src/archives/S3Storage/ProjectsToPublish.props, src/archives/S3Storage/S3Storage-archive.proj, src/archives/S3Storage/S3Storage-symbols.proj
=> Create archives for S3 extension

eng/AfterSolutionBuild.targets, eng/Version.Details.xml, eng/Versions.props, eng/dependabot/Versions.props, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/build-test.yml, eng/pipelines/jobs/pack-sign-publish.yml, src/Microsoft.Diagnostics.Monitoring.StartupHook/ProjectsToPublish.props, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/PublishedProjectPackage.targets
=> Merge main to feature/egressExtension

documentation/releaseNotes/releaseNotes.v8.0.0-preview.2.23155.4.md
=> Add 8.0 preview 2 release notes

documentation/collectionrules/collectionrules.md
=> Update token docs

.github/dependabot.template.yml, .github/dependabot.yml
=> Add release/7.1 to dependabot updates

documentation/releases.md
=> Add 8.0 P2 and 7.1.0 release information

src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/MainProfiler/ExceptionTracker.cpp, src/MonitorProfiler/MainProfiler/ExceptionTracker.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/MainProfiler/ThreadData.cpp, src/MonitorProfiler/MainProfiler/ThreadData.h, src/MonitorProfiler/MainProfiler/ThreadDataManager.cpp, src/MonitorProfiler/MainProfiler/ThreadDataManager.h, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs
Manual backport of #2452 to `release/6.x`
=> [release/6.x] Disable exception tracking via profiler

global.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs
=> Update SDK to final 8.0 Preview 2

documentation/learningPath/testing.md
=> Learning path for dotnet-monitor testing

src/Microsoft.Diagnostics.Monitoring.Options/ExtensionEgressProviderOptions.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs
=> Remove unnecessary whitespace

src/archives/AzureBlobStorage/Package.props, src/archives/S3Storage/Package.props
=> Include Third Party Notices in extension packages

eng/pipelines/jobs/tpn.yml
Generate a notice file that contains all of the dependencies of all of the tools shipped from the repository. It will be included inside the package for each tool.
=> Generate shared composite notice file

documentation/schema.json, eng/dependabot/Versions.props, src/Extensions/AzureBlobStorage/AzureBlobEgressProvider.cs, src/Extensions/AzureBlobStorage/AzureBlobEgressProviderOptions.Validate.cs, src/Extensions/AzureBlobStorage/AzureBlobEgressProviderOptions.cs, src/Extensions/AzureBlobStorage/OptionsDisplayStrings.Designer.cs, src/Extensions/AzureBlobStorage/OptionsDisplayStrings.resx, src/Extensions/AzureBlobStorage/Strings.Designer.cs, src/Extensions/AzureBlobStorage/Strings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.AzureBlobStorageTests.UnitTests/AzureBlobEgressProviderTests.cs
=> Enable workflow identity

src/Extensions/AzureBlobStorage/AzureBlobEgressProvider.cs
=> Disable azure developer cli creds

documentation/configuration/README.md
=> Fix Broken Docs Link

global.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
This reverts commit 83e81b4c413d9bc9efda78fc1450f441fd2eb5ff.
=> Revert "Update to latest 8.0 SDK (#4388)"

global.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2187458&view=results
=> Use 8.0 Preview 4 SDK

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.Validate.cs, src/Microsoft.Diagnostics.Monitoring.Options/AzureBlobEgressProviderOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/AzureBlob/AzureBlobEgressProviderTests.cs, src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Manual backport of #4313 to release/7.x
=> [release/7.x] Port workload identity auth for Azure egress

eng/Versions.props
=> Update diagnostics repo dependencies

eng/Versions.props
=> [release/7.x] Update diagnostics repo dependencies

eng/Versions.props
=> [release/6.x] Update diagnostics repo dependencies

documentation/egress.md
These may be expanded in the future, but I wanted to get some initial coverage in our docs regarding the new model. Note that there are references to the learning path in this doc (which has not yet been merged) - if we don't want to link users there, I can also duplicate some of that information here, or have the learning path point to this documentation (instead of vice versa).
=> Egress Extensibility - Updates to User-Facing Docs

src/Tests/CollectionRuleActions.UnitTests/CollectLogsActionTests.cs
Skip flaky tests due to runtime update
=> Skip CollectLogsActionTests

eng/pipelines/stages/preparerelease.yml
Manual backport of #4175 to `release/7.x`
=> [release/7.x] Cleanup release preparation stage

eng/Versions.props, eng/dependabot/NuGet.config, eng/dependabot/Packages.props, eng/dependabot/Versions.props, eng/dependabot/net6.0/NuGet.config, eng/dependabot/net7.0/NuGet.config, eng/dependabot/netcoreapp3.1/NuGet.config, eng/dependabot/nuget.org/Directory.Build.props, eng/dependabot/nuget.org/Packages.props, eng/dependabot/nuget.org/Versions.props, eng/dependabot/nuget.org/dependabot.csproj
=> Move MicrosoftDiagnosticsMonitoringShippedVersion to nuget.org dependabot props

eng/Version.Details.xml, eng/Versions.props, global.json
Preemptively add versions for Helix usage so that I don't have to chase them on a daily basis when offering more complicated PRs.
=> Add versions for Helix

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestConditions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EgressExtensibilityTests.cs
=> Disable some extensibility egress tests for ARM64

documentation/release-process.md
=> Update release doc

src/Tools/dotnet-monitor/LoggingEventIds.cs
=> Fix message id

eng/pipelines/dotnet-monitor-cg.yml
=> Disable CI and PR triggers for CG pipeline

.github/workflows/post-release.yml
=> Skip `shipped/*` branch creation as part of releases

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionEventArgs.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionSourceBase.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipeline.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipelineExceptionContext.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionDemultiplexerPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionInstance.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionInstance.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventListener.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/MockExceptionSource.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionEvents.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs
=> Merge release/7.x to main

src/Microsoft.Diagnostics.Monitoring.HostingStartup/FunctionProbeCategories.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingService.cs
=> Change Parameter Capture logger category

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/OutputStreamResult.cs
=> Remove unused EgressOperation and OutputStreamResult ctors

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectDumpOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectExceptionsOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectGCDumpOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLiveMetricsOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLogsOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectStacksOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptions.cs
Follow up on https://github.com/dotnet/dotnet-monitor/pull/5064#discussion_r1283472326
=> Unify Egress and Duration options descriptions

src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/LogEmittingProbes.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/InstrumentedMethod.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingLogger.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingService.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/SystemLoggingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestLogger.cs, src/Tools/dotnet-monitor/DisposableHelper.cs
=> [Parameter capturing] Enable logging of system types

src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingLogger.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingService.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/SystemLoggingTests.cs
=> Fixup unstable test

NuGet.config
Clean up NuGet.config file to help with automated insertions from dependency flow.
=> Cleanup NuGet.config

eng/helix/Helix.proj
=> Use property for DotNetBuildsInternalContainerReadToken

eng/pipelines/jobs/build.yml, eng/pipelines/jobs/pack-sign-publish.yml, eng/pipelines/jobs/sign-binaries.yml, eng/pipelines/jobs/tpn.yml, eng/pipelines/steps/setup-nuget-sources.yml
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2261464&view=results
=> Add runtime feed and feed setup to Sign and Pack/Publish jobs

eng/PoliCheckExclusions.xml
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2262423&view=results
=> Exclude the .dotnet folder from PoliCheck

eng/PoliCheckExclusions.xml
Similar to #5292 but targeting `release/7.x`; this change will be backported to remaining active branches.
=> Update PoliCheck exclusions

eng/pipelines/stages/preparerelease.yml
=> Update AzDO token for darc gather-drop

documentation/releaseNotes/releaseNotes.v8.0.0-rc.1.23458.6.md
Note that this was manually created (the pipeline did not successfully run) - I believe I have rounded up all of the relevant PRs.
=> Add releaseNotes.v8.0.0-rc.1.23458.6

eng/Version.Details.xml, eng/Versions.props
=> Merge internal commits for release/8.x

documentation/release-process.md
=> Update docs for internal release builds

eng/dependabot/Versions.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj
=> Re-add explicit JWT packagereference

documentation/kubernetes.md, samples/AKS_Tutorial/deploy.yaml
=> Update to match sample app user

global.json
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2271080&view=results
=> Update SDK to 8.0 RC 1

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs
=> Fix build break due to new tests with old field references

eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Manual backport of #5426 to main
=> [main] Remove explicit IdentityModel dependencies

eng/Versions.props
=> Switch to shipped Microsoft.Diagnostics.Monitoring libraries

global.json
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2283480&view=results
=> Update xcopy msbuild

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2285448&view=results
=> Fix process cleanup startup hook path

global.json
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2287643&view=results
=> Update SDK to 8.0 RC 2

global.json
This reverts commit 2fdb924aa7899d2c7eae70ac418a1ae39527e9a9.
I merged this in too early, prior to all CI validation.
=> Revert "Update SDK to 8.0 RC 2 (#5522)"

global.json
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2297277&view=results
=> Use implicit xcopy-msbuild version

NuGet.config, eng/Version.Details.xml, eng/Versions.props, eng/dependabot/nuget.org/Versions.props, global.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/TraceUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
=> Merge main into release/8.x

eng/helix/Helix.proj
=> Fix helix aspnet version reference

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestConditions.cs
=> [release/6.x] Disable flaky logs tests

eng/release/Scripts/SetTaskVariable.ps1
=> Add missing script

documentation/compatibility/README.md
=> Add 8.0 compat link to readme

documentation/api/definitions.md, documentation/configuration/metrics-configuration.md
It looks like the docs weren't updated when we switched schemas several months ago - updating the example to be accurate.
=> SDM Doc Updates

.github/actions/generate-release-notes/releaseNotes.template.md
Updates the release notes to include a survey.
Closes #5722
=> Release notes template update

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs
The LogsTests have a configuration reuse error between retry attempts. This affects tests that specify a filter specification since the test infrastructure will append implementation detail categories to the filter specification; if the test is retried, then those categories will attempt to be readded and fail due to already existing keys.
The fix is to copy the logs configuration before attempting to make any modifications.
=> Copy configuration in LogsTests to avoid reuse between retries.

eng/release/DiagnosticsReleaseTool/Common/ReleaseToolHelpers.cs, eng/release/DiagnosticsReleaseTool/Core/FileMetadata.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsManifestGenerator.cs
=> fix: GetDefaultCategoryForClass typo

eng/Version.Details.xml
=> Rename packages to framework 9

NuGet.config, documentation/schema.json, eng/Common.props, eng/Versions.props, eng/dependabot/net8.0/Packages.props, eng/pipelines/jobs/test-binaries.yml, src/Directory.Build.props, src/Directory.Build.targets, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/SchemaGenerationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMonikerExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestDotNetHost.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestDotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/ActionTestsHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
=> Change to version 9.0

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs
=> [feature/9.x] Fix exception tests for 9.0

eng/helix/Helix.proj, global.json
=> Update net90 runtime references

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSourceIdentifierCacheCallback.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionGroupIdentifierCache.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/EventStacksPipeline.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameCache.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameIdentificationEvents.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs, src/Profilers/CommonMonitorProfiler/CommonUtilities/ClrData.h, src/Profilers/CommonMonitorProfiler/CommonUtilities/NameCache.cpp, src/Profilers/CommonMonitorProfiler/CommonUtilities/NameCache.h, src/Profilers/CommonMonitorProfiler/CommonUtilities/TypeNameUtilities.cpp, src/Profilers/MonitorProfiler/Stacks/StacksEventProvider.cpp, src/Profilers/MonitorProfiler/Stacks/StacksEventProvider.h, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventListener.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/ExceptionGroupIdentifierCacheTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs, src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipelineNameCache.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs
Backport simplify exception types to release/8.0
=> [release/8.0] [Exceptions] Simplify Types in Plain Text Representation (#5017)

eng/dependabot/Versions.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net7.0/Versions.props, eng/dependabot/net8.0/Directory.Build.props, eng/dependabot/net8.0/NuGet.config, eng/dependabot/net8.0/Packages.props, eng/dependabot/net8.0/Versions.props, eng/dependabot/net8.0/dependabot.csproj
=> [release/8.0] Update dependencies

eng/dependabot/Versions.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net7.0/Versions.props
=> [release/7.x] Update dependencies

eng/Versions.props, eng/dependabot/net8.0/Versions.props, eng/helix/Helix.proj, global.json
=> [release/8.0] Fixup dependencies

eng/dependabot/Versions.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net7.0/Versions.props, eng/dependabot/net8.0/Packages.props, eng/dependabot/net8.0/Versions.props
=> Fixup dependencies

eng/dependabot/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
=> [release/6.x] Update Diagnostics shipped version

eng/dependabot/nuget.org/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
=> [release/7.x] Update Diagnostics shipped version

eng/dependabot/nuget.org/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
=> [release/8.0] Update Diagnostics shipped version

.github/dependabot.template.yml, .github/dependabot.yml
=> Ignore Moq updates via dependabot

eng/Versions.props, eng/dependabot/Versions.props
Manual backport of #6071 to release/7.x
=> [release/7.x] Simplify dependabot imports

.github/dependabot.template.yml, .github/dependabot.yml
=> Include `release/8.0` in dependabot updates

eng/pipelines/scripts/Copy-ApiScanEligible.ps1
Don't skip ARM64 binaries when scanning. Use alternative procedures for excluding these files.
=> Scan all executable files

eng/pipelines/dotnet-monitor-official.yml, eng/pipelines/dotnet-monitor-public.yml
=> [release/7.x] Bifurcate official pipeline from public pipeline

eng/pipelines/dotnet-monitor-official.yml, eng/pipelines/dotnet-monitor-public.yml
=> [release/6.x] Bifurcate official pipeline from public pipeline

.config/tsaoptions.json
Separate TSA reporting from .NET Diagnostics
=> Update TSA options

eng/pipelines/jobs/build.yml, eng/pipelines/templates/pipeline-template.yml
Manual backport o #6242 to release/6.x
=> [release/6.x] Use long-term pool images

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/ProfilerHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/AppCommands.cs
Manual backport of #6299 to release/6.x
=> [release/6.x] Minimize printing of potential secrets in tests

eng/pipelines/dotnet-monitor-official.yml
Enable more SDL tools. These tools should not cause build breaks but will file bugs for issues for each tool.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2414178&view=results
=> Enable BinSkim, PoliCheck, and TSA

eng/pipelines/dotnet-monitor-official.yml
Manual backport of #6305 to release/7.x
=> [release/7.x] Enable BinSkim, PoliCheck, and TSA

eng/pipelines/jobs/sign-binaries.yml
The `JobName` variable doesn't exist in this job; write out the literal name of the job.
=> Fix sign binaries job name

src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingService.cs, src/Microsoft.Diagnostics.Monitoring.Options/StorageOptions.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/DiagnosticsBootstrapper.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/MonitorMessageDispatcher/MonitorMessageDispatcher.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/MonitorMessageDispatcher/ProfilerMessageSource.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypes.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/EgressValidationAttribute.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/EndpointInfo/IEndpointInfoSource.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/HostRestrictionAttribute.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IArtifactOperation.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IDiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IInProcessOperation.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IStartable.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/KeyValueLogScope.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessKey.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProfilerChannel.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProfilerMessage.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/StreamDefaults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/Utilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.AzureBlobStorageTests.UnitTests/Microsoft.Diagnostics.Monitoring.AzureBlobStorageTests.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.S3StorageTests.UnitTests/Microsoft.Diagnostics.Monitoring.S3StorageTests.UnitTests.csproj, src/Tools/dotnet-monitor/IDiagnosticLifetimeService.cs, src/Tools/dotnet-monitor/StartupHook/StartupHookApplicator.cs
This PR adjusts some of the type visibilities. I've taken the approach of changing things at the file-level instead of trying to make micro adjustments on specific methods / properties for a given type.
=> Type visibility changes

src/Tests/CollectionRuleActions.UnitTests/CollectDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Fixtures/AzuriteFixture.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs
Resolves https://github.com/dotnet/dotnet-monitor/issues/5906
=> [feature/9.x]Remove test disablements

.config/1espt/PipelineAutobaseliningConfig.yml
Commit the 1ES Pipelines baseline file that was automatically created from build runs.
=> Add 1ES pipeline baselines

cspell.json
=> Exclude eng/common from spell check

global.json
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2442620&view=results
=> Update to latest 8.0 SDK

.github/releases.json
=> Mark 7.3 as out-of-support

eng/pipelines/dotnet-monitor-official.yml
Manual backport of #6685 to release/6.x
=> [release/6.x] Remove debug legs from CI build

eng/pipelines/dotnet-monitor-cg.yml
=> Exclude 7.3 from CG scans

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleDescriptionTests.cs
Add retries around flaky collection rule tests. No other changes to the tests were made.
The tests are flaky because of the fact they rely on a cpu usage trigger for the collection rules. This isn't something we can deterministically cause in pipelines. I've opted for adding a retry here to see if that helps. if it doesn't we should skip these tests until we can rewrite them to use a more deterministic trigger.
=> Add retries around flaky collection rule tests

eng/Version.Details.xml, eng/Versions.props
=> Fake version for sdkplacholder

eng/Version.Details.xml
=> Update parent dependency

eng/pipelines/steps/setup-nuget-sources.yml
=> Fixup nuget authentication

src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/DebuggerDisplayFormatterTests.cs
=> Fix more InlineData nullable parameters

eng/pipelines/stages/preparerelease.yml, eng/release/DiagnosticsReleaseTool/Common/AzureBlobPublisher.cs, eng/release/DiagnosticsReleaseTool/Config.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj, eng/release/Directory.Build.props, eng/release/Scripts/AcquireBuild.ps1
Manual backport of #6899 to release/6.x; conflicts were due to lack of compliance pipeline in target branch and updates to the AcquireBuild.ps1 script that were not backported before. I've included the "separated" flag updates in the script to prevent future collisions.
=> [release/6.x] Update build asset staging to use managed identity

eng/pipelines/stages/preparerelease.yml, eng/release/DiagnosticsReleaseTool/Common/AzureBlobPublisher.cs, eng/release/DiagnosticsReleaseTool/Config.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj, eng/release/Directory.Build.props, eng/release/Scripts/AcquireBuild.ps1
Manual backport of #6899 to release/8.0; conflicts were due to lack of compliance pipeline in target branch and updates to the AcquireBuild.ps1 script that were not backported before. I've included the "separated" flag updates in the script to prevent future collisions.
=> [release/8.0] Update build asset staging to use managed identity

eng/pipelines/stages/preparerelease.yml
Use the same tokens for internal build read as the other branches.
=> Fix staging to use correct tokens

eng/dependabot/independent/Versions.props
Similar to #6927, update Microsoft.Identity.Web to 2.20.0
=> Update Microsoft.Identity.Web to 2.20.0

.github/dependabot.template.yml, .github/dependabot.yml
=> Pin major/minor identity model versions for .NET Monitor 6

.github/workflows/sync-branches.yml
Example PR: https://github.com/schmittjoseph/dotnet-monitor/pull/616
cc @kkeirstead
=> Fix auto merging of branches when there is a `modify/delete` conflict

Directory.Packages.props, eng/dependabot/independent/Versions.props
Manually backporting https://github.com/dotnet/dotnet-monitor/pull/7053
=> [release/8.0] Manual Backport Azure Core Pinned Version

.github/dependabot.template.yml, .github/dependabot.yml, eng/dependabot/independent/Packages.props
=> Add Azure.Core to dependabot

.github/dependabot.template.yml, .github/dependabot.yml, .github/workflows/add-markdown-feedback.yml, .github/workflows/lint-csharp.yml, .github/workflows/scan-for-to-do-comments.yml, eng/Version.Details.xml, eng/Versions.props, eng/dependabot/independent/Packages.props, eng/dependabot/independent/Versions.props, global.json
=> Merger feature/9.x into release/9.x

documentation/releaseNotes/releaseNotes.v9.0.0-preview.6.md
Fix spelling so that spell checker doesn't flag these as errors.
=> Fix spelling in release notes

eng/helix/Helix.proj
=> Add Azure Linux 3.0 helix queues

global.json
Update .NET SDK to 9.0 Preview 7
=> [feature/9.x] Update .NET SDK

documentation/configuration/view-merged-configuration.md
Fix command to dotnet-monitor
Fix dotnet-monitor command
=> Update view-merged-configuration : update command

.github/releases.json, documentation/releases.md
=> Add 6.x EOL date

documentation/README.md
=> Remove SSL item from readme

eng/pipelines/jobs/build.yml
=> Update public Linux build machines to Ubuntu 22.04

eng/pipelines/stages/preparerelease.yml, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj
=> Update release tool to .NET 8 and update dependencies

eng/pipelines/jobs/build.yml
Manual backport of #7283 to release/6.x
=> [release/6.x] Update public Linux build machines to Ubuntu 22.04

documentation/configuration/azure-ad-authentication-configuration.md, documentation/security-considerations.md
Update security considerations docs with Entra ID related information.
=> Add security considerations for Entra ID auth

eng/pipelines/jobs/test-binaries.yml
=> Pin Azurite

documentation/configuration/configuration-sources.md, documentation/configuration/egress-configuration.md, documentation/security-considerations.md
Justin and I chatted briefly yesterday about what recommendations we want since this isn't an area where I have a lot of expertise - if people want to adjust/add to this guidance, we can rework this, but I figured I'd put this up for initial feedback.
=> Add security considerations for managing secrets

eng/Version.Details.xml, eng/Versions.props, eng/pipelines/jobs/tpn.yml, src/Directory.Build.props
Add PackageReference for System.Text.Json to allow participation in dependency flow.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2551375&view=results
=> [release/6.x] Add System.Text.Json PackageReference with latest version

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Fixtures/AzuriteFixture.cs
=> [release/6.x] Disable Azurite tests

documentation/configuration/metrics-configuration.md, documentation/security-considerations.md
=> Security considerations for metrics

eng/pipelines/stages/preparerelease.yml, eng/release/Scripts/AcquireBuild.ps1
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2552320&view=logs&j=9c2ccffd-8e7d-5b34-ccf9-d3f1053322e9&t=4fd9d253-d592-541b-cb24-178afb820382
=> Use DotNetStaging service connection credentials to gather drop

eng/release/Scripts/AcquireBuild.ps1
=> Remove extra verbose switch

eng/helix/Helix.proj
=> [release/8.0]Fixup package version

NuGet.config, eng/Version.Details.xml, eng/Versions.props
=> [release/6.x] Merge internal to public

eng/Version.Details.xml, eng/Versions.props, eng/dependabot/net9.0/Versions.props
=> [release/9.x] Merge internal to public

global.json
=> [main] Update SDK

global.json
=> [feature/9.x] Update SDK

global.json
=> [release/8.0] Update SDK

.github/dependabot.template.yml, .github/dependabot.yml, eng/dependabot/net9.0/Packages.props
=> Fix .NET 9 dependabot updates

eng/dependabot/net9.0/Versions.props
=> Update .NET 9 System.Text.Json to 9.0.0

eng/pipelines/jobs/tpn.yml
=> Add retry to notice generation

NuGet.config, eng/Version.Details.xml, eng/Versions.props
=> [release/9.x] Sync branch

documentation/egress.md
=> Update egress download URLs

global.json
=> Remove `xcopy-msbuild` version for `release/9.x`

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj
=> Suppress TFM support for functional tests for .NET 6 and 7

.github/dependabot.template.yml, .github/dependabot.yml, eng/Version.Details.xml, eng/Versions.props, eng/common/sdk-task.ps1, eng/common/tools.ps1, eng/dependabot/independent/Versions.props, global.json, src/Extensions/AzureBlobStorage/Program.cs, src/Extensions/S3Storage/Program.cs, src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Scenarios/ExceptionThrowCatchScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Scenarios/ExceptionThrowCrashScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AspNetScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AsyncWaitScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/EnvironmentVariablesScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExecuteScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/FunctionProbes/FunctionProbesScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/MetricsScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ParameterCapturingScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/SpinWaitScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/TraceEventsScenario.cs, src/Tools/dotnet-monitor/Program.cs
=> Merge main to release/8.x

.config/1espt/PipelineAutobaseliningConfig.yml, .config/guardian/.gdnbaselines
Baseline updates for 1ES pipeline template compliance tooling.
=> Update 1ES PT baselines

NuGet.config, eng/Version.Details.xml, eng/Versions.props
=> Merge main to release/9.x

.github/workflows/sync-branches.yml
- Stop non-code flow to `release/8.0`
- Start non-code flow to `release/9.0`
- Start code flow to `feature/10.0`
=> Code flow updates

eng/pipelines/dotnet-monitor-publish.yml
=> Fixup syntax

eng/pipelines/dotnet-monitor-publish.yml
=> Build pipeline Fixups

eng/helix/Helix.proj
=> Update helix queue

.config/1espt/PipelineAutobaseliningConfig.yml
=> Update 1ESPT baseline config

src/Extensions/AzureBlobStorage/AzureBlobEgressProvider.cs
=> Remove obsolete reference

src/Tests/Microsoft.Diagnostics.Monitoring.AzureBlobStorageTests.UnitTests/AzureBlobEgressProviderTests.cs
=> Fixup test case

eng/dependabot/independent/Versions.props, src/Extensions/S3Storage/S3Storage.cs
* Update AWS packages
* Fix build issues
=> [release/9.0] Update AWS packages (#8334) (#8360)

eng/dependabot/independent/Versions.props, src/Extensions/S3Storage/S3Storage.cs
* Update AWS packages
* Fix build issues
=> [release/8.x] Update AWS packages (#8334) (#8360)

.config/1espt/PipelineAutobaseliningConfig.yml, eng/Version.Details.xml, eng/Versions.props, eng/common/core-templates/job/job.yml, eng/common/internal/NuGet.config, eng/common/tools.ps1, eng/dependabot/independent/NuGet.config, eng/dependabot/independent/Versions.props, eng/dependabot/net8.0/NuGet.config, eng/dependabot/net8.0/Versions.props, eng/dependabot/net9.0/NuGet.config, eng/dependabot/net9.0/Versions.props, eng/helix/Helix.proj, eng/pipelines/dotnet-monitor-release.yml, global.json, src/Tools/dotnet-monitor/CommonOptionsExtensions.cs, src/Tools/dotnet-monitor/Program.cs
Only conflicts were minor version updates in tooling, resolved in favor of main.
=> [release/9.x] Merge main to release/9.x

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs
=> [release/10.0]Fix dump tests

.github/workflows/sync-branches.yml
=> Sync release/10.0

eng/Versions.props
=> Fixup 10.0 release

.github/linters/check-markdown-links-config.json, documentation/egress.md
=> Fix broken link

src/archives/Directory.Build.props
=> [TESTING] Fix archive
