src/Tools/dotnet-monitor/AddressBindingResults.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/ExperimentalToolLogger.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Startup.cs
Route address binding failures through logging so that anything scraping stdout can more easily parse the errors.
Additional changes:
- Move authentication log messages to LoggingExtensions.
- Handle invalid addresses when parsing binding addresses.
Sample output when SSL cert is not configured and when authentication is disabled:
```
11:57:08 warn: Microsoft.Diagnostics.Tools.Monitor.ExperimentalToolLogger[0]
WARNING: dotnet-monitor is experimental and is not intended for production environments yet.
11:57:09 fail: Microsoft.Diagnostics.Tools.Monitor.Startup[0]
Unable to bind to https://localhost:52323. Dotnet-monitor functionality will be limited.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer …
```
=> Route address binding failures through logging.

dotnet-monitor.yml, eng/build.yml
Overview:
- Publish artifacts for internal builds.
- Set _BuildConfig variable.
- Execute SDL checks on PackageArtifacts artifact.
Sample internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=999305
=> Fix build to publish artifacts and run SDL checks on packages.

eng/Publishing.props
The dotnet-docker repo uses the *.nupkg.version file to detect the latest package version, so it is not necessary to publish the package to the blob feed. The package is still published to the dotnet-tools NuGet package feed.
=> Don't publish nupkg to blob feed

eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj
Upgrades the following packages to the minimal version that are secure.
- Microsoft.AspNetCore.Http
- Microsoft.AspNetCore.Server.Kestrel.Core
- System.IO.Pipelines
Removed other packages that are not referenced:
- Microsoft.AspNetCore
- Microsoft.AspNetCore.HttpsPolicy
- Microsoft.AspNetCore.ResponseCompression
Lastly, change ASP.NET Core references to version ranges that end at 2.2.0 exclusively.
=> Upgrade ASP.NET Core 2.1 packages to secure versions

src/Tools/dotnet-monitor/AddressListenResults.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Startup.cs
This change allows dotnet-monitor to report which addresses are default and which are metrics. This will be used for testing when telling dotnet-monitor to bind to any port for each of these types of addresses, e.g.
```
dotnet-monitor collect --urls https://127.0.0.1:0 --metricUrls http://127.0.0.1:0
```
Output (with Debug log level set for Microsoft.Diagnostics logging category):
```
17:33:31 warn: Microsoft.Diagnostics.Tools.Monitor.ExperimentalToolLogger[0]
WARNING: dotnet-monitor is experimental and is not intended for production environments yet.
17:33:32 warn: Microsoft.AspNetCore.Server.Kestrel[0]
Overriding address(es) 'https://127.0.0.1:0'. Binding to endpoints defined in UseKestrel() instead.
17:33:32 info: Microsoft.Hosting.Lifetime[0]
Now listening on: https://127.0.0.1:53960 …
```
=> Log bound default vs metrics addresses.

eng/Tools.props
With this change, dotnet-monitor can be built and tested on Linux.
=> Install ASP.NET Core on Unix systems.

src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/MetricsTests.cs
Increase test timeout to 1 minute to allow for tests to pass on resource constrained machines. The purpose of the tests is not to measure performance; the timeouts are just a means of giving up on the test so that the builds do not hang for the maximum timeout.
=> Increase test timeouts to 1 minute.

eng/Versions.props, src/Directory.Build.targets
The current aka.ms link generation for the latest version produces a link that represents the absolute latest version within a given release. For example, the link 'aka.ms/dotnet/diagnostics/monitor5.0/dotnet-monitor.nupkg.version' only allows for pointing to a single version within the 5.0.X release.
In order to allow dotnet-docker to consume a specific preview version, the link generation needs to be updated to include the prerelease information. This change adds the prerelease information as a subfolder to the existing blob group name calculation. It also introduces a build quality notion that is similar to aka.ms channel build quality so that the main branch does not have to declare its release name.
For example, we could fork main into a release branch (which would build preview 4 …
=> Have blob group include release subfolder based on build quality.

src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Fixtures/DefaultCollectionFixture.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Fixtures/ServiceProviderFixture.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/MetricsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/DotNetMonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/DotNetMonitorRunnerExtensions.cs
There is a problem in the tests where HttpClient.SendAsync will hang and only return when cancelled. This happens due to exhaustion of the available sockets for use by HttpClientHandler.
To mitigate this, create an HttpClientFactory (via the AddHttpClient service method in the ServiceProviderFixture) which pools HttpClientHandlers. The ServiceProviderFixture provides for two HttpCliendHandlers: a default one and one that authenticates with the current user credentials. All of the tests use the default one except for NegotiateAuthenticationSchemeTest which uses the one with default credentials.
Additional refactoring to the ApiClient was done to remove the privately created HttpClient since it shouldn't encourage the use of separately instantiated HttpClient instances.
=> Use HttpClientFactory shared among tests to avoid socket exhaustion.

documentation/schema.json, dotnet-monitor.sln, eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.RestServer/CorsConfiguration.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsOptions.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsOptionsDefaults.cs, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/SchemaGenerationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Microsoft.Diagnostics.Monitoring.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Options/EgressOptions.cs, src/Tests/test.runsettings, src/Tools/dotnet-monitor/Auth/ApiAuthenticationOptions.cs, src/Tools/dotnet-monitor/DiagnosticPortOptions.cs, src/Tools/dotnet-monitor/DiagnosticPortOptionsDefaults.cs
Generate schema for dotnet-monitor configuration. This uses https://github.com/RicoSuter/NJsonSchema
=> Generate schema for configuration options

eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj
The System.Text.Encodings.Web package is has vulnerabilities; Component Governance advisory says to upgrade to 4.7.2
=> Update System.Text.Encodings.Web to 4.7.2 for RestServer netstandard2.0

eng/Versions.props
This change causes the aka.ms link generation to include the prerelease information in the blob group (e.g. https://aka.ms/dotnet/diagnostics/monitor5.0/preview.4/dotnet-monitor.nupkg.version) so that the preview version can be stabilized independently of the main branch updating the daily link.
closes #79
=> Set blob group to include prerelease information.

documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.RestServer/ActionContextExtensions.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/ContentTypes.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/MetricsController.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/Models/EventPipeConfiguration.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/Models/EventPipeProvider.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/ProducesWithProblemDetailsAttribute.cs, src/Tools/dotnet-monitor/Startup.cs
- Require at least one event pipe provider in POST /trace route body.
- Validate EventLevel on event pipe provider is one of the known event levels.
- Add content type when custom action result has exception.
- Set Bad Request content type only to application/problem+json.
=> Additional model validation and content type fixes.

src/Tools/dotnet-monitor/DiagnosticPortValidateOptions.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs
If listen connection mode is specified via configuration without specifying the diagnostic port name, the reversed server will silently fail to bind, thus no applications can be discovered and the user has no indication of the failure.
This change validates that the diagnostic port endpoint name is specified if running in listen mode. If not specified, the tool will fail to startup and the validation failures are sent through logging:
```
21:48:42 crit: Microsoft.Diagnostics.Tools.Monitor.DiagnosticsMonitorCommandHandler[20]
In 'Listen' mode, the diagnostic port endpoint name must be specified.
```
=> Validate that diagnostic port endpoint name is specified if running in listen mode.

eng/Version.Details.xml, eng/Versions.props, global.json, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetFrameworkReference.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Microsoft.Diagnostics.Monitoring.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/MonitorRunner.cs
This change allows running tests on .NET 6, which required splitting the `DotNetHost.CurrentRuntimeVersion` property into two (one for the runtime version and one for the ASP.NET version) so that dotnet-monitor can be run on the ASP.NET runtime and the unit test app can be run .NET runtime.
closes #144
=> Add .NET 6 runtimes and run tests on .NET 6.

eng/build.yml
The test results for each build again are all merged together into one result upload, thus its difficult to determine for which runtime version a test fails. This change separates the uploads by runtime version for easier discernment.
=> Publish tests results per runtime version.

src/Microsoft.Diagnostics.Monitoring.RestServer/ConfigurationHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tools/Common/CommandExtensions.cs, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/Egress/AzureBlobEgressFactory.cs, src/Tools/dotnet-monitor/Egress/Configuration/EgressConfigureOptions.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Program.cs
Addresses issue #125
``` json
Sample output:
{
"urls": "https://localhost:52323",
"Kestrel": {
"Certificates": {
"Default": {
"Path": "/etc/aspnet/customcert/customcert.pfx",
"Password": "REDACTED"
}
}
},
"CorsConfiguration": "NOT PRESENT",
"DiagnosticPort": {
"ConnectionMode": "Connect",
"EndpointName": null
},
"Metrics": {
"AllowInsecureChannelForCustomMetrics": "False",
"Enabled": "True",
"Endpoints": "http://localhost:52325",
"IncludeDefaultProviders": "True",
"MetricCount": "3",
"UpdateIntervalSeconds": "10"
},
"Storage": {
"DumpTempFolder": "/tmp/"
},
"ApiAuthentication": {
"ApiKeyHash": "REDACTED",
"ApiKeyHashType": "SHA256"
},
"Egress": {
"Properties": {
"MonitorBlobAccountKey": "REDACTED"
},
"Providers": {
"monitorBlob": {
"Type": "azureBlobStorage",
"AccountUri": …
```
=> Adding new command to display configuration

src/Tools/dotnet-monitor/Auth/AuthOptions.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Startup.cs
Resolve issue #5: Add warning when running as an elevated processes
- Adds a warning when launched as admin on windows:
```
11:53:37 warn: Microsoft.Diagnostics.Tools.Monitor.Startup[21]
The process was launched elevated and will have access to all processes on the system. Do not run elevated unless you need to monitor processes launched by another user (e.g., IIS worker processes)
```
- Adds warning when launched as admin on windows and NTLM auth is enabled:
```
11:53:37 warn: Microsoft.Diagnostics.Tools.Monitor.Startup[22]
Negotiate, Kerberos, and NTLM authentication are not enabled when running with elevated permissions.
```
=> Add logged warnings for elevated launch on windows

dotnet-monitor.yml
GitHub security policies require that the dotnet-monitor-ci build completes, however the pipeline definition excludes some paths such as documentation. Thus, PR owners cannot complete pull requests due to blocking on a condition that will never complete. This change removes the exclusions to have the pipeline run for all changes.
=> Allow PR build to run on all changes

src/Microsoft.Diagnostics.Monitoring.RestServer/ScopeState.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/StreamingLogger.cs
C# code that logs:
```cs
try
{
throw new InvalidOperationException("Uh oh!");
}
catch (Exception ex)
{
_logger.LogError(new EventId(7, "FailedAfterRetries"), ex, "Failed to get resource after {attempts} attempts.", 5);
}
```
will appear in the `/logs` call (`application/x-ndjson`) as:
```json
{
"LogLevel": "Error",
"EventId": 7,
"EventName": "FailedAfterRetries",
"Category": "WebApplication1Pages.IndexModel",
"Message": "Failed to get resource after 5 attempts.",
"Exception": "System.InvalidOperationException: Uh oh!\r\n   at WebApplication1.Pages.IndexModel.OnGet() in C:\\Users\\username\\source\\WebApplication1\\WebApplication1\\Pages\\Index.cshtml.cs:line 25",
"State": {
"Message": "Failed to get resource after 5 attempts.",
"attempts": "5",
"{OriginalFormat}": "Failed to get resource …
```
=> Write ndjson logs in same format at JsonConsoleFormatter and event-stream logs in format as SimpleConsoleFormatter

documentation/api/defaultprocess.md, documentation/api/definitions.md, documentation/api/dump.md, documentation/api/gcdump.md, documentation/api/logs.md, documentation/api/processes-env.md, documentation/api/processes-get.md, documentation/api/trace-custom.md, documentation/api/trace-get.md, documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/DiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/Models/ProcessIdentifier.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/ProcessKey.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs
This change allows process selection based on the process name.
For example, a request such as
```http
GET /processes/pwsh
```
would yield a response such as
```json
{
"pid": 13564,
"uid": "199efe46-595b-4640-b957-1fbf7ee78c26",
"name": "pwsh",
"commandLine": "\"C:\\Program Files\\PowerShell\\7\\pwsh.exe\"",
"operatingSystem": "Windows",
"processArchitecture": "x64"
}
```
The resolution of zero or more than one process remains unchanged.
Additional changes include adding the process name to the `/processes` route:
```json
[
{
"pid": 13564,
"uid": "199efe46-595b-4640-b957-1fbf7ee78c26",
"name": "pwsh"
},
{
"pid": 20412,
"uid": "87596ba0-b92f-47c9-b065-1cb271d41645",
"name": "dotnet"
},
{
"pid": 21308,
"uid": "00000000-0000-0000-0000-000000000000",
"name": "WebApplication3"
}
]
```
and …
=> Add ability to specify process name to process selection algorithm.

eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
This change has dotnet-monitor use the UseAppFilters sentinel on all runtime versions since the 3.1.15 patch version contains the ability to use the UseAppFilters sentinel in this LoggingEventSource. 
closes #159
closes #183
=> Use UseAppFilters for all runtime versions.

documentation/api/definitions.md, documentation/api/logs-custom.md, documentation/api/logs-get.md, documentation/api/logs.md, documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.RestServer/Models/LogsConfiguration.cs
Add POST /logs route. The body is a object with the following properties:
- `logLevel`: Default log level for any category without a log level.
- `filterSpecs`: The key-value pairs of categories and log levels that should be collected.
- `useAppFilters`: Include the application-defined filters.
Example request:
```http
POST /logs/2584?durationSeconds=15 HTTP/1.1
{
"filterSpecs": {
"Microsoft.AspNetCore.Hosting": "Information"
},
"useAppFilters": false
}
```
Example response:
```http
HTTP/1.1 200 OK
Content-Type: text/event-stream
﻿data: Information Microsoft.AspNetCore.Hosting.Diagnostics[1]
data: 2021-05-13 18:06:41Z
data: Request starting HTTP/1.1 GET http://localhost:5000/  
data: => RequestId:0HM8M726ENU3K:0000002B, RequestPath:/, SpanId:|4791a4a7-433aa59a9e362743., …
```
=> Add POST /logs route

eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.RestServer/Models/LogsConfiguration.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ContentTypes.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Microsoft.Diagnostics.Monitoring.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Models/LogEntry.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/ScenarioRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/TestTimeouts.cs
This change adds tests for the `GET /logs` and `POST /logs` routes and tests each aspect of those routes. It tests these routes using newline-delimited JSON responses since those are relatively easy to process.
=> Tests for logs routes.

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/TestConditions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/TestTimeouts.cs
These changes:
- Enable Linux dump testing. Required parsing ELFHeaderIdent header to determine bitness and endianness before adding ELF parsing types for the full ELFHeader header.
- Enable Mach-O dump testing for .NET 6+ on OS X.
closes #228
closes #322
=> Enable Linux dump tests and OS X Mach-O verification

src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/LogsTests.cs
This change allows the logs tests to flex the EventLogsPipeline code path that handles log events that do not have a message format (https://github.com/dotnet/diagnostics/blob/614bad036c73b37123d5f8db6e383164d452429d/src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs#L155).
=> Update logs tests to have custom logger state.

src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationHandler.cs, src/Tools/dotnet-monitor/ConfigurationBuilderExtensions.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
This change fixes key-per-file configuration to signal the change token when data is reloaded. This is a workaround until https://github.com/dotnet/aspnetcore/issues/32836 is fixed. This change enables the use of dependency injection to acquire key-per-file options from configuration and perform other options operations, such as post configuration and validation, in future changes.
=> Fix key-per-file to signal change token.

src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationHandler.cs, src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationHostedService.cs, src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationOptions.cs, src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationOptionsChangeTokenSource.cs, src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationOptionsObserver.cs, src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationPostConfigureOptions.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Startup.cs
How this works:
- `ApiKeyAuthenticationOptions` is updated to contain the validated hash algorithm, hash value, and validation errors.
- `ApiKeyAuthenticationPostConfigureOptions` fills in properties on the `ApiKeyAuthenticationOptions` instance based on the validated properties from `ApiAuthenticationOptions`.
- `ApiKeyAuthenticationOptionsChangeTokenSource` listens for changes to `ApiAuthenticationOptions` and signals that `ApiKeyAuthenticationOptions` has changed when the change occurs.
- `ApiKeyAuthenticationHostedService` logs the initial state of the API Key configuration, listens for changes to `ApiKeyAuthenticationOptions`, and logs the updated state on the change.
- `ApiKeyAuthenticationHandler` checks if there are any `ApiKeyAuthenticationOptions` validation errors, and if there …
=> Log authentication configuration errors on startup, configuration change, and HTTP requests.

src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/LogsTests.cs
- Enable event name verification in logs tests.
- Enable default log level none tests.
=> Enable test fixes due to bug fixes from dotnet/diagnostics

src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTests/Runners/MonitorRunnerExtensions.cs, src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationHandler.cs, src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationPostConfigureOptions.cs, src/Tools/dotnet-monitor/Auth/AuthOptions.cs, src/Tools/dotnet-monitor/Auth/GeneratedApiKey.cs, src/Tools/dotnet-monitor/Auth/IAuthOptions.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Startup.cs
- Add `--temp-apikey` option to generate an APIKey during startup
- Prints the temporary key to the console like this:
```
D:\repos\github\dotnet-monitor-kelltrick [dev/pafenelo/eph2 ≡ +0 ~9 -0 !]> D:\repos\github\dotnet-monitor-kelltrick\artifacts\bin\dotnet-monitor\Debug\netcoreapp3.1\dotnet-monitor.exe collect --temp-apikey
13:45:24 warn: Microsoft.Diagnostics.Tools.Monitor.Startup[23]
Generated one-time-use ApiKey for dotnet-monitor; use the following header for authorization:
Authorization: MonitorApiKey Un3LJob3MqrR69WmFFNiU6G7U6QqgF0cY/Tm4FWSjxI=
13:45:24 warn: Microsoft.AspNetCore.Server.Kestrel[0]
Overriding address(es) 'https://localhost:52323'. Binding to endpoints defined in UseKestrel() instead.
```
- Add test hook to add commandline flag `--temp-apikey`, add test to exercise …
=> Ephemeral Keys

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/AuthenticationTests.cs
The `RNGCryptoServiceProvider` is [obsolete](https://github.com/dotnet/runtime/blob/ebd695fee1ccccac472e39adb2a2469e89a7ccb2/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/RNGCryptoServiceProvider.cs#L8) in .NET 6. Replace usage with `RandomNumberGenerator.Create`, which is what `RNGCryptoServiceProvider` was doing internally all the back to .NET Core 3.1.
=> Fix obsolete type usage error in tests.

src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
When the settings.json file is incorrectly configured, a crash results. This handles the error and gracefully exits with an error message pointing the user to the issue.
```
Could not parse the JSON file.
'"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 6 | BytePositionInLine: 33.
```
closes #203
=> Handles incorrectly formatted settings.json files by catching the System.FormatException and outputting a readable error message for the user.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestTimeouts.cs
Increasing the dump collection timeout to help mitigate #440. Adding additional logging for request durations to help track down similar issues in the future.
=> Increase dump collection timeout and log request durations.

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Runners/MonitorRunner.cs
Sometimes the tests on MacOS just hang and timeout waiting for the dotnet-monitor process to start. It's difficult to see why that is happening but one cause might be that the process exits before it becomes ready. These changes await for the process to be ready OR exit. If it exits before it is ready, then throw an exception to fail the test.
=> Check if test process exits before it is ready

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ProcessTests.cs
Also run identifier checks for each process.
=> Skip uid-only check for failed uid values.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ProcessTests.cs
I created #523 to so that we can better mitigate this type of problem. We can never guarantee that we get all of the process information on the first call, but once we getting it, we should be able to cache it.
=> Retry process routes when name is "unknown"

documentation/api/trace-custom.md, documentation/api/trace-get.md
Addresses the issue of inaccessible .nettrace files when prematurely terminating a trace. This behavior will likely be resolved in the future; the documentation is meant to notify users that this is a known issue until it is addressed.
=> Indefinite Trace Documentation

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EgressTests.cs
The ConcurrentLimitTest fails very frequently to the point that it effectively blocks PRs from being completed. Disable the test for now until the issue with the test is fixed.
=> Skip ConcurrencyLimitTest

src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/ConfigurationKeys.cs
Note: I wasn't entirely sure about the scope of the issue based on what's written in #481, so if this is completely different than what was intended let me know. I essentially just latched onto the existing functionality for config show and added in Logging as one of the outputs. This is an example of the new output for `config show`
Closes #481
=> 'config show' now outputs Logging info from appsettings.json

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EgressTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Runners/ScenarioRunner.cs
Added in two test cases to ensure the proper error ensues when using the --no-http-egress flag for dumps and logs.
=> Disable http response egress - testing

src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.AutoFlushStream.cs, src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs
Some other considerations:
- We could push this logic out of the egress provider and into trace directly. We would need to break down CopyToAsync and periodically flush. I chose this approach since it ensures that anything that gets egressed to azure flushes on certain boundaries.
- The default buffer size in this PR and in the blob client is 4Mi. We could make this smaller and see data at an even more granular level. This would mean less memory usage, better data availability, but more frequent commit calls.
=> Automatically flush trace data to Azure storage.

documentation/schema.json, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
This change allows adding more discriminated subschemas in the future without reimplementing the concept for each set of options. Also, generate schemas from type information and cache it in a resolver so that type schemas can be reused across multiple type generations.
=> Refactor schema gen to generically create discriminated subschemas

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EventPipeProvider.cs, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectDumpOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectDumpOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectGCDumpOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLogsOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLogsOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/ExecuteOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleLimitsOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleLimitsOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetRequestCountOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetRequestCountOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetRequestDurationOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetRequestDurationOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetResponseStatusOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetResponseStatusOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterOptions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/EventCounterOptionsDefaults.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/IAspNetActionPathFilters.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/TriggerOptionsConstants.cs
- Generate action and trigger options in schema.
- Add display name descriptions to these options.
- Add defaults for the optional properties.
- Other small changes such as property renames and changing IncludePaths and ExcludePaths property to arrays.
=> Generate action and trigger options in schema.

src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/SchemaGenerationTests.cs
This adds a more detailed output to `TestSchemaBaseline` to make it easier at a glance to tell what changed in `schema.json` when the baseline differs from the checked-in schema.
- ![image](https://user-images.githubusercontent.com/700511/129313270-35d9dfb7-b74f-48dd-bc86-f89565eab4af.png)
- ![image](https://user-images.githubusercontent.com/700511/129314899-aeb0472b-e187-4de4-b20f-594803b0126b.png)
=> Add detailed message to output in TestSchemaBaseline

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TaskExtensions.cs
The CTS should be disposed.
Unconditionally call Cancel on the CTS since it will short-circuit if the underlying tokens were already cancelled.
=> Small changes to the WithCancellation extension method.

dotnet-monitor.sln, src/Microsoft.Diagnostics.Monitoring.Options/Microsoft.Diagnostics.Monitoring.Options.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/SchemaGenerationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/AssemblyHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tools/dotnet-monitor/EndpointInfo/ClientEndpointInfoSource.cs, src/Tools/dotnet-monitor/EndpointInfo/EndpointInfo.cs, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
The collection rule system will hook directly into the ServerEndpointInfoSource (and eventually, the ClientEndpointInfoSource), so this class needs to move to the dotnet-monitor project. This means that the unit tests for these types need to move to a new unit test assembly for dotnet-monitor (this unit test assembly already exists in the feature/triggers branch, but I'm bringing it to the main branch). As part of this, I've refactored entry point assembly path calculation for the tests into a common helper since I needed to changed some of the ServerEndpointInfoSource tests into theories with each supported TFM.
- Move *EndpointInfo implementations to dotnet-monitor.
- Add dotnet-monitor unit test assembly and move *EndpointInfo tests to it.
- Consolidate calculating …
=> Move *EndpointInfo implementations to dotnet-monitor.

documentation/releaseNotes/releaseNotes.md, documentation/releaseNotes/releaseNotes.v5.0.0-preview.6.21370.3.md
- Clear release notes for preview 7 for after snap
- Archive preview 6 released notes for testing release pipeline
=> Post preview 7 snap release notes update

documentation/releaseNotes/releaseNotes.v5.0.0-preview.7.21420.5.md
- Adds release notes for candidate build [5.0-preview.7](https://aka.ms/dotnet/diagnostics/monitor5.0/preview.7/dotnet-monitor.nupkg.version)
=> Add release notes for preview 7 canidate build to main

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/LoggingRunnerAdapter.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TaskExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/EgressTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/ScenarioRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tools/dotnet-monitor/EndpointInfo/IEndpointInfoSourceCallbacks.cs, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
There's a race condition between when the ServerEndpointInfoCallback is invoked due to a process connecting in reverse mode and the LoggingRunnerAdapter setting the process Id information just after starting the process. Sometimes the reverse server callback is quicker than the adapter, which will then fail to find the runner with a matching process ID.
I changed the code so that the LoggingRunnerAdapter has an additional ProcessIdTask property so that it can be awaited. the ServerEndpointInfoCallback has been updated to await the ProcessIdTask property of each registered runner and process each one as they complete. This guarantees that ServerEndpointInfoCallback will wait for the runner to fulfill the process ID or be cancelled first.
=> Fix race condition in EndpointInfoSourceTests.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs
The logs functional tests fail for .NET Core 3.1 on Windows sporadically but frequent enough to hold up many PR and CI builds. I have not been able to reproduce the issue (no logs are reported via the HTTP endpoint when the issue occurs) manually nor have I see it on local test runs. I'm skipping these tests for .NET Core 3.1 on Windows for now until that root cause can be determined.
=> Skip logs functional tests for .NET Core 3.1 on Windows.

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs, src/Tools/dotnet-monitor/EndpointInfo/ClientEndpointInfoSource.cs, src/Tools/dotnet-monitor/EndpointInfo/EndpointInfo.cs, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
These changes rely on the following PR from the diagnostics repo: https://github.com/dotnet/diagnostics/pull/2350
These changes only switch to using the async APIs on the DiagnosticsClient class. Subsequent changes to timeout on querying the process list will be made in a different PR.
=> Use async DiagnosticsClient APIs

documentation/README.md, documentation/api/collectmetrics-custom.md, documentation/api/collectmetrics-get.md, documentation/api/collectmetrics.md, documentation/api/definitions.md, documentation/api/gcdump.md, documentation/api/logs-custom.md, documentation/api/logs-get.md, documentation/api/operations-delete.md, documentation/api/operations-get.md, documentation/api/operations-list.md, documentation/api/process-env.md, documentation/api/process-get.md, documentation/api/processes-list.md, documentation/api/trace-custom.md, documentation/api/trace-get.md, documentation/releaseNotes/releaseNotes.md
- Also fixup some examples for Bearer
=> Documentation for metrics

src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs
In recent builds, the `/processes` route is failing to calculate the process name on .NET Core 3.1 for MacOS. The timeout for determining the extra process information, such as command line and process name, is too short. This change increases the timeout to 1 second which seems to be sufficient to work around the problem.
In the long term, this code should be changed to cache process information between lookups so that subsequent querying for process information is fast and accurate. Re #523
=> Increase extra process information timeout.

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/ActionsServiceCollectionExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Triggers/ManualTrigger.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Triggers/TriggersServiceCollectionExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/SpinWaitScenario.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/ExecuteAction.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRulePipeline.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/EventCounterTriggerFactory.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/EventPipeTriggerFactory.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/StartupTrigger.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/StartupTriggerFactory.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx, src/Tools/dotnet-monitor/TaskExtensions.cs
These changes create a new pipeline for executing a collection rule. The current implementation handles both non-startup and startup triggers, all action types, and enforces the configured limits. Tests were implemented to test the behavior of the pipeline for the startup trigger, event counter trigger, and collection rule limits.
Aspects deferred to future changes:
- Tests for validating negative cases (cancellation, bad-acting triggers, bad-acting actions).
- Asynchronous action execution.
- Logging
=> Implement collection rule pipeline, event counter trigger, and tests.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs
This is an effort to fix the following test failure: https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3Adotnet-monitor-ci+name%3ACollectionRulePipeline_StartupTriggerTest
My belief that that the callback is failing to register before the pipeline finishes is causing the TCS to not be completed and thus causing the test to fail with a TaskCanceledException. The changes make sure that the callback TCS is registered before yielding back another Task that represents the invocation of the callback, thus ensuring that the callback is registered before the test continues to start the pipeline.
I will run this PR through the build several times to see if this fixes the issue before completing it:
- Build [20210914.9](https://dev.azure.com/dnceng/public/_build/results?build …
=> Fix CollectionRulePipelineTests failure due to callback registration timing.

src/Tools/dotnet-monitor/EndpointInfo/ClientEndpointInfoSource.cs, src/Tools/dotnet-monitor/FilteredEndpointInfoSource.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
This change allows dotnet-monitor to skip waiting for unresponsive processes in `connect` mode. Prior to this change, any unresponsive process that dotnet-monitor attempts to communicate with will cause HTTP requests to hang indefinitely until canceled. The change gives a brief window in which processes must respond; otherwise, dotnet-monitor will skip the inclusion of those offending processes in the process list.
This was tested on my local machine using WSL2; the unresponsive processes are skipped whereas the responsive ones are reported via the `/processes` route.
I will run the CI build several times to check that this fixes the `/processes` hang issue that is seen in various tests. Build results:
- Build [20210916.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1367731& …
=> Cancel waiting for unresponsive processes.

src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.CollectionRule.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestTimeouts.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
This change filters collection rules based on the filters specified in configuration. It includes a refactor of the DiagnosticServices+ProcessInfo class to a separate ProcessInfoImpl class as well as a few basic tests to verify that the rules are able to be conditionally applied.
closes #870
=> Implement collection rule filters.

src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs
This change refactors collection rule startup and running into a separate container class which each instance is associated with a specific process. This will allow easy incorporation of future changes, such as:
- Changing triggers and actions to be scoped to individual processes.
- Detecting when a process shuts down and stopping the rules associated with the process.
- Restarting rules for each previously discovered process when configuration changes.
=> Refactor collection rule startup into containers.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/ActionListExecutor.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRulePipeline.cs
This change allows action completion to be deferred by default such that all actions are startup asynchronously (but in order), signal startup has completed, and then wait for completion on all deferred action completions. Actions can opt into synchronous completion by setting the WaitForCompletion property to true e.g.
```json
{
"Type": "CollectTrace",
"Settings": { ... },
"WaitForCompletion": true
}
```
=> Allow action completion to be deferred.

NuGet.config, eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tools/dotnet-monitor/Auth/UserAuthorizationHandler.cs, src/Tools/dotnet-monitor/ConfigurationBuilderExtensions.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This change migrates dotnet-monitor to run only on the .NET 6 (or higher) runtime.
- Add net6.0 TFMs and fix build.
- Update tests to support running net6.0 dotnet-monitor.
- Remove netcoreapp3.1 TFM from dotnet-monitor and tests.
=> Migrate to .NET 6

src/Tools/dotnet-monitor/Startup.cs
Disabling due to https://github.com/dotnet/aspnetcore/issues/36960 since Preview 8 will likely ship on top of ASP.NET 6.0 RC 1.
=> Disable response compression

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/MetricsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.CollectionRule.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestTimeouts.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs, src/Tools/dotnet-monitor/CollectionRules/Configuration/CollectionRulesConfigurationChangeTokenSource.cs, src/Tools/dotnet-monitor/CollectionRules/Configuration/CollectionRulesConfigurationProvider.cs, src/Tools/dotnet-monitor/DynamicNamedOptionsCache.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
This change plumbs through the ability to stop and restart collection rules on all processes when the collection rule configuration changes.
~~TODO: Add functional test that verifies that a rule change is actually reflected in the tool and can be observed.~~ Done
closes #657
=> Restart collection rules when configuration changes.

eng/Versions.props, eng/build.yml, src/Directory.Build.props
Collect hang dump for the test host when individual tests run longer than 3 minutes.
closes #620
=> Collect dumps for hanging tests

dotnet-monitor.yml, eng/build.yml
Per https://github.com/dotnet/core-eng/issues/14276.
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1404326&view=results
=> Switch to 1ES servicing pools on release/5.0

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.CollectionRule.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleEndpointInfoSourceCallbacks.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs
The change removes collection rules associated with a process when that process is no longer detected (e.g. it exited, crashed, etc). A test has been added to verify that removal is detectable.
closes #962
=> Remove collection rules when process is no longer detected.

eng/Versions.props, src/Directory.Build.props
Use newer System.Private.Uri to avoid restoring the 4.3.0 version so that component scanning doesn't pick it up. See https://github.com/dotnet/announcements/issues/97 for the issue that upgrading addresses. From what I can see, this change does not affect the build output.
=> Use newer System.Private.Uri library.

src/Tools/dotnet-monitor/dotnet-monitor.csproj
Port #1032 to `release/6.0` branch.
=> Prevent warning on retries of copying locked files in dotnet-monitor.

src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/DisposableHelper.cs, src/Tools/dotnet-monitor/GenerateApiKeyCommandHandler.cs
The `generatekey` command currently writes out an empty CollectionRules property, e.g.:
```
Settings in Json format:
{
"Authentication": {
"MonitorApiKey": {
"Subject": "...",
"PublicKey": "..."
}
},
"CollectionRules": {}
}
```
This occurs because it the RootOptions object has a non-null CollectionRules property and the JsonSerializer will write out non-null values.
This change fixes this by using ConfigurationJsonWriter instead of JsonSerializer to write out the relevant properties. This writer has been updated to allow not writing out anything for configuration sections that do not have data.
=> Use ConfigurationJsonWriter to write authentication key generation output

eng/Version.Details.xml, eng/Versions.props, eng/build.yml, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestConditions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tools/dotnet-monitor/CollectionRules/ActionOptionsDependencyAnalyzer.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This change adds the netcoreapp3.1 TFM to dotnet-monitor so that the tool can run on .NET Core 3.1 and .NET 5.0 in addition to .NET 6. The tool uses the Microsoft.Extensions.* assemblies from the 6.0.0 release regardless of the TFM. The tests have been updated to run both versions of the tool in a limited fashion. The test matrix is:
| FunctionalTests Version | Dotnet-Monitor Version | Test App Version |
|---|---|---|
| netcoreapp3.1 | netcoreapp3.1 | netcoreapp3.1 |
| net5.0 | netcoreapp3.1 rolled forward to net5.0 | net5.0|
| net6.0 | net6.0 | net6.0 |
=> Add netcoreapp3.1 to dotnet-monitor.

eng/Version.Details.xml, eng/Versions.props, eng/build.yml, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestConditions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tools/dotnet-monitor/CollectionRules/ActionOptionsDependencyAnalyzer.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This cherry-picks the commits from #1080 from `release/6.0` to `main` with one additional change to remove the NoWarn for MSB3026 since it doesn't occur anymore with this changes.
=> [main] Add netcoreapp3.1 to dotnet-monitor

NuGet.config, global.json, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This change builds the product with the .NET 6.0.100 SDK, which allows the framework references of the dotnet-monitor tool to be based on the 6.0.0 packages and frameworks.
=> Use .NET 6 GA SDK

NuGet.config, global.json, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This reverts commit f5832e0791098e628172ff20d0530319518e6fed.
=> Revert "Use .NET 6 GA SDK (#1097)"

src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Corrects an error in the `generatekey` command's `output` parameter help text. 
Old output of `dotnet monitor generatekey --help`:
```
generatekey:
Generate api key and hash for authentication.
Usage:
dotnet-monitor generatekey [options]
Options:
-o, --output <Cmd|Json|PowerShell|Shell|Text>    The format to display the output in. Valid values are Json, Text,
and EnvVar. [default: Json]
-?, -h, --help                                   Show help and usage information
```
New output of `dotnet monitor generatekey --help`:
```
generatekey:
Generate api key and hash for authentication.
Usage:
dotnet-monitor generatekey [options]
Options:
-o, --output <Cmd|Json|PowerShell|Shell|Text>    The format to display the output in. This option is useful for
printing the information in a format to be …
```
=> Fix help text for generatekey's output parameter

src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
- Fixes missing closing braces when executing `dotnet monitor show config` with `Authentication` section present.
- Replaces `_writer.WriteStartObject();` and `_writer.WriteEndObject();` calls with new `JsonSectionHolder` that can be used in a C# `using (...)` scope.
Old output from `dotnet monitor show config` (with `Authentication__MonitorApiKey__Subject` and `Authentication__MonitorApiKey__PublicKey` set via environment variables)
``` json
{
// omitted for clarity
"Authentication": {
"MonitorApiKey": {
"Subject": "2c866b1a-38c5-4454-a686-1e022e38a7f6",
"PublicKey": ":REDACTED:",
"Egress": ":NOT PRESENT:"
}
```
New output:
``` json
{
// omitted for clarity
"Authentication": {
"MonitorApiKey": {
"Subject": "2c866b1a-38c5-4454-a686-1e022e38a7f6",
"PublicKey": ":REDACTED:"
}
},
"Egress": …
```
=> Fix missing closing braces

eng/Publishing.props, eng/release/DiagnosticsReleaseTool/DiagnosticsRepoHelpers.cs, src/Directory.Build.targets, src/Tools/dotnet-monitor/dotnet-monitor.csproj
These changes facilitate the ability to publish the dotnet-monitor nupkg file to the dotnet blob storage account in addition to the default behavior of publishing to each channel's nuget feed.
The files that are created as part of the pack step are:
| File Name | Description | Blob Sub Path |
|---|---|---|
| `dotnet-monitor.<PackageVersion>.nupkg` | The nupkg built by the standard .NET build targets | `diagnostics/monitor/<BuildVersion>/dotnet-monitor.<PackageVersion>.nupkg` |
| `dotnet-monitor.<PackageVersion>.nupkg.blobgroup` | Contains which sub-container the files should be published to in blob storage e.g. `7.0/daily`, used by publishing | N/A |
| `dotnet-monitor.<PackageVersion>.nupkg.buildversionfile` | Contains the name of build version file, used by publishing | N/A |
| …
=> Publish nupkgs to blob storage.

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/DumpService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IDumpService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/OperationTrackerService.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs, src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs, src/Tools/dotnet-monitor/DumpServiceEndpointInfoSourceCallback.cs, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/OperationTrackerServiceEndpointInfoSourceCallback.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
It appears that the event pipe is not responsive during rundown, which causes our pruning mechanism to remove processes (similar to dumps). Possibly related to https://github.com/dotnet/runtime/issues/1892.
- The pruning algorithm should probably do multiple attempts over a period of time to see if the process is really to be removed.
- The real fix should make rundown more configurable. We are defaulting to true in some cases we may not need.
- There may be other affected artifacts (gcdump/logs).
- We should converge the OperationTrackerService and the RequestLimitTracker at some point.
=> Do not attempt to prune processes during tracing

src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs
By default, `Config Show` lists the indices of elements in an array. This change counteracts that behavior by printing `Config Show` using the expected format (no indices).
I've currently only wired up three scenarios to take advantage of this code (CollectionRules, Metrics, and DefaultProcess), because they appeared to be the ones that were affected; however, this could easily be extended with the addition of a parameter to any of the other configuration elements.
The least elegant part of this solution is determining the type of actions/triggers in order to get their available properties; I'll leave a few comments in the review where people can weigh in if they have any thoughts on whether it's fine as-is or if there's a better way.
I tested this against the scenarios in my Collection …
=> Config Show: Array properties without indices

eng/build.yml
Adding this step allows access to private feeds that require credentials. See the following example build demonstrating what it is changing in the NuGet.config file: https://dev.azure.com/dnceng/internal/_build/results?buildId=1489686&view=logs&j=1994a01f-c112-51c5-af4f-f0bea4551182&t=e14f3dce-491b-58da-8687-15b613994bfa
=> Allow access to private feeds for internal builds.

eng/build.yml
Internal builds are available on a different feed than the standard feeds that the dotnet-install script knows. Pass the additional feed location and SAS token to access the feed to install the frameworks.
=> Pass additional installation feed for internal builds.

eng/build.yml
Port of #1163 from `release/6.0` to `main` branch.
(cherry picked from commit f1bd67df92b707d787dd54fdd8cdfdd2f0fb493a)
=> [main] Allow access to private feeds for internal builds.

eng/build.yml
Port of #1169 from `release/6.0` branch to `main` branch.
(cherry picked from commit 8dda983a3ecde881d6464b969dd049e1831464bf)
=> [main] Pass additional installation feed for internal builds.

eng/PrepareRelease.yml
* Adds `internal/release/` to publish branches so the yaml pipeline will correctly publish bits during the build.
(cherry picked from commit 53c9fa2a0a75827aeda7542be69ca1dd30478e15)
=> [release/6.0] Adds internal/release/ to publish branches

eng/Version.Details.xml, eng/Versions.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This change removes the explicit PackageReference dependencies on libraries that are provided by the 6.0 shared frameworks. This gives dotnet-monitor the advantage of reducing its package size (from 6.56 MB to 5.97 MB, about 0.6 MB savings) and (more importantly) removes some of the surface area that _may_ require servicing in the net6.0 TFM. The latter can be advantageous for the Docker image since it only uses the net6.0 TFM and thus reduces the necessity to provide a servicing package prior to a servicing release. This change should have no functional impact.
=> Remove explicit dependencies provided by net6.0 shared frameworks

eng/Version.Details.xml
The KeyPerFile assembly is built from the aspnetcore repo, not from the runtime repo.
=> Fix Microsoft.Extensions.Configuration.KeyPerFile version source

src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
It was noticed that DiagnosticPort's config wasn't being respected in `appsettings.json`; this is because the default value set in `ConfigureEndpointInfoSource` was being loaded after `appsettings.json`. This change fixes the ordering so that `appsettings.json` is automatically added as a source _after_ the defaults are set in the call to `ConfigureHostConfiguration`.
Closes #1102
=> Fix ordering of configuration sources

src/Microsoft.Diagnostics.Monitoring.WebApi/DumpService.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs
If some folder segment in the dumps directory path doesn't exist, the `/dump` endpoint will fail, returning an HTTP 400 with an error message of `WriteDumpAsync failed - HRESULT: 0x00000000`. The logs in `dotnet monitor` show this error too but there's no indication what the issue is.
This is fixed by ensuring that the directory exists before issuing the dump command.
closes #1216
=> Ensure dumps folder exist before issuing dump command.

src/Tools/dotnet-monitor/dotnet-monitor.csproj
Simplify dotnet-monitor project by using Web SDK.
Port of #1190 from `release/6.0` branch to `main` branch.
=> [main] Remove dependencies provided by shared framework.

eng/Publishing.props
With https://github.com/dotnet/arcade/issues/6517 fixed, nupkg files can now be published to blob storage once again. This will allow providing dotnet-monitor to the dotnet-docker repo via blob storage rather than shipping through a separate NuGet feed.
See https://dev.azure.com/dnceng/internal/_build/results?buildId=1521464&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a as an example of the nupkg being promoted to blob storage in addition to the normal target NuGet feed.
=> Enable publishing of nupkg to blob storage.

eng/Publishing.props
(cherry picked from commit 5cb0a7b0fef906263d315cb32ccc8498e09680d9)
=> [release/6.0] Enable publishing of nupkg to blob storage.

eng/build.yml, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DistroInformation.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionTestsHelper.cs, src/Tools/dotnet-monitor/RuntimeInfo.cs
The Alpine image currently used is very old and no longer supported. It also doesn't seem to work with .NET 7 runtimes. Update the image to 3.14 since that the earliest Alpine image in support as provided by dotnet-docker (which also happens to be the latest version until 3.15 images are shipped in the near future).
Note: May need to adjust dump tests on Alpine to only capture full dumps (see https://github.com/dotnet/dotnet-monitor/issues/674#issuecomment-920189864)
=> Update Alpine image to latest

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
This change installs the .NET 7 versions of runtime and aspnet frameworks. All other packages have been kept back at currently shipping versions. This change does not impact the functionality of the tool nor change the target framework support matrix at this time.
=> Update dependency flowed runtimes to 7.0.0 versions.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.CollectionRule.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs
Let's convert the huge list of constants in [LoggingEventIds.cs](https://github.com/dotnet/dotnet-monitor/blob/main/src/Tools/dotnet-monitor/LoggingEventIds.cs) to an enum to these 2 advantages:
- Compiler will enforce that we don't accidently introduce duplicate IDs, this is very common because we always append to this list and just use the next number
- Avoid having an extra point where we define the ID and a string representing the event. We can just ask the runtime for the enum name and so the code will always match the event names produced at runtime.
The motivation for this is to avoid having to worry about and verify that we don't introduce conflicting IDs in 2 PRs that add an event to this list.
=> Convert LoggingEventIds to enum

documentation/authentication.md, documentation/configuration.md, documentation/setup.md
Remove the fixed versions of the releases to encourage using the latest versions. Customers can look up exact versions from the sources cited in the existing documentation on the docker.md page as well as in the new section at the bottom of the setup.md page.
=> Update setup and documentation pages to encourage using latest versions.

eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.Options/Microsoft.Diagnostics.Monitoring.Options.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/OutputStreamResult.cs
With 2.1 out of support, there's little reason to keep the netstandard build outputs. Removing these simplifies the necessary assembly references in the Options and WebApi projects.
closes #1270
=> Remove netstandard2.0 outputs and PackageReferences.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestOutputLogger.cs
These changes take the log entries and write them to ITestOutputHelper so that the entries are in the test output. This will help diagnose test failures around components that log their state.
=> Write logger entries to ITestOutputHelper.

global.json
This will allow the repo to build net7.0 TFM assemblies in future changes.
close #1268
=> Use latest .NET 7.0 SDK

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/LoggingRunnerAdapter.cs
Fix logging message for exit code in `AppRunner`. Current code causes null to always be printed.
=> Fix logging message for exit code in AppRunner

.github/workflows/backport.yml, eng/actions/backport/action.yml, eng/actions/backport/index.js
This GitHub action allows a repository collaborator to backport a change from a completed PR to another branch. This is done by invoking `/backport to <branch_name>`, which will open a PR in that branch and a link to that PR to the complete PR.
These files were largely copied from dotnet/runtime repo.
closes #1297
=> Add backport action.

eng/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Remove netcoreapp3.1 TFM from dotnet monitor unit tests.
Run net6.0 dotnet monitor for all test application TFMs.
Update Microsoft.AspNetCore.Authentication.* to 6.0.0
There's more work to remove netcoreapp3.1 from the Options and WebApi assemblies, but the FunctionalTests project depends on a bunch of types from WebApi and the FunctionalTests project builds for netcoreapp3.1, net5.0, and net6.0. I'll make a subsequent change to remove the netcoreapp3.1 TFM from those projects when I have a reasonable solution.
closes #1267
=> Remove netcoreapp3.1 TFM from dotnet monitor.

eng/Versions.props, src/Microsoft.Diagnostics.Monitoring.Options/Microsoft.Diagnostics.Monitoring.Options.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/OutputStreamResult.cs
Backport of #1272 to release/6.0
/cc @jander-msft
=> [release/6.0] Remove netstandard2.0 outputs and PackageReferences.

eng/Versions.props, global.json, src/Microsoft.Diagnostics.Monitoring.Options/Microsoft.Diagnostics.Monitoring.Options.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
These changes add the net7.0 TFM to all projects, including dotnet-monitor. The functional tests will use the net6.0 variant for testing netcoreapp3.1, net5.0, and net6.0 apps whereas the net7.0 variant will be used with the net7.0 apps (future changes can be made to test across targets).
I've centralized the TFM specifications for the projects so that it'll be easier to add and remove TFMs in the future.
Finally, the SDK is updated to bring in runtimes that contain fixes for some configuration bugs that were introduced in prior versions of the .NET 7 SDK.
closes #1269
=> Add net7.0 TFM to dotnet-monitor.

eng/release/DiagnosticsReleaseTool/Core/FileMetadata.cs, eng/release/DiagnosticsReleaseTool/Core/Release.cs
Ports the following PRs (made to `release/6.x`) into main:
- #1350
- #1351
- #1358
- #1359
This fixes a bug in the release tool that caused it to error when duplicate files exist in the DARC drop.
@hoyosjs let me know if we should also port this over to the Diagnositcs repo. It should be safe for you but it does change one of the core assumptions (that there won't be duplicate files in the DARC drop).
=> Port DiagnosticsReleaseTool fix to main

eng/Versions.props
This change will have the build produce packages that are exactly the version as specified by the `VersionPrefix` property, which is set to `6.1.0` at this time.
=> Produce stable versions for 6.1

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs
This change pushes the command line url parameters to the lowest possible precedence so that DOTNET_* environment variables (e.g. DOTNET_Urls) can override them.
cc @wiktork
=> Push command line url parameters to lowest precedence.

eng/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Backport of #1382 to release/6.0
This also requires taking a dependency on the 6.0.0 version of Microsoft.Extensions.Hosting in which the `IHostBuilder ConfigureDefaults(this IHostBuilder builder, params string[] args)` method was introduced. Without this dependency, the code would need to be rewritten in such as way that the in-memory collections are inserted _before_ the sources that were already added from prior invocations of `IHostBuilder IHostBuilder.ConfigureHostConfiguration(Action<IConfigurationBuilder> configureDelegate)`.
=> [release/6.0] Push command line url parameters to lowest precedence.

eng/PrepareRelease.yml
Maestro vars are no longer isoutput=true, and should not be referenced with the task name.
=> Remove task reference from BuildId parameter

documentation/troubleshooting.md
Adds the first entry in our troubleshooting guide to address the issue found in #1326, which ended up being high log volume.
Closes #1326
=> Add first entry in troubleshooting guide

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorGenerateKeyRunner.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/OutputFormat.cs
Adds new `OutputFormat` called `MachineJson` which will cause `generatekey` to write out only a single json object. This is designed to be machine consumable and parsable.
`dotnet monitor generatekey --output MachineJson`
```json
{
"Authentication": {
"MonitorApiKey": {
"Subject": "68b75a98-c440-4b87-8abc-42c81a06fdce",
"PublicKey": "eyJBZGRpdGlvbmFsRGF0YSI6e30sIkNydiI6IlAtMzg0IiwiS2V5T3BzIjpbXSwiS3R5IjoiRUMiLCJYIjoiWG80NTFxdm9JRC1pS0ltLVRfZ2pTZVZteEhabC1RV1VpbnczWG1fUS1CTEM3c0ptSTVSTllSYzc2RlVDeldSZyIsIlg1YyI6W10sIlkiOiJoQWRPWENiczFhVHl6R1JTRVFET1FYUUsyUElrVGs1aVBSZWQ4YTBYbUNOQ2xmdTgwTmg3bGtSRFB0TllvZE5fIiwiS2V5U2l6ZSI6Mzg0LCJIYXNQcml2YXRlS2V5IjpmYWxzZSwiQ3J5cHRvUHJvdmlkZXJGYWN0b3J5Ijp7IkNyeXB0b1Byb3ZpZGVyQ2FjaGUiOnt9LCJDYWNoZVNpZ25hdHVyZVByb3ZpZGVycyI6dHJ1ZSwiU2lnbmF0dXJlUHJvdmlkZXJPYmpl …
```
=> Add MachineJson output format for key generation

eng/release/Scripts/GetBarId.ps1, eng/release/Scripts/GetReleaseVersion.ps1, eng/release/Scripts/SetTaskVariable.ps1
This change adds the Get BAR ID and Get Release Version inline scripts from the release definition into the repo with several improvements:
- Caller can decide if it wants verbose information (e.g. release data and versions) by using the -Verbose flag.
- Caller can decide whether to push final output value into a task variable.
- Use standard error stream for reporting errors and failing the script immediately.
- Allows calling script via file path so that script parameters are printed into task output.
- Allows reuse among multiple build tasks.
cc @kelltrick, @hoyosjs
=> Add common release scripts

eng/release/DiagnosticsReleaseTool/Common/BlobLayoutWorker.cs, eng/release/DiagnosticsReleaseTool/Common/ChecksumLayoutWorker.cs, eng/release/DiagnosticsReleaseTool/Common/NugetLayoutWorker.cs, eng/release/DiagnosticsReleaseTool/Common/SkipPublisher.cs, eng/release/DiagnosticsReleaseTool/Core/FileMetadata.cs, eng/release/DiagnosticsReleaseTool/Core/Release.cs, eng/release/DiagnosticsReleaseTool/DarcHelpers.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseRunner.cs, eng/release/DiagnosticsReleaseTool/DiagnosticsRepoHelpers.cs
- Change NugetLayoutWorker to only consider files under the packages directory
- Add checksum file to ChecksumAssets in publish manifest
- Add unprocessed files to BlobAssets in publish manifest
- Add --dry-run option to run tool without publishing
The changes will make it easier to publish blob assets to the desired target storage account, checksums to a different storage account, and more easily have NuGet publishing only consider NuGet packages (fixes issue where the nupkg was listed twice under NuGetAssets).
Example dry run publish manifest:
```json
{
"ReleaseVersion": "20220127.7",
"RepoUrl": "https://github.com/dotnet/dotnet-monitor",
"Branch": "refs/heads/release/6.0",
"Commit": "9774a8ccc1a015d47960ed76de1bc6a5a1227f2c",
"DateProduced": "2022-01-28T05:44:47+00:00",
"BuildNumber": …
```
=> Release tool updates

eng/release.yml, eng/release/Scripts/GetBuildVersion.ps1, eng/release/Scripts/InstallAzCopy.ps1, eng/release/Scripts/PublishToBlobAccounts.ps1
These changes add scripts and a pipeline for publishing the `dotnet monitor` files from the staging location to the expected production location. They have options for performing a dry-run (exercises all of the publish steps but not actually push the files to the destination accounts) and for testing with test accounts (exercises all of the publish steps but publishes to test accounts rather than `dotnetcli` and `dotnetclichecksums`). The test and dry-run modes are the default to prevent accidental promotion. When not running a test run, the promotion will use an environment that requires an explicit approval, whereas the test run uses an environment that has automatic approval.
Example runs:
- [6.1.0 candidate test (dry-run)](https://dev.azure.com/dnceng/internal/_build/results?buildId=16 …
=> Scripts and pipeline for release to blob storage

documentation/configuration.md, src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
With the addition of the `--show-sources` flag, users can now view the configuration sources that `dotnet monitor` is using to generate the configuration for debugging purposes. NOTE: this does not show which parts of the configuration are associated with each provider - if we'd rather invest in trying to do that, we can close this PR and I can work on a different solution.
Closes #277
=> Config Show - List configuration sources

src/Tools/dotnet-monitor/Auth/JwtBearerPostConfigure.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfiguration.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfigurationObserver.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyPostConfigure.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Removes unnecessary api config warning messages when no Api key is configured.
- Adds a bool to the internal `MonitorApiKeyConfiguration` object that tracks if any value was provided for the 2 settings. If null was passed, the log messages are omitted.
Resolves #1509
=> Reduce log messages for APIKey changes when no API key is configured

src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs
In the release/6.* branches, when attempting to update the SDK version to beyond 6.0.100, the OpenApiGen unit test fails with a message such as `The specified framework 'Microsoft.NETCore.App', version '6.0.0', apply_patches=0, version_compatibility_range=exact cannot roll-forward to the previously referenced version '6.0.1'.`
What's happening is that the test runner incorrectly assumes that the OpenApiGen tool is a .NET application whereas it is really an ASP.NET application. We've made changes to not attempt to roll forward ASP.NET applications starting with .NET 6 since the `--fx-version` parameter seems to break the ability to run them due to the *.runtimeconfig.json file having multiple frameworks.
The fix is to specify that the OpenApiGen tool is an ASP.NET framework-based tool, …
=> Set OpenApiGen runner to use ASP.NET framework

documentation/authentication.md, documentation/configuration.md, documentation/docker.md, documentation/releases.md
Update the release information with the new releases and expected end of support time frames. Made similar updates to the docker information. Also changed the docker image tags to use major only versions to promote automatic acquisition of minor releases.
=> Update releases and docker documentation

documentation/configuration.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.Options/ProcessFilterOptions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/DiagProcessFilter.cs
Allows users to use a shorthand means of specifying the process filter instead of listing the key and value separately. This is not a breaking change and should not interfere with the existing functionality. Note: In the testing, I also noticed that the `Key` field could be omitted for a value, and it defaults to checking for a `ProcessId`; since altering this behavior would be a breaking change, it's now listed explicitly in documentation.
Closes #636
=> Simplified Process Filter Schema

src/Tests/TestProfiler/CMakeLists.txt
This change bifurcates the symbols from the native libraries so that the libraries are smaller. The symbol files are *.dbg on Linux and *.dwarf on MacOS. These files will be uploaded to the pipeline artifacts to be for debugging and symbol resolution later.
=> Splits symbols from native libraries

dotnet-monitor.yml, eng/build.yml, eng/cipacksignpublish.cmd
These changes allow individual build jobs to contribute their native assemblies to a single pipeline artifact so that all platform variations of each native assembly can be incorporated into the same package. Note that the dotnet-monitor package does not pack any native assemblies at this time, but these changes allow that to happen more easily in a subsequent change.
Summary of Changes:
- Remove pack, sign, and publish from the individual build jobs
- Build jobs publish only the binaries the contribute to the NuGet packages
- Windows x64 Release contributes managed and native assemblies
- All other release builds contribute native assemblies only
- Add single job for pack, sign, and publish
- Add pipeline parameter to allow skipping test runs; by default, tests are run
=> Pack and sign from combined build artifacts

dotnet-monitor.yml, eng/build.yml
Add support for building native libraries for arm64 Windows, Linux, Linux Musl, and MacOS without testing them. Package projects have not been updated to include these binaries because the package projects do not include native libraries yet.
~~Internal build (skipped tests): https://dev.azure.com/dnceng/internal/_build/results?buildId=1660023&view=results~~
Internal build (skipped tests): https://dev.azure.com/dnceng/internal/_build/results?buildId=1663048&view=results
=> ARM64 cross build support

documentation/releaseNotes/releaseNotes.md, documentation/releaseNotes/releaseNotes.template.md, dotnet-monitor.yml, eng/PrepareRelease.yml, eng/Versions.props, eng/build.yml
Update build pools to servicing
Reset release notes
> **NOTE:** this is targeting a new release branch (`release/6.1`) which was forked from `release/6.x`
=> Update version to 6.1.1

documentation/releaseNotes/releaseNotes.md, src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/ExperienceSurvey.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Example outputs:
```
> dotnet dotnet-monitor.dll collect
10:17:12 info: Microsoft.Diagnostics.Tools.Monitor.Startup[60]
Tell us about your experience with dotnet monitor: https://aka.ms/dotnet-monitor-survey
10:17:12 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
MonitorApiKey settings are invalid: The Subject field is required.
10:17:12 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
MonitorApiKey settings are invalid: The PublicKey field is required.
10:17:12 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
MonitorApiKey settings are invalid: The configuration parameter PublicKey must be base64Url encoded, the value '' could not be parsed as a base64Url-encoded string.
10:17:13 warn: …
```
=> Add experience survey link

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs
Logs functional tests are frequently failing on Windows CI jobs. Conditionally skip in builds for now until it can be resolved.
=> Skips logs functional tests on Windows CI machines

src/Tools/dotnet-monitor/dotnet-monitor.csproj
The profiler is not ready to be used in the product; exclude it until a scenario is enabled. Non-official builds will still include the profiler files for easier testing.
=> Exclude profiler from nupkg until productized

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs
Add retry logic to the logs and dumps tests in an effort to allow builds to complete with a higher success rate.
=> Retry logs and dumps tests on failure

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestOutputLogger.cs
Some test failures can be diagnosed using the logging statements provided by the tested components. However, those statements are just logging the message without the exception information (if there is any). This update will log exception information if it is available.
=> Write logger exceptions to test output

eng/Version.Details.xml
Apply CoherentParentDependency to runtime instead of aspnetcore. Dependency update PR showing a coherency update: https://github.com/dotnet/dotnet-monitor/pull/1662
=> Fix coherency dependencies

src/Microsoft.Diagnostics.Monitoring.WebApi/ActionContextExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectDumpAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectGCDumpAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLogsAction.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs
The collection rule actions do not throw exceptions when they fail to collect their artifacts. The call to `IEgressOperation.ExecuteAsync` will return a failed `ExecutionResult` instead of throwing an exception when the operation fails.
To fix this, I've added an `Exception` property to the `ExecutionResult` class which is populated when creating a failure result and updated the actions to throw a `CollectionRuleActoinException` that wraps the exception from the `ExecutionResult`.
=> Have collect actions throw exceptions on failure

documentation/docker.md
This excludes the CBL-Mariner links as they are not documented.
=> Update Docker docs with new Dockerfile links

src/Tools/dotnet-monitor/Auth/JwtBearerPostConfigure.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfiguration.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfigurationObserver.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyPostConfigure.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport of https://github.com/dotnet/dotnet-monitor/pull/1510 to release/6.x
/cc @jander-msft @kelltrick
=> [release/6.x] Reduce log messages for APIKey changes when no API key is configured

src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/CollectionRuleOptionsExtensions.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Triggers/AspNetResponseStatusOptions.cs
Backport of https://github.com/dotnet/dotnet-monitor/pull/1573 to release/6.x
/cc @jander-msft, @kkeirstead
=> [release/6.x] Add Unit Testing for AspNet* Triggers

dotnet-monitor.yml, eng/build.ps1, eng/build.sh, eng/build.yml, src/Directory.Build.props, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMonikerTraitAttribute.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMonikerTraitDiscoverer.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/EgressTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/MetricsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/RootTests.cs
Backport of https://github.com/dotnet/dotnet-monitor/pull/1613 to release/6.x
/cc @jander-msft
=> [release/6.x] Skip netcoreapp3.1 and net5.0 tests in PR and CI builds

eng/Version.Details.xml
Same change in #1660 and #1663 but targeting the release/6.x branch
The aspnetcore and runtime versions are already coherent, so only the attributes need to be applied to the version entries.
=> [release/6.x] Make aspnetcore a coherent parent of runtime

documentation/releaseNotes/releaseNotes.md
I removed the experience link item since that will ship in 6.1.1 before 6.2 ships.
=> [release/6.x] Update release notes with product changes

dotnet-monitor.yml, eng/build.yml, eng/cipacksignpublish.cmd
These changes allow the packing phase, which occurs on a different job than the platform build jobs, to not rebuild the product. This required capturing the `obj` folder of the same build job that provided the managed assemblies, namely the Windows x64 Release job, in the `Build_Release` artifact such that it can be reused in the packing job. This allows the assemblies and pdbs that are packged into the nupkg file to be exactly the same as those that were produced by the build job.
[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=1702307&view=logs&j=8302af6e-291f-54bf-6d61-b832e4017e5a&t=31c4598f-342a-52ea-54df-47052f2aafdf) shows that the packing phase does not rebuild any assemblies.
=> Prevent rebuild while packing in official builds

src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/ClassFactory.h, src/MonitorProfiler/Environment/Environment.h, src/MonitorProfiler/Environment/EnvironmentHelper.cpp, src/MonitorProfiler/Environment/EnvironmentHelper.h, src/MonitorProfiler/Environment/ProfilerEnvironment.cpp, src/MonitorProfiler/Environment/ProfilerEnvironment.h, src/MonitorProfiler/Logging/AggregateLogger.cpp, src/MonitorProfiler/Logging/AggregateLogger.h, src/MonitorProfiler/Logging/DebugLogger.cpp, src/MonitorProfiler/Logging/DebugLogger.h, src/MonitorProfiler/Logging/LogLevelHelper.h, src/MonitorProfiler/Logging/Logger.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/ProfilerBase.cpp, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs, src/inc/com.h, src/inc/tostream.h, src/inc/tstring.h
These changes add a logging infrastructure that has a similar shape as [ILogger](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger?view=dotnet-plat-ext-6.0) in managed code. There currently only two logger implementations: a debug output logger (logs to the output window when debugging on Windows) and an aggregate logger (dispatches log calls to a list of loggers). Choosing a similar abstraction with the same log levels allows easier integration with managed code if we decide to serialize log entries back to the dotnet-monitor process. Finally, common macros and implementation specific macros were added to aid in logging HRESULT failures and log entries in general.
These changes also refactor the notion of getting and setting environment variables …
=> Profiler logging infrastructure

documentation/release-process.md, eng/Versions.props, src/Directory.Build.targets
Remove the unused `prerelease` blob group to avoid release process confusion.
=> Remove prerelease blob group

documentation/release-process.md
Make sure the instructions state that (1) a successful release build should be made and (2) dotnet-docker update pipeline should be adjusted BEFORE bumping the version in the main branch.
=> Update release process docs

src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs, src/Tools/dotnet-monitor/DiagnosticPortValidateOptions.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Currently, if a user is running in `Connect` mode and has collection rules configured, we don't give a warning indicating the issue. Now, a Warning logger message gives a brief description of what to do to resolve the issue. The check also occurs in two separate places since changes to the diagnostic port aren't respected once dotnet monitor is running - the first check will occur during validation for the diagnostic port, and then a check will occur every time the collection rule configuration changes. This will **not** fail validation, as that would be a breaking change.
Closes #1774
=> Add warning when collection rules are configured but not running in Listen mode

src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfigurationObserver.cs
Introduces a no-auth check to prevent the warning from appearing when `--no-auth` is present. ~~**NOTE:** I kept this in-line with the pre-regression behavior where "MonitorApiKey settings have changed. The new settings have passed validation." is printed when the no-auth flag is present. If we don't want this, I can modify the check to only show that message when the user omits the flag.~~
Closes #1624
Closes #1625
=> Do not warn about unconfigured auth when --no-auth is used

documentation/release-process.md, eng/Versions.props, src/Directory.Build.targets
Backport of https://github.com/dotnet/dotnet-monitor/pull/1813 to release/6.1
/cc @jander-msft
=> [release/6.1] Remove prerelease blob group

eng/Publishing.props
The metadata on the PackageFile items was accidentally dropped in #1834, which causes all of the files uploaded to the dotnetbuilds storage account to be marked as non-shipping. This fix includes the metadata from the PackageFile items in the PackageToPublish items to allow shipping vs non-shipping to be tracked correctly.
=> Fix shipping metadata for blob files

documentation/kubernetes.md
As of the 6.0.2 release from February, the dumps folder does not need a separate, already created folder. It can be combined with the `/diag` directory so that only one shared volume is necessary for all scenarios. This should work since the runtime should not be creating a `dumps` file in the `/diag` directory and dotnet monitor is explicitly told to create a `port.sock` file in the `/diag` directory.
=> Consolidate dumps folder into diag folder in k8s sample

NuGet.config, documentation/openapi.json, eng/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AsyncWaitScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/EnvironmentVariablesScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/LoggerScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/SpinWaitScenario.cs, src/Tools/dotnet-monitor/Program.cs
As part of the Security Review, we need to keep our OSS up-to-date. This is an initial pass - @jander-msft will be taking a look and making recommendations for what versions we should use. Some versions were updated (but not to the latest version), since the latest version (or its dependencies) hadn't been picked up yet. `System CommandLine` also had breaking changes, which led to changes in how we set Arguments.
=> Update OSS Versions

src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/Communication/CommandServer.cpp, src/MonitorProfiler/Communication/CommandServer.h, src/MonitorProfiler/Communication/IpcCommClient.cpp, src/MonitorProfiler/Communication/IpcCommClient.h, src/MonitorProfiler/Communication/IpcCommServer.cpp, src/MonitorProfiler/Communication/IpcCommServer.h, src/MonitorProfiler/Communication/Messages.h, src/MonitorProfiler/Communication/SocketWrapper.h, src/MonitorProfiler/Environment/EnvironmentHelper.cpp, src/MonitorProfiler/Environment/EnvironmentHelper.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/Utilities/BlockingQueue.h
Backport from #1790
Add a communication mechanism between the profiler and dotnet-monitor.
- Currently using Unix Domain Socket on both Windows and Linux
- Current model is to receive small control messages from dotnet-monitor.
- Requests are handled serially, long/con-current sessions are not really supported with the current model.
=> [Backport] Add command ipc to profiler 

src/MonitorProfiler/Environment/EnvironmentHelper.h, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs, src/Tools/dotnet-monitor/CollectionRules/ActionOptionsDependencyAnalyzer.cs, src/Tools/dotnet-monitor/ConfigurationTokenParser.cs
- Rename InstanceId to RuntimeId
- Fix issue with values that contain both dependencies and RuntimeId. We were replacing values in the wrong order.
- Add unit tests for above scenario.
- Refactor token replacement code to its own class so that it can be reused by egress in the future.
=> Fix RuntimeId token

src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/Logging/Logger.h, src/MonitorProfiler/MainProfiler/ExceptionTracker.cpp, src/MonitorProfiler/MainProfiler/ExceptionTracker.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/MainProfiler/ThreadData.cpp, src/MonitorProfiler/MainProfiler/ThreadData.h, src/MonitorProfiler/MainProfiler/ThreadDataManager.cpp, src/MonitorProfiler/MainProfiler/ThreadDataManager.h
These changes add the ability to detect unhandled exceptions in the most commons cases. The algorithm is described (along with its known caveats) and coded into the [ExceptionTracker class](https://github.com/dotnet/dotnet-monitor/compare/release/6.x...jander-msft:dev/jander/exceptions?expand=1#diff-5eb9c3b5e67efbf830637957e3fa121a43d4ebdb4cde8b9d23ad566a7cccf518). No action is taken in these changes when an unhandled exception does occur; these changes are purely about detection.
=> Unhandled exception detection

documentation/releases.md
Add the 6.0 unsupported version information into a separate table. This largely mirrors the format of the [.NET Core support policy page](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
=> Add unsupported versions entry

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx, src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressProvider.cs, src/Tools/dotnet-monitor/FilteredEndpointInfoSource.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Part of the security review is to address "swallow everything" exceptions; this is an initial pass at adding logging to some of the places where we `catch` as well as expanding to specify which exceptions we want to catch. Things to consider:
- Where we should/shouldn't log (and what level makes the most sense)
- What exceptions we need to handle that were previously being encompassed by `Exception`
- Places where the exception handling should not be altered (and the reasoning)
If there are other places where we should make changes that aren't included here, please let me know and I'll add them in.
=> Address "Swallow Everything" Exceptions

global.json
Builds are failing due to https://github.com/dotnet/aspnetcore/issues/42200; I have tried the latest SDK and the issue seems to persist. Revert to the Preview 4 SDK until the issue is fixed. Internal validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1852879&view=results
=> Revert SDK to Preview 4

documentation/configuration.md, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/EgressFull.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/EgressRedacted.json, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/Commands/ConfigShowCommandHandler.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/HostBuilderResults.cs, src/Tools/dotnet-monitor/HostBuilderSettings.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Backport of #1990 to release/6.x
=> Specify Json Configuration File Source Via Command Line

eng/Publishing.props, src/Directory.Build.targets
The naming of the *.buildverion and *.version files that are uploaded to blob storage was regressed in #1834. The prior naming convention would include the build version in the file name regardless of final versions were used, for example:
```
dotnet-monitor.6.2.1-servicing.22330.6.nupkg.buildversion
dotnet-monitor.6.2.1-servicing.22330.6.nupkg.version
```
whereas with the changes in #1834 only used the package version in the file names:
```
dotnet-monitor.6.2.1.nupkg.buildversion
dotnet-monitor.6.2.1.nupkg.version
```
The problem is that these are uploaded to a container and prefix named `diagnostics/monitor6.2/release`. If more than one build is produced from the same final version, then the uploaded files will collide with what's already on blob storage from the first build.
This …
=> Fix version file names that are published to blob storage

src/Tests/Directory.Build.props
In the event that the SDK starts implicitly requiring a unrelease version of .NET 6, the version of the runtime should be pinned to what is installed so that the apps will run on what's available at build time.
=> Pin net6.0 version for test apps

src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
An arcade update brough in .NET 7 SDK Preview 5, which contains the following issue: https://github.com/dotnet/aspnetcore/issues/42200
The workaround is to disable the use of static web assets. These typically are only available when running in a development hosting environment, which is not the case for the typical dotnet-monitor deployment (this would be an environment where the `Environment` environment variable or configuration key is set to `Development`). I am also not aware of any feature of dotnet-monitor that makes use of static web assets.
=> Disable use of static web assets

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptionsExtensions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Possible fix for https://github.com/dotnet/dotnet-monitor/issues/2118 and https://github.com/dotnet/dotnet-monitor/issues/1827
=> Delete endpoint on startup

documentation/api/operations-get.md, documentation/api/operations-list.md, documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/EgressOperationStatus.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressRequest.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperation.cs
This is for #2122. It updates the /operations and /operations/operationId api to show the RuntimeId, ProcessId, and ProcessName as a sub-object shown in the results.
Main question I wanted to bring up for discussion in this PR: 
Most EgressOperations created can't really take in an `IProcessInfo` object since they pull an endpoint directly, which doesn't have the ProcessName stored. There are a few ways I'm thinking we can use to fix this - 
1. Leave as-is and let most operations not have a processName that we can use.
2. If the processName isn't that relevant we can remove it from the API update so we only show RuntimeId and ProcessId.
3. We can query for the processInfo object using the found RuntimeId and get the name from that, similar to what's done [in …
=> Operations Api shows RuntimeId, ProcessId, and ProcessName

eng/Versions.props, eng/build.yml, global.json, src/Microsoft.Diagnostics.Monitoring.Options/Microsoft.Diagnostics.Monitoring.Options.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionTestsHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
These changes:
- remove .NET 5 from the testing matrix (just as #2086 did for `main`, with an additional change to not install .NET 5)
- consolidate the TFM specification in the cross-targeting projects (just as #1352 did for `main`, but only an applicable subset)
The result is that .NET 5 is no longer tested (it is out of support), build times should be incrementally faster, and full test runs should be much faster.
=> Remove .NET 5 testing and consolidate TFMs

global.json
The .NET 5 runtimes are not used; remove the steps to install them.
=> Remove .NET 5 installation

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRules/Actions/CallbackAction.cs
Some of the collection rule unit tests are not advancing the simulated clock correctly, which is causing the DelayedCallbackAction to not complete since it spin waits. I've added cancellation support to hopefully alleviate long test hangs until the simulated clock issue is resolved.
=> Add cancellation support to DelayedCallbackAction

.github/CODEOWNERS
Backport of #2231 to release/6.x
=> [release/6.x] Assign dotnet-monitor reviewers by default

dotnet-monitor-codeql.yml, dotnet-monitor.yml, eng/PrepareRelease.yml, eng/build.yml, eng/release.yml
Per guidance from .NET Core engineering, update the Windows build images to newer images.
=> Update to newer Windows build machines

src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Warnings will be logged in the event of file not found or unauthorized access for JSON configuration files.
closes #2020
=> Check Read Permissions For JSON Configuration Sources

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs
This test fails very frequently often blocking builds from succeeding. Disable the test for now until cause to fixed.
=> Skip CollectionRuleDescriptionPipeline_ExecutingAction test

eng/Versions.props, global.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/ScenarioHelpers.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This change includes splitting the versions of the authentication libraries along the .NET versions. This is necessary because there are changes in .NET 7 Preview 7 that prevent usage of the .NET 6 version of the libraries from being used in .NET 7. Because the .NET 6 libraries cannot be used in .NET 7 any longer, I've also removed the ability to have dotnet-monitor roll forward to newer major versions of .NET.
Another issue is that the Microsoft.Extensions.Logging.Console library is not writing out all of the logged entries in a timely manner. The tests use this library for controlling coordination between the unit tests and the unit test app. I've replaced the standard JSON console logger with a custom implementation that effectively does the same logging without using a message queue. …
=> Update runtimes and SDK to latest

src/Directory.Build.targets
Recent upgrade of the Microsoft.Diagnostics.Tracing.TraceEvent library that is transitively included by direct dependencies of dotnet-monitor include Windows-only native libraries. These libraries in total are about ~10 MBs; when packaged into dotnet-monitor, they take up ~20 MBs of space due to multitargeting.
This change removes those native libraries as they are not used by dotnet-monitor in order to reduce the package size.
=> Remove unused native TraceEvent libraries from consideration

documentation/api/operations-list.md, documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/Utilities.cs
Part 2 of #2122; allows users to specify a PID/UID/Name to only see the operations list for that specific process.
=> Operations API - Specify PID/UID/Name to see operations for specific process

.github/fabricbot.json
I haven't been able to test this, but this PR is intended to do the following:
- If a PR hasn't had any activity in 4 weeks (28 days), we add a 'stale' label to it, and leave a comment saying that the PR will be closed if there is no activity
- If a PR hasn't had any activity in 10 weeks total (4 weeks + 6 weeks after the comment), we close the PR
- If a PR has the stale label and has activity, we remove the stale label. This piece I'm not confident in, because I'm not sure if this will immediately remove the stale label as soon as it's added (because it'll be seen as new activity), but I believe I've mitigated that by saying the activity sender cannot be the fabric bot.
Follow-up to #2344
=> Use FabricBot to add stale label and close PRs that are stale

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDefaultsTests.cs
xUnit analyzer will fail the build on these lines because the expected value and actual value are swapped. Flip them around to correctly specify the expected and actual values.
=> Reorder assertion arguments

dotnet-monitor.yml, eng/PrepareRelease.yml, eng/build.yml
Manual backport of #2345 to `release/6.1`
=> [release/6.1] Update to newer Windows build images

eng/PrepareRelease.yml, eng/build.yml, eng/common/templates/job/source-build.yml, eng/common/templates/job/source-index-stage1.yml
This change is required to continue building PRs in the dotnet public repo.  The agents and images used in the new project / organization are identical and build regressions are not expected.  Updating files under eng/common is intentional to move as much as possible over to viable build agents (normally this is not done).
For questions / concerns, please stop by the .NET Core Engineering Services [First Responders Teams Channel](https://teams.microsoft.com/l/channel/19%3aafba3d1545dd45d7b79f34c1821f6055%40thread.skype/First%2520Responders?groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).
=> Update public pool names

eng/Versions.props
Now that the .NET 7 SDK is stable enough, this change enables building the `net7.0` TFM when building in Visual Studio. I've left in the commented-out condition that would allow the conditional inclusion of the latest TFM for when this branch forks for .NET 8.
Note that this will require installing the latest .NET 7 SDK on dev machines and requires using a preview version of Visual Studio to build.
=> Enable building net7.0 in Visual Studio

.github/fabricbot.json
The current FabricBot experiment doesn't appear to be removing the `no-recent-activity` label when a user does an action - I plan to continue the experiment with these changes. Also adds logic so that the `no-recent-activity` label doesn't get added when it's already on the PR.
=> FabricBot Adjustments

.github/fabricbot.json
There had been some discussion on https://github.com/dotnet/dotnet-monitor/pull/2374#issuecomment-1227595984 about what timeframes we want to use - this PR currently has the original ones, but once we settle on what we want to use I can update this as needed.
=> Update FabricBot Stale-Checker To Use Actual Timeframes and Apply to All PRs

src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/ProfilerBase.cpp, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ProfilerInitializationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/ProfilerHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs
Refactor profiler initialization to be callable by `Initialize` and `InitializeForAttach`.
Add unit tests for validating profiling at startup and attaching profiler.
=> Add profiler attach support and initialization unit tests

src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/MainProfiler/ExceptionTracker.cpp, src/MonitorProfiler/MainProfiler/ExceptionTracker.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/MainProfiler/ThreadData.cpp, src/MonitorProfiler/MainProfiler/ThreadData.h, src/MonitorProfiler/MainProfiler/ThreadDataManager.cpp, src/MonitorProfiler/MainProfiler/ThreadDataManager.h, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs
Remove exception tracking while evaluating future designs and allow the profiler to ship without it.
=> Disable exception tracking via profiler

src/Tools/dotnet-monitor/AddressListenResults.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/Startup.cs
This change clears the server URLs from configuration since the URLs are represented as endpoints in the KestrelServerOptions. This removes the warning that is displayed about overriding URLs from configuration:
```
12:15:26 warn: Microsoft.AspNetCore.Server.Kestrel[0]
Overriding address(es) 'https://localhost:52323'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
```
The above warning will no longer be logged since there are no URLs in configuration, yet the endpoints are still bound.
=> Clear server URLs after setting endpoints on KestrelServerOptions

documentation/docker.md
PR builds are failing due to 6.1 being removed from dotnet-docker repository. This change removes those links and adds new links for the Ubuntu Chiseled images
=> Update dotnet-docker links

src/MonitorProfiler/Environment/EnvironmentHelper.h, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/HostBuilderExtensions.cs, src/Tools/dotnet-monitor/CommonOptionsExtensions.cs, src/Tools/dotnet-monitor/Egress/EgressService.cs, src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs, src/Tools/dotnet-monitor/Profiler/ProfilerIdentifiers.cs, src/Tools/dotnet-monitor/Profiler/ProfilerService.cs, src/Tools/dotnet-monitor/ToolIdentifiers.cs
Standardize all environment variables to start with `DotnetMonitor_`
Standardize all profiler environment variables to start with `DotnetMonitor_Profiler_` (these are not user facing)
Rename the runtime identifier environment variable to not be specific to the profiler.
=> Standardize environment variable prefix

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DiagnosticPortTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/ScenarioRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestConditions.cs, src/Tools/dotnet-monitor/DiagnosticPort/DiagnosticPortPostConfigureOptions.cs, src/Tools/dotnet-monitor/ToolIdentifiers.cs
As part of the stacks experimental feature, a default shared path configuration property was added to provide a unified default directory where all file communication and sharing can be performed while preserving the ability to configure individual file sharing aspects. This work also enabled the creation of a listening diagnostic port socket in the default shared path if the diagnostic port was not otherwise configured and "flips" dotnet-monitor into listen mode.
This change modifies the behavior of the default diagnostic port by having the user opt into the behavior by having them specify the connection mode to be listen. Hence, if the user configures the connection mode to be listen AND the default shared path is specified AND the diagnostic port name is not specified, then a default …
=> Only create default diagnostic port when running in listen mode

global.json
This change removes the `x64` architecture from the list of runtimes that are installed as part of bootstrapping the build. This would allow for building and testing the repository on non-x64 machines (e.g. Windows x86 or arm64, Linux arm64). This change has no effect on x64 machines.
=> Use host architecture instead of x64 for runtimes

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/DefaultProcess.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/DiagnosticPort.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExpectedShowSourcesConfigurations/URLs.json, src/Tools/dotnet-monitor/ConfigurationExtensions.cs, src/Tools/dotnet-monitor/ConfigurationJsonWriter.cs, src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs
Currently, all of the configuration that is added as part of host configuration (this would largely be anything from the command line, the DOTNET_* variables, the ASPNETCORE_* variables) will have a reported source of `ChainedConfigurationProvider` when executing `config show --show-sources`. This is not particular helpful in understanding from where these values are provided.
This change effectively unwraps the occurrence of `ChainedConfigurationProvider` instances in the configuration writing algorithm to search within the chained configuration for the real configuration sources. Additionally, values that are provided from the command line have been changed to be represented by the `CommandLineConfigurationProvider` instead of by `MemoryConfigurationProvider`.
=> Unwrap ChainedConfigurationProvider to get real provider

src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptionsExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/MetricsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Startup.cs
Manual backport of #2530 to `release/6.x`
=> [release/6.x] Move metrics services configuration out of Startup class

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs
Currently if `dotnet-monitor` writes any text to stdout that is not JSON formatted during a functional test, it'll result in an unhandled exception and prematurely stop the test.
Under normal circumstances this is acceptable, however it prevents easily adding log statements for the purpose of debugging (e.g. adhoc `Console.WriteLine` when debugging a test failure). Update our test runner to handle this situation gracefully, not stopping the test.
=> Gracefully handle stdout that is not JSON formatted during tests runs

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/KestrelTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/ConfigurationExtensions.cs, src/Tools/dotnet-monitor/HostBuilderHelper.cs, src/Tools/dotnet-monitor/ServerUrlsBlockingConfigurationManager.cs, src/Tools/dotnet-monitor/ServerUrlsBlockingConfigurationProvider.cs, src/Tools/dotnet-monitor/ServerUrlsBlockingConfigurationSource.cs
Manual backport of #2535 to `release/6.x`
=> [release/6.x] Avoid Kestrel address override warning

eng/Versions.props, eng/dependabot/Directory.Build.props, eng/dependabot/Packages.props, eng/dependabot/Versions.props, eng/dependabot/dependabot.csproj
This is largely a backport of #2387 to `release/6.x` with bumps of the versions to their latest that do not require code changes. Follow-up PRs from dependabot will address the versions that require code changes.
=> Restructure versions for Dependabot updates

.github/dependabot.yml
Requires #2582 to be completed first.
=> Add release/6.x to dependabot NuGet updates

eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Microsoft.Diagnostics.Monitoring.ExecuteActionApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj
Arcade presets the xUnit version that is used and provides it as a `XUnitVersion` MSBuild property. Rather than trying to force xUnit to be newer than what Arcade expects, use this version for any direct xUnit dependencies.
=> Tie xunit.assert version to xunit version from Arcade

eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.ExecuteActionApp/Microsoft.Diagnostics.Monitoring.ExecuteActionApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj
Manual backport #2594 to `main`
=> [main] Tie xunit.assert version to xunit version from Arcade

eng/build.yml
This change moves all of the docker images to the latest tag as part of https://github.com/dotnet/arcade/issues/10377.
=> Use latest docker containers

.github/workflows/add-markdown-feedback.yml, .github/workflows/submit-linter-suggestions.yml
Part 2 of 2 for integrating "Was This Helpful" buttons - this PR adds in the workflows that check if a PR contains md files and add a suggestion to include a "Was This Helpful" button if it is not currently included. This utilizes a custom GitHub Action that I wrote ([AppendToFile](https://github.com/kkeirstead/AppendToFile)) - let me know if this should have a more permanent home, if we should leave it where it is, or something else.
=> Add "Was This Helpful" Actions (Part 2)

documentation/api/collectionrules-get.md, documentation/api/collectionrules-list.md, documentation/api/definitions.md, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/LoggingExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/ScenarioHelpers.cs
=> Fixing broken links and typos

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/CommonTestTimeouts.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/EnumerableExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunnerExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/LoggingRunnerAdapter.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunnerExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/ScenarioRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLiveMetricsActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectTraceActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTestsHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestHostHelper.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleActionBase.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleContainer.cs, src/Tools/dotnet-monitor/CollectionRules/CollectionRuleService.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/DisposableHelper.cs
This change splits out the behavior of stopping the process runners from disposing the process runners. This allows consistent access to process information after the process has stopped but before it is disposed (which the process information, such as exit code, are no longer available). As it was before, owners of the process runner are NOT required to call `StopAsync` before calling `DisposeAsync`.
The `AppRunner.ExecuteAsync` extension methods have been updated to call `StopAsync` instead of `DisposeAsync` in order to maintain the symmetry with the method starting the runner rather than creating and owning the runner. Callers are now responsible for disposing the runners.
Additional changes were made to unify the disposal patterns to use the common disposal helpers.
=> Split process stop from disposal and use disposal helpers

src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
The StaticWebAssets [issue](https://github.com/dotnet/aspnetcore/issues/42200) was fixed in the Preview 7 timeframe. The disablement workaround is no longer needed.
=> Remove StaticWebAssets disablement workaround

eng/Versions.props, eng/build.yml
With .NET Core 3.1 going EOL in December 2022 and libraries starting to not support the `netcoreapp3.1` TFM, remove building and testing .NET Core 3.1 apps.
=> Remove .NET Core 3.1 build and testing

global.json
Since `netcoreapp3.1` assets are no longer built nor tested, the frameworks for 3.1 do not need to be installed anymore.
=> Remove installation of .NET Core 3.1 frameworks

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/OverlappingEventSourceTests.cs
This test consistently fails, so it should be disabled. Issue was logged to track it: https://github.com/dotnet/dotnet-monitor/issues/2762
=> Skip AspNetResponseStatusTest

eng/Versions.props, eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj
Manual backport of #2610 and #2639 to `release/6.x`
I kept the version the same so that way we can test that dependabot will bump it correctly.
=> [release/6.x] Allow dependabot to manage Microsoft.Diagnostics.Monitoring.* libraries

eng/Version.Details.xml
The arcade update in #2793 attempted to remove the NuGet source for the `Microsoft.CodeAnalysis.NetAnalyzers` package. I believe it did this because the commit hash registered in the Version.Details.xml file was incorrectly specified. I've updated the commit hash to the correct value as reported in the `darc` tool.
I will close out #2973 and rerun the arcade update after this change is merged.
=> Fix Roslyn analyzers commit hash

src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
If a process exits between when it was discovered and getting additional information about it, then it will fail the entire process discovery mechanism. Misbehaving processes or processes at the end of their lifetime can cause this issue. To mitigate this, catch exceptions when trying to create the `IProcessInfo` instance for each process, log it, and continue enumerating the remaining processes.
Handle exceptions when determining additional information about discovered processes.
=> Handle exceptions when collecting additional info for discovered processes

src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
Manual backport of #2806 to `release/7.x`
=> [release/7.x] Handle exceptions when collecting additional info for discovered processes

src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/LoggingExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx
Manual backport of #2806 to `release/6.x`
=> [release/6.x] Handle exceptions when collecting additional info for discovered processes

src/Tools/dotnet-monitor/Logs/LogsOperation.cs, src/Tools/dotnet-monitor/PipelineArtifactOperation.cs
Allow base artifact operation class to support starting non-EventSource-based pipelines. Derived classes provide the core logic for starting the pipeline.
=> Support non-EventSource-based piplines as artifact operations

.github/dependabot.yml
Prevent the Microsoft.Extensions.* libraries from being updated outside of their current major version so that they stay in sync with the target framework version for dotnet-monitor. Major version changes to these libraries will require manual changes.
=> Pin Microsoft.Extensions.* dependabot updates to major versions

eng/dependabot/Versions.props
Bump Microsoft.Extensions.Configuration.KeyPerFile to 7.0.0 so that dependabot will keep it in sync with the other extension libraries.
=> Bump Microsoft.Extensions.Configuration.KeyPerFile to 7.0.0

CODE-OF-CONDUCT.md, README.md
The code of conduct links have been fixed on the .NET Foundation website with redirects. We need to revert our fix due to a policy violation even though they ultimately point to the same document.
=> Revert "Update code-of-conduct links (#2854)"

src/Tests/CollectionRuleActions.UnitTests/ActionListExecutorTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectDumpActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectGCDumpActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectLiveMetricsActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectLogsActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectTraceActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/ExecuteActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/LoadProfilerActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/TestCollections.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/CollectionRules/Actions/PassThroughAction.cs
This change runs the collection action tests serially so that they do not apply thread pool pressure to each other. The `PassThrough` action has also been rewritten to avoid using the `CollectionRuleActionBase` class, which is susceptible to delayed execution when the thread pool is starved.
=> Run collection rule action tests serially

dotnet-monitor.yml
I received an email indicating that we need to enable CodeQL3000 in our repo by tomorrow - I used [this](https://github.com/dotnet/roslyn/blob/main/azure-pipelines-official.yml#L43) as my reference, but **let me know if I should be going about this a different way.**
@hoyosjs 
Note: After talking with Joe and Juan, this change is intended to be a temporary fix to be compliant for CodeQL immediately - there were some performance concerns regarding increased build times by doing it this way. To avoid making large changes to the build pipelines without consulting Justin/Wiktor, this is a simple solution that can be reworked later if we want.
=> Enable CodeQL

eng/Versions.props
Bifurcate the versions of the ASP.NET authentication packages so that the `net6` usage can be versioned independently from the `netcoreapp3.1` usage.
=> [release/6.x] Bifurcate ASP.NET authentication package versions

eng/Versions.props, eng/dependabot/net6.0/Directory.Build.props, eng/dependabot/net6.0/Packages.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net6.0/dependabot.csproj, eng/dependabot/net7.0/Directory.Build.props, eng/dependabot/net7.0/Packages.props, eng/dependabot/net7.0/Versions.props, eng/dependabot/net7.0/dependabot.csproj, eng/dependabot/netcoreapp3.1/Directory.Build.props, eng/dependabot/netcoreapp3.1/Packages.props, eng/dependabot/netcoreapp3.1/Versions.props, eng/dependabot/netcoreapp3.1/dependabot.csproj
Manual backport of https://github.com/dotnet/dotnet-monitor/pull/2951 to release/7.0. Notable change is the removal of the NuGet.config files to match the common dependabot versioning folder.
This PR will be backported to `release/7.x` once merged.
=> [release/7.0] Make dependabot manage framework package versions

eng/Versions.props
Tie the `Microsoft.AspNetCore.Authentication.*` package versions to their corresponding ASP.NET framework versions so that they do not need to be manually updated. Historically, these packages have been updated in lockstep with the ASP.NET framework (they do not version faster nor slower than the framework).
=> Align ASP.NET authentication package versions with ASP.NET framework versions

eng/Versions.props, eng/dependabot/net6.0/Directory.Build.props, eng/dependabot/net6.0/Packages.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net6.0/dependabot.csproj, eng/dependabot/netcoreapp3.1/Directory.Build.props, eng/dependabot/netcoreapp3.1/Packages.props, eng/dependabot/netcoreapp3.1/Versions.props, eng/dependabot/netcoreapp3.1/dependabot.csproj
Manual backport of #2951 to `release/6.x`. Notable changes are the removal of the `net7.0` updates (since that doesn't exist in `release/6.x`) and the removal of the NuGet.config files to match the common dependabot versioning folder.
=> [release/6.x] Make dependabot manage framework package versions

eng/Versions.props
Manual backport of #2959 to `release/6.x`. Notable change is that `net7.0` versions were replaced by `netcoreapp3.1` versions.
=> [release/6.x] Align ASP.NET authentication package versions with ASP.NET framework versions

.github/dependabot.yml
Enable dependabot framework version updates on release branches and enable dependabot on the `release/7.0` branch.
=> Enable dependabot framework version updates on release branches

dotnet-monitor-codeql.yml, dotnet-monitor.yml, eng/PrepareRelease.yml, eng/build.yml
The `release/6.x` branch should be using the servicing pools since it is a release branch and it is no longer in active development.
=> [release/6.x] Use servicing build pools

eng/build.ps1, eng/build.sh, eng/build.yml, eng/citest.cmd, eng/citest.sh
- Avoid using the default binlog output by disabling it during test phase; the test phase already specifies its own log file.
- Do not install runtimes and restore the projects since they've been installed and restored during the build phase. This is accomplished with the `citest.[cmd|sh]` scripts that do not specify the `-restore` and `-preparemachine` flags.
=> Avoid restore and multi binlogs during test phase

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/OverlappingEventSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/ScenarioRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs
Instead of having each test determine when a process is available to get used via the dotnet-monitor HTTP API, consolidate this check for any test that is using `ScenarioHelper.SingleTarget`. I took a look at each one of the tests and it appears that none of them rely on being able to interact with the target process before it becomes available the process list.
=> Consolidate waiting for process availability into ScenarioHelper

documentation/api/definitions.md, documentation/api/stacks.md, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/CallStackData.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/CallStackEvents.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/EventStacksPipeline.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/JsonStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/StacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx, src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/EventProvider/ProfilerEvent.h, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/MainProfiler/MainProfiler.h, src/MonitorProfiler/Stacks/Stack.h, src/MonitorProfiler/Stacks/StackSampler.cpp, src/MonitorProfiler/Stacks/StackSampler.h, src/MonitorProfiler/Stacks/StacksEventProvider.cpp, src/MonitorProfiler/Stacks/StacksEventProvider.h, src/MonitorProfiler/Utilities/ThreadNameCache.cpp, src/MonitorProfiler/Utilities/ThreadNameCache.h, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksScenario.cs
Add support for thread names in the callstack artifact.
=> Add support for thread names stack artifacts.

documentation/openapi.json, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypeUtilities.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ContentTypes.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/SpeedScopeStackResults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProfilerChannel.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/StacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs, src/MonitorProfiler/CMakeLists.txt, src/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/MonitorProfiler/Utilities/ThreadUtilities.cpp, src/MonitorProfiler/Utilities/ThreadUtilities.h, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectStacksAction.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectStacksOptions.cs
* Add support for speedscope format
* Add comments and actually cache frames
* PR feedback
* Fix sleep for unix
* Update openapi schema
* PR feedback + unit test start
* Finish speedscope unit test
* Update src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs
Co-authored-by: Joe Schmitt <joschmit@microsoft.com>
Co-authored-by: Joe Schmitt <joschmit@microsoft.com>
=> [release/7.x] Add support for speedscope format (#2795)

documentation/kubernetes.md
The changes include:
- Splitting the sample for v6 vs v7 because (1) overriding the command line with just `--no-auth` is not sufficient, (2) there are better settings to use in v7.
- Removal of the second app from the samples so that the `/metrics` route works.
=> Update Kubernetes sample and docs

src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Operation/EgressOperationStoreTests.cs
`CancelOperation_Supports_StoppingState` appears to be flaky, skip it for now.
=> Skip flaky test CancelOperation_Supports_StoppingState

documentation/api/livemetrics-custom.md, documentation/configuration.md, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/JsonCounterLogger.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/PrometheusDataModel.cs, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/PrometheusDataModelTests.cs
These changes are the second part of addressing #430 (first-part can be found in the [diagnostics repo](https://github.com/dotnet/diagnostics/pull/3498)). This allows dotnet-monitor to show metadata in metrics and in live metrics.
Closes #430 
Add Metadata Support For Metrics
=> Add Metadata Support For Metrics

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
These changes update the SDK and code analyzers to .NET 8 and add the .NET 8 runtimes to be installed. No product or test code changes are part of this update; these will be done separately.
=> Update to .NET 8 SDK, runtimes, code analyzers

.github/workflows/lint-csharp.yml, eng/Versions.props, src/Directory.Build.targets, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/ActionTestsHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
- Update dotnet-monitor to build net6.0 and net8.0 TFMs
- Add net8.0 TFM to tests
- Prevent building of net8.0 assets in Visual Studio
=> Add net8.0 TFM to product and tests

.github/workflows/lint-csharp.yml, src/Tools/dotnet-monitor/ConfigurationKeys.cs
This PR fixes and re-enables linting on PRs that target main.  Of note, skip the analyzer phase of formatting as there appears to be an issue where `dotnet format` is trying to load an analyzer that isn't available locally (`Microsoft.CodeAnalysis.ExternalAccess.AspNetCore`).  This can be re-enabled later once properly triaged and fixed.
Also apply some minor cleanups to the workflow, simplifying it.
=> Fix c# linting on main

src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Options/SimpleConsoleFormatterOptions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/JsonSerializerOptionsFactory.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectTraceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleDescriptionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/EgressTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiStatusCodeException.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LogsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/OverlappingEventSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ProcessTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestConditions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Egress/AzureBlob/AzureBlobEgressProviderTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/AspNetScenario.cs
Remove any conditional TFM usage that included code for .NET 6 or later or excluded code for .NET 5 or lower since this branch now only builds .NET 6 or later.
=> Remove unnecessary conditional TFM usage

dotnet-monitor.yml, src/Directory.Build.props, src/Tests/CollectionRuleActions.UnitTests/ActionListExecutorTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectDumpActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectGCDumpActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectLiveMetricsActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectLogsActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/CollectTraceActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/ExecuteActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/LoadProfilerActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ProfilerInitializationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/BuiltInTriggerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDefaultsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesTests.cs
For pull requests, only run .NET 8 tests. For CI builds, run all tests. Remove scheduled build since CI builds will now run all tests.
=> Pull requests only run .NET 8 tests

dotnet-monitor.yml, src/Directory.Build.props, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ProfilerInitializationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/BuiltInTriggerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLiveMetricsActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectTraceActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDefaultsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesTests.cs
Manual backport of #3043 to `release/7.x`. Main difference is that PRs run .NET 7 instead of .NET 8 (which does not exist in the `release/7*` branches.
=> [release/7.x] Pull requests only run .NET 7 tests

dotnet-monitor.yml, src/Directory.Build.props, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTests/ExceptionTrackingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionListExecutorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/BuiltInTriggerTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectGCDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLiveMetricsActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectLogsActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectTraceActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDefaultsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleDescriptionPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ConfigurationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DiagnosticPortTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EndpointInfoSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExecuteActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/LoadProfilerActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesTests.cs
Manual backport of #3043 to `release/6.x`. Main difference is that PRs run .NET 6 instead of .NET 8 (which does not exist in the `release/6*` branches.
=> [release/6.x] Pull requests only run .NET 6 tests

documentation/release-process.md, eng/Version.Details.xml, eng/Versions.props, eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
This change allows easy pivoting of the diagnostic library versions between public releases and development versions. Change `UseMicrosoftDiagnosticsMonitoringShippedVersion` to `true` in order to use the publicly shipped version or `false` to use the development version.
=> [release/7.x] Allow pivoting on released vs development versions of diagnostics libraries

dotnet-monitor.yml, eng/build-test.yml, eng/build.yml
Split the test phase into a separate yaml template to allow the build phase to be reused in other pipelines.
=> Split build and test yaml into separate templates

dotnet-monitor.yml, eng/build-test.yml, eng/build.yml
Manual backport of #3105 to `release/7.x`; only difference is to remove .NET 8 from test result TFM list.
=> [release/7.x] Split build and test yaml into separate templates

dotnet-monitor.yml, eng/build-test.yml, eng/build.yml
Manual backport of #3105 to `release/6x`; only difference is the TFM test result list.
=> [release/6.x] Split build and test yaml into separate templates

dotnet-monitor.sln, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionProcessor.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionSourceBase.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/IExceptionSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipeline.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipelineBuilder.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipelineDelegate.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/FilterRepeatExceptionPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Microsoft.Diagnostics.Monitoring.StartupHook.csproj, src/Microsoft.Diagnostics.Monitoring.StartupHook/StartupHook.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/CurrentAppDomainExceptionSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/MockExceptionSource.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/ExceptionPipelineBuilderTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/ExceptionPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/Steps/AppendIntegerPipelineStep.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/Steps/FilterRepeatExceptionPipelineStepTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests.csproj, src/Tools/dotnet-monitor/DisposableHelper.cs
These changes provide an initial implementation of detecting first chance exceptions in target applications using a startup hook and providing a pipeline for processing the exception instances.
- First chance exceptions are monitored when the startup hook code is initialized.
- When an exception is detected, it is handled by a pipeline. This pipeline allows discrete steps to be taken in the specified order  to observe the provided exception. These steps an implementation specific: the only one currently registered is one that prevents rethrown exceptions from being considered. The current pipeline step list will be extended in the future as more of exception handling and reporting is fleshed out.
- The startup hook assembly is only built for .NET 6 but should be …
=> Initial in-proc exception detection and handling pipeline.

documentation/api/definitions.md, documentation/api/dump.md, documentation/api/gcdump.md, documentation/api/livemetrics-custom.md, documentation/api/livemetrics-get.md, documentation/api/logs-custom.md, documentation/api/logs-get.md, documentation/api/operations-list.md, documentation/api/operations-stop.md, documentation/api/operations.md, documentation/api/stacks.md, documentation/api/trace-custom.md, documentation/api/trace-get.md
Both of these features were originally listed as `8.0+`; however, they've since been backported to `release/7.x` (and are expected to go out as part of `7.1`). Updated the docs accordingly.
=> Fix documentation for stop traces and tags to reference correct version number

eng/Build.props, eng/Signing.props, eng/Versions.props, eng/build.ps1, eng/build.sh, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/platform-matrix.yml, src/Directory.Build.props, src/Tools/Directory.Build.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/dotnet-monitor-archive.proj
These changes add the ability to produce archives (zip for Windows, gzip-compressed tarballs for non-Windows) as part of build. The pipelines have been updated to produce and sign these archives but not to publish them (they will only be available as build artifacts until all of the outstanding issues are resolved).
- Add `-archive` switch to build scripts to optionally produce archives after building the managed and native components.
- The archive is built for the current platform, current build architecture, and latest target framework (namely .NET 7).
- The archives are produced from the `dotnet-monitor-archive.proj` file using Arcade's `Microsoft.DotNet.Build.Tasks.Archives` build task
- It builds the `dotnet-monitor.csproj` project as a framework dependent, RID-specific (e.g. …
=> Create platform and TFM specific archives

src/Directory.Build.props, src/Tools/Directory.Build.props
Do not pack executable shims for OSX in the .NET tool package because the build pipeline doesn't notarize them. These were accidentally added in #3204.
=> Do not pack shims for OSX

src/archives/dotnet-monitor-archive.proj
Make the file permissions of the contents of the archives consistent for tarballs.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2078461&view=results
=> Make file permissions consistent in archives

eng/Build.props, eng/Signing.props, eng/Versions.props, eng/build.ps1, eng/build.sh, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/platform-matrix.yml, src/Directory.Build.props, src/Tools/Directory.Build.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/dotnet-monitor-archive.proj
Manual backport of #3204 to `release/6.x`. Notable differences are:
- Changing the archive TFM from `net7.0` to `net6.0`.
- Excluding `osx-arm64` runtime identifier for `netcoreapp3.1`.
- Excluded the profiler assemblies from the archives in official builds as is done for the NuGet packages.
=> [release/6.x] Create platform and TFM specific archives

src/Directory.Build.props, src/Tools/Directory.Build.props
Manual backport of #3211 to `release/6.x`; only difference is that I have to exclude `osx-arm64` for `netcoreapp3.1`.
=> [release/6.x] Do not pack shims for OSX

eng/pipelines/jobs/build.yml
#3112 regressed the component governance coverage by not evaluating the `disableComponentGovernance` template parameter correctly which caused it to always be disabled. This change fixes the regression.
Build demonstrating that its fixed: https://dev.azure.com/dnceng/internal/_build/results?buildId=2079307&view=results
=> Fix Component Governance

CMakeSettings.json, eng/Build-Native.cmd, eng/build.sh, eng/pipelines/jobs/platform-matrix.yml, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/NativeLibraryHelper.cs, src/Tools/Directory.Build.props
Manual backport of #3224 to `release/6.x`; merge conflicts were on files that don't exist.
=> [release/6.x] Use RID folders instead of osGroup/architecture folders

eng/AfterSolutionBuild.targets, eng/Build-Native.cmd, eng/Build.props, eng/DotnetMonitorProjectToPublish.props, eng/PublishProjects.targets, eng/build.ps1, eng/build.sh, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/Directory.Build.targets, src/archives/PublishedProjectArchive.targets, src/archives/dotnet-monitor-archive.proj
The following changes were made to take a step in the direction of splitting packaging from binary build in the official builds:
- Move native build in front of managed build to allow for native build, managed build, and pack to be done with one build script invocation.
- Add ability to publish dotnet-monitor project for the current RID after build completes (opt-in using `/p:PublishProjectsAfterBuild=true`) __XOR__ when archiving (publish is done by default, opt-out using `/p:PublishProjectsAfterBuild=true`)
With the need to include the third-party notice (TPN) file in the archives (not done in this PR), the build needs to be refactored such that binaries are built in parallel with the TPN generation followed by archive and NuGet packaging. Currently, archiving effectively rebuilds the …
=> Allow archiving without building product

eng/AfterSolutionBuild.targets, eng/Build-Native.cmd, eng/Build.props, eng/DotnetMonitorProjectToPublish.props, eng/PublishProjects.targets, eng/build.ps1, eng/build.sh, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/Directory.Build.targets, src/archives/PublishedProjectArchive.targets, src/archives/dotnet-monitor-archive.proj
Manual backport of #3242 to `release/6.x`; manually resolved conflicts were on the CI condition in the dotnet-monitor project and the target framework property change in the archive project (which shouldn't be a conflict going forward).
=> [release/6.x] Allow archiving without building product

eng/Publishing.props, src/Directory.Build.targets, src/archives/Directory.Build.props, src/archives/dotnet-monitor-archive.proj
The following changes allow archive packages to participate in the publishing process (inclusion in the BAR manifest so that they are published to dotnetbuilds feed during Maestro promotion).
- Update `src/Directory.Build.targets` to produce projectpath and projectprops (these are new in this PR to support specifying per-project properties when the project is invoked during publish) files for both product archives and symbols archives.
- Update `src/Directory.Build.targets` to report correct archive name from `GetPackageFileName` target, which is invoked during publish.
- Update `eng/Publishing.props` include archive file types, to use the projectprops file for each package file (if it exists), and to only apply `Category=OTHER` to nupkg files (this categorization …
=> Enable checksum and publishing of archives

dotnet-monitor.yml, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/build-codeql.yml, eng/pipelines/jobs/build-test.yml, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/pack-sign-publish.yml, eng/pipelines/jobs/platform-matrix.yml, eng/pipelines/jobs/tpn.yml, src/archives/Directory.Build.targets, src/archives/dotnet-monitor-archive.proj
- Removed `jobName` and `displayName` parameters from `build.yml` in favor of calculating each using the platform, architecture, configuration, and the new `prefix` parameter.
- Moved publishing artifact information from `platform-matrix.yml` to `build-test.yml`.
- Pass RID information into `build-test.yml` so it can copy native binaries to unified artifact.
- Add `build-archive.yml` job that downloads binaries from `build-test.yml` job, builds the platform specific archive, and uploads it.
- Moved pack, sign, and publish into its own yml file for better separation; updated to download archives from new job.
- Move TPN creation into its own yml file for better separation.
One suggested optimization is to build all of the archives using a single job, however at this time, arcade doesn't …
=> Archive in separate job with license and TPN

eng/Publishing.props
Fixes an issue where the `Category=OTHER` metadata is not applied to nupkg files, which causes them to only be published to NuGet package feeds; the "other" categorization allows the packages to also be published to blob storage feeds.
=> Fix artifact publish metadata for NuGet packages

src/Directory.Build.targets
Allow non-shipping assets to participate in asset manifest generation. The effect of this change is that these non-shipping assets are published to the `dotnetbuilds` blob storage account, however they are not available when acquiring the drop during the release staging job (because the `--non-shipping` flag is not used, which is correct) so there shouldn't be any issue with accidentally releasing non-shipping artifacts.
This change allows us to more easily acquire and verify the non-shipping assets without releasing them.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2088444&view=results
=> Allow non-shipping assets in manifest generation

eng/pipelines/jobs/build.yml
Alpine 3.13 was EOL in November 2022; move to 3.14
=> Update Alpine build image to 3.14

documentation/openapi.json, eng/Signing.props, eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx, src/Tools/dotnet-monitor/dotnet-monitor.csproj
- Move the OpenApi security description to the OpenApiGen project
- Update the description to identify that this is the API Key authentication via bearer token and that the whole authorization header value must be used.
- Minimize the dependencies shipped in the tool by just using the UI package.
- Add 3rd party signing entry for shipped assemblies.
=> Swagger generation updates and minimize shipping dependencies

src/Directory.Build.targets
The unused Windows-only TraceEvent native dependencies are being included in the published output of dotnet-monitor. This is happening because publish is not resolving the paths in absolute terms. To fix this, add another removal entry that matches the relative paths used by TraceEvent to prevent them being included during publish.
=> Remove unused TraceEvent Windows-only dependencies two ways.

src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs
The OpenApiGen tests fail for .NET 7 and .NET 8 due to differences in some of the built-in structures (e.g. `TimeSpan` has `Microseconds` in .NET 7+ but not in .NET 6). The openapi.json document is based on the .NET 6 generation, so have the tests only run that version.
=> Only run .NET 6 OpenApiGen

dotnet-monitor.yml, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/build-test.yml, eng/pipelines/jobs/pack-sign-publish.yml, src/Directory.Build.props, src/Tools/Directory.Build.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/Directory.Build.targets, src/archives/dotnet-monitor-archive.proj
- Stop including profiler files during RID publishing.
- Move profiler inclusion to archive build.
- Include both musl and glib based profilers in each other's archives.
- Move archive build to separate stage since they depend on all build jobs to finish and publish artifacts into a unified artifact.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2091950&view=results
=> Allow bundling of cross-platform native libraries

src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj
Manual backport of #3387 to `release/6.x`; there were conflicts on the TFM specification because 6.x used a literal whereas the other branches use an MSBuild property.
=> [release/6.x] Run OpenApi tests for all TFMs

dotnet-monitor.yml, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/build-test.yml, eng/pipelines/jobs/pack-sign-publish.yml, src/Directory.Build.props, src/Tools/Directory.Build.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/Directory.Build.targets, src/archives/dotnet-monitor-archive.proj
Manual backport of #3381 to `release/6.x`; conflict was on the exclusion of the profiler assemblies from CI builds.
=> [release/6.x] Allow bundling of cross-platform native libraries

src/Directory.Build.targets
Using NUGET_PACKAGES property for looking up paths of NuGet package files works on Windows but not on non-Windows due to extra slashes. This causes the removal of the extra trace event library files to not work on non-Windows platforms. Use NuGetPackageRoot instead which is correctly normalized.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2096170&view=results
I'll only complete this PR if the referenced build produces the correct removal.
=> Use NuGetPackageRoot instead of NUGET_PACKAGES

documentation/openapi.json, eng/Signing.props, eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Microsoft.Diagnostics.Monitoring.OpenApiGen.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Manually backport #3375 to `release/7.x`; no true conflict occurred despite backport command failing.
=> [release/7.x] Swagger generation updates and minimize shipped dependencies

eng/PublishProjects.targets
Include the apphost (e.g. `dotnet-monitor.exe` or `dotnet-monitor`) in the archives in order to preserve the existing behavior of the Dockerfiles (which invoke the apphost). This adds about ~1% to the contents of the archive.
=> Include apphost in archives

eng/Build.props, eng/Common.props, eng/DotnetMonitorProjectToPublish.props, eng/Versions.props, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/build-test.yml, src/archives/PublishedProjectArchive.targets, src/archives/dotnet-monitor.props, src/archives/pkgs/Directory.Build.targets
- Create unified specification of the latest target framework in the new `./eng/Common.props` file. Update all MSBuild usage of that target framework value to use the new property, especially the archive infrastructure which specified this value multiple times.
- Update build publish to publish under `./artifacts/pub/<project>/<configuration>/<tfm>/<rid>`. This allows all build legs to publish their `./artifacts/pub` folder without collisions instead of publishing to separate artifacts. This will allow for future change where a single job can do all archiving as well as a single job can sign all archivable content.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2097060&view=results
=> Unified latest target framework spec and publish directory

src/archives/pkgs/Directory.Build.targets
Recent changes regressed the permissions fixup logic when the common archive production code had the staging content path removed from it, so it started changing the permissions of the source files instead of the staging files. This change updates the logic to change the permissions on the staged files instead.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2097098&view=results
=> Change permissions on staged files instead of source files

eng/Build.props, eng/Common.props, eng/DotnetMonitorProjectToPublish.props, eng/Versions.props, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/build-test.yml, src/archives/PublishedProjectArchive.targets, src/archives/dotnet-monitor.props, src/archives/pkgs/Directory.Build.targets
Manual backport of #3462 to `release/6.x`; adjusted the LatestTargetFramework usage to `net6.0` and replaced `net6.0` with the property.
=> [release/6.x] Unified latest target framework spec and publish directory

src/archives/pkgs/Directory.Build.props, src/archives/pkgs/Directory.Build.targets, src/archives/pkgs/dotnet-monitor/dotnet-monitor-archive.proj
- Use ItemDefinitionGroup to provide defaults for metadata.
- Mark the `dotnet-monitor` executable so that it is made executable before archiving.
=> Mark dotnet-monitor as executable in archives

dotnet-monitor.sln, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionProcessor.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionEvents.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSourceIdentifierCacheCallback.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionIdentifier.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionIdentifierCache.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionIdentifierCacheCallback.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionIdentifierData.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Microsoft.Diagnostics.Monitoring.StartupHook.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/CallStackData.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/CallStackEvents.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/EventStacksPipeline.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/JsonStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameCache.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameIdentificationEvents.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/StacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventListener.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/ExceptionIdentifierCacheTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/ExceptionIdentifierTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/TestExceptionIdentifierCacheCallback.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests.csproj
- Add event source for producing exception information so that external process (e.g. dotnet-monitor) can get exception information that is grouped and identified by the `ExceptionIdentifier` class.
- Add exception identifier cache that invokes callbacks when new exception identification information is added to it. This allows filtering of repeated exceptions so that the event source doesn't have to repeat the same exception, method, type, and module information.
=> Exceptions event source and exception identifier cache

dotnet-monitor.yml, eng/Signing.props, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/sign-binaries.yml
The SignTool task only knows how to unpack *.nuget and *.zip files in order to sign their contents. This leaves all of the files *.tar.gz unsigned.
This change adds an additional job after build but before archiving that signs all of the archive content in one pass.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2100455&view=results
=> Sign published artifacts before archiving

src/archives/pkgs/dotnet-monitor/dotnet-monitor-archive.proj
With all outstanding work finished for the archives (with the exception of #3506), the archives can now be marked as shipping. This has very little effect on the builds, however it allows the files to be copied to dotnetstage storage account to prepare for shipping.
=> Mark archives for shipping

documentation/release-process.md, dotnet-monitor.yml, eng/pipelines/stages/preparerelease.yml
Tag builds from `main` with `docker-update` if variable enables it. This allows us to more easily opt into and out of producing dotnet-docker updates of nightly builds from the main branch.
=> Tag build for dotnet-docker update if enable nightly update from main

src/Microsoft.Diagnostics.Monitoring.WebApi/IExperimentalFlags.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IInProcessFeatures.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TestExperimentalFlags.cs, src/Tools/dotnet-monitor/Experimental/ExperimentalFlags.cs, src/Tools/dotnet-monitor/Experimental/ExperimentalStartupLogger.cs, src/Tools/dotnet-monitor/InProcessFeatures/InProcessFeatures.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Add an experimental feature flag for the exceptions feature. Note that the feature itself is not implemented yet; this should be added before any exception feature code is added to dotnet-monitor.
=> Add exceptions experimental feature flag

eng/Version.Details.xml, eng/Versions.props, global.json
Rearrange coherent dependencies around updates from the dotnet/installer repository. Update versions to the latest from the ".NET 8.0.1xx SDK Preview 1" channel. The "Microsoft.Dotnet.Sdk.Internal" dependency is not actually used in product or test, but is used as a single point to synchronize the dependencies; a subscription will be added to pull the updates from the dotnet/installer repo in the ".NET 8.0.1xx SDK Preview 1" channel.
=> [release/8.0] Update dependencies and SDK to 8.0 Preview 1

dotnet-monitor.yml, eng/pipelines/stages/preparerelease.yml
There were two issues regarding the `NightlyUpdateDockerFromMain` pipeline variable:
- Looking up the variable with template syntax (e.g. `${{ varaibles['NightlyUpdateDockerFromMain'] }}`) only takes that value at template compile time and doesn't consider the value at queue time. Thus the pipeline variable defined on the AzDO pipeline was ignored. I had to move to using runtime evaluation, hence the change to using it within a condition on the tagging task rather than using templating to exclude the task.
- Having the `NightlyUpdateDockerFromMain` variable declared in both the yaml pipeline and AzDO pipeline ignored the value from the AzDO pipeline. Even though the job would state that the value of the variable is what was set at queue time, the runtime evaluation of the variable would …
=> Fix docker tag opt-out variable and usage

.github/dependabot.template.yml, .github/dependabot.yml
Add branch prefix to commit messages for dependabot updates so its easier to discern which branch is being targeted.
Example PR update: https://github.com/jander-msft/dotnet-monitor/pull/66
=> Use branch name as message prefix for dependabot updates

dotnet-monitor.yml, eng/pipelines/dotnet-monitor-codeql.yml, eng/pipelines/dotnet-monitor-release.yml, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/sign-binaries.yml, eng/pipelines/jobs/tpn.yml, eng/pipelines/stages/preparerelease.yml
Use pool provider variables from Arcade; this allows us to not have to update the pool names when merging between branches and forking branches.
=> Use pool provider variables

documentation/configuration/metrics-configuration.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/TraceUtilities.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Validation/CounterValidator.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRuleOptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsSettingsTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectTraceOptions.Validate.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/AspNetRequestDurationTriggerFactory.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/EventCounterTriggerFactory.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Requires https://github.com/dotnet/diagnostics/pull/3639
=> Allow per provider interval specification

eng/release/Scripts/GetBuildVersion.ps1
Now that non-shipping assets are included in the publishing to the Build Asset Registry, they appear in assets for the build. Need to filter out non-shipping assets before determining the build version.
=> Fix GetBuildVersion script

eng/Publishing.props, src/Directory.Build.targets
With the usage of the archives in the dotnet-docker images, the nupkgs no longer need to be publshed to blob storage since there are no remaining scenarios that acquire them via blob storage. Anything else should be using either `dotnet tool`, the dotnet-tools feed, or the darc-pub-*/darc-int-* feeds for final releases.
Here's a diff of the relevant sections of the assert manifest for a build before and after the change.
```diff
<Build>
...
-    <Blob Id="diagnostics/monitor/7.1.0-rtm.23109.6/dotnet-monitor.7.1.0.nupkg" Category="OTHER" />
-    <Blob Id="diagnostics/monitor/7.1.0-rtm.23109.6/dotnet-monitor.7.1.0.nupkg.sha512" />
-    <Blob Id="diagnostics/monitor/7.1.0-rtm.23109.6/Microsoft.Diagnostics.Monitoring.WebApi.7.1.0-rtm.23109.6.nupkg" Category="OTHER" NonShipping="true" />
- …
```
=> No longer publish nupkg to blob feeds

.github/workflows/respond_to_first_issue.yml
Mark and I were chatting yesterday about ways to engage more with users, and one of the things we talked about was finding a way to get more feedback through our surveys. As opposed to having a passive survey link in our docs that gets skimmed over, we meet users where they are by asking them for feedback when they've demonstrated a desire to interact with us (i.e. creating an issue). Having a bot automatically create a comment should hopefully improve our survey's CTR, and this message is only presented for someone's first issue (to prevent it from becoming spam). Here's an example of Mark trying it on my fork: https://github.com/kkeirstead/dotnet-monitor/issues/150
=> Automatically Solicit Feedback From First-Time Issues

eng/pipelines/jobs/pack-sign-publish.yml
Fix pipeline step that copies a buildversion file to use one that exists. The *.nupkg.buildversion file no longer exists because nupkg are no longer published to blob storage.
=> Fix build info gathering

src/Extensions/Directory.Build.props
Update the RID specifications for extensions to match dotnet-monitor.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2116266&view=results
=> Update RID support to match dotnet-monitor

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/OverlappingEventSourceTests.cs
Seems to no longer repo due to fixes in #2914
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2119826&view=results
closes #2762
=> Reenable AspNetResponseStatusTest test

documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionInstance.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionsFormat.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionInstance.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionsStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IExceptionsOperationFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/OutputStreamResult.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperationFactory.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsService.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
- Adds a single instance of an exceptions store that contains the exception information for the default process. The exception store will quickly consume the information from the provider and queue it for processing shortly thereafter.
- Adds an exceptions service that will start the exceptions pipeline on the default process and insert the exception information into the store for the default process.
- Add the `/exceptions` route that only reports exception information from the default process. This route is authenticated and can produce `text/plain`, `application/x-ndjson`, and `application/json-seq` formats.
Example output of the `/exceptions` route:
Plain text:
```
First chance exception. System.InvalidOperationException: The current time is 2/27/2023 11:37:21 PM
First chance …
```
=> Basic exceptions store and route for default process

dotnet-monitor.yml
Publish the `.gdn` directory after validation for easier manual inspection.
=> Publish guardian directory after validation

src/Microsoft.Diagnostics.Monitoring.WebApi/IInProcessFeatures.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputNativeFileProvider.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputSharedLibraryInitializer.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/HostingStartup.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/InProcessFeatures/InProcessFeatures.cs, src/Tools/dotnet-monitor/LibrarySharing/DefaultSharedLibraryInitializer.cs, src/Tools/dotnet-monitor/LibrarySharing/IFileProviderFactory.cs, src/Tools/dotnet-monitor/LibrarySharing/ISharedLibraryInitializer.cs, src/Tools/dotnet-monitor/LibrarySharing/ISharedLibraryService.cs, src/Tools/dotnet-monitor/LibrarySharing/NativeLibraryHelper.cs, src/Tools/dotnet-monitor/LibrarySharing/SharedFileProvider.cs, src/Tools/dotnet-monitor/LibrarySharing/SharedLibraryService.cs, src/Tools/dotnet-monitor/Profiler/ProfilerService.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Refactor library sharing from the profiler service so that other features that are not dependent on the profiler can use library sharing with target processes.
=> Split library sharing initialization from profiler service.

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputManagedFileProvider.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputSharedLibraryInitializer.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsService.cs, src/Tools/dotnet-monitor/LibrarySharing/DefaultSharedLibraryInitializer.cs, src/Tools/dotnet-monitor/LibrarySharing/IFileProviderFactory.cs, src/Tools/dotnet-monitor/LibrarySharing/SharedFileProvider.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/StartupHook/StartupHookValidator.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx, src/Tools/dotnet-monitor/ToolIdentifiers.cs
These changes check that if the exceptions features are enabled then the default process needs to be configured correctly (the `DOTNET_STARTUP_HOOKS` environment variable needs to be set appropriately). The startup hook validator will log warning messages as to why the startup configuration of the target process is not sufficient. At this time, startup hook environment variable is the only way to configure target processes load the exceptions logging infrastructure.
Changes also include the ability to query for the managed libraries from the shared libraries path.
=> Startup hook validation for enabling exceptions capture

eng/pipelines/jobs/build-test.yml, src/Microsoft.Diagnostics.Monitoring.StartupHook/ProjectsToPublish.props
Currently, each build leg is publishing platform neutral outputs and uploading them to the same build artifact and sub path. This can cause a race condition between two build legs that are publishing at the same time. This change fixes this behavior by only publishing platform neutral outputs on the win-x64 release build leg. Additionally, the publish outputs for this build leg are also uploaded to the Build_Unified_Release artifact so that nupkg creation can consume it without publishing it (currently, the nupkg creation leg is invoking publish, but this will be fixed in a different change).
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2130271&view=results
=> Only publish platform neutral outputs on win-x64 release leg

eng/AfterSolutionBuild.targets, eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/pack-sign-publish.yml, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/PublishedProjectPackage.targets
Allow the archive and package legs to explicitly opt out of publishing projects and relying on the build legs to provide the published binaries. This change requires #3883 as seen from the example build where it fails to package due to missing published binaries.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2130279&view=results
=> Allow skipping publishing of projects in archive and package legs

eng/Common.props, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/AzureBlobStorage/Package.props, src/archives/AzureBlobStorage/ProjectsToPublish.props, src/archives/S3Storage/Package.props, src/archives/S3Storage/ProjectsToPublish.props
Publish platform neutral variants of the extensions and include them in the dotnet-monitor tool nupkg under `extensions/AzureBlobStorage` and `extensions/S3Storage`. Separate changes are required to execute the extensions from dotnet-monitor using the shared framework host (`dotnet`) instead of searching for a platform-specific executable.
Note that the extensions are intentionally not packed into the dotnet-monitor archive files since that should remain minimal to allow for custom composition.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2130927&view=results
=> [Egress] Publish and include extensions in tool nupkg

src/Tools/dotnet-monitor/dotnet-monitor.csproj
Now that cloud egress providers are external to the dotnet-monitor tool, remove the libraries from the tool to reduce the package size.
=> Remove cloud egress libraries from dotnet-monitor

src/archives/AzureBlobStorage/Package.props, src/archives/PublishedProjectPackage.targets, src/archives/S3Storage/Package.props
Nest the contents of the extensions under the `extensions/<extension_name>` subfolder within the archives. This allows unpacking of the dotnet-monitor and extension archives into the same root directory without having to know which folders the extension archives would need to be unpacked.
=> Nest extension content in archives under extensions folder

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectTraceAction.cs, src/Tools/dotnet-monitor/Logs/LogsOperation.cs, src/Tools/dotnet-monitor/Logs/LogsOperationFactory.cs, src/Tools/dotnet-monitor/Metrics/MetricsOperation.cs, src/Tools/dotnet-monitor/Metrics/MetricsOperationFactory.cs, src/Tools/dotnet-monitor/PipelineArtifactOperation.cs, src/Tools/dotnet-monitor/Trace/AbstractTraceOperation.cs, src/Tools/dotnet-monitor/Trace/TraceOperation.cs, src/Tools/dotnet-monitor/Trace/TraceOperationFactory.cs, src/Tools/dotnet-monitor/Trace/TraceUntilEventOperation.cs
Addresses https://github.com/dotnet/dotnet-monitor/issues/3916.
Fixes issue where trace operations with an egress provider and rundown on Linux would cause dotnet-monitor to lose connectivity with the target application.
=> Refactor registration to artifact operation

src/Extensions/AzureBlobStorage/extension.json, src/Extensions/S3Storage/extension.json, src/Tests/CollectionRuleActions.UnitTests/CollectLogsActionTests.cs, src/Tests/CollectionRuleActions.UnitTests/ExecuteActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/AssemblyHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/GenerateDotNetHost.targets, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestDotNetHost.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestDotNetHost.cs.template, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/DumpTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/Options/CollectionRuleOptionsExtensions.cs, src/Tools/dotnet-monitor/DotNetHost.Unix.cs, src/Tools/dotnet-monitor/DotNetHost.Windows.cs, src/Tools/dotnet-monitor/DotNetHost.cs, src/Tools/dotnet-monitor/Extensibility/ExtensionDeclaration.cs, src/Tools/dotnet-monitor/Extensibility/ProgramExtension.cs
Extensions can specify `"UseSharedDotNetHost": true` in their manifest in order to instruct dotnet-monitor to execute the extension using the shared framework host (e.g. `dotnet.exe`) instead of the platform-specific apphost in the extension. This allows a platform-neutral extension to be used so that extensions do not have to have separate apphost executables for each supported platform.
=> [Egress] Support using shared framework host to execute extensions

src/Tools/dotnet-monitor/Extensibility/ProgramExtension.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
The extension started message currently prints the path to the file that's starting up - with the recent changes to using the dotnet executable, this message isn't helpful for users (on linux: `Starting extension '/usr/share/dotnet/dotnet '`).
For human-readability, this switches the logging statement to show the name of the extension (now: `Starting extension 'AzureBlobStorage'.`)
=> [Egress Extensibility] Change Logging Message For When Extension Starts

.github/fabricbot.json
After discussing some of the main issues we face with PRs, it seemed like one of the main issues was that PRs start to get stale (especially after multiple review cycles). By default, GitHub doesn't offer a clear way to tell when an item is still being worked on versus when it needs another round of feedback. This PR adds a `needs-review` label whenever a contributor pushes a new commit to their PR - whenever someone reviews or leaves a comment on the PR, the label should automatically be taken away. This _should_ require no manual intervention, and provides a visual way to quickly tell which things need a fresh review (the label is neon green, so it should stand out at a glance).
Since this uses fabricbot, I haven't been able to verify that this works - I intend to test it once it's …
=> [Experimental] Add/Remove `needs-review` label to PRs

.github/fabricbot.json
=> Fixes `needs-review` Fabricbot to remove label on close/merge

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMoniker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TargetFrameworkMonikerExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutput.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputExtensionRepository.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputManagedFileProvider.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputNativeFileProvider.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputSharedLibraryInitializer.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/HostingStartup.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup.csproj, src/Tools/dotnet-monitor/Extensibility/ExtensionRepository.cs, src/Tools/dotnet-monitor/Extensibility/FolderExtensionRepository.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Allow building and using extensions directly from debug build output without having to stage the egress extensions.
This is done by adding another ExtensionRepository implementation to the test hosting startup that understands how to locate extensions from the build output directory.
=> Allow using extensions from build output

documentation/schema.json, src/Extensions/AzureBlobStorage/AzureBlobStorage.csproj, src/Extensions/S3Storage/S3Storage.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/SchemaGenerator.cs
Add the known extensions back to the configuration schema. This almost brings the schema back to its state before the refactor, except that the descriptions and default values for the egress properties do not exist. This will be added in a future PR.
=> Add known extensions to configuration schema

src/Extensions/AzureBlobStorage/extension.json, src/Extensions/S3Storage/extension.json, src/Tests/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp/extension.json, src/Tools/dotnet-monitor/Extensibility/ExtensionDeclaration.cs, src/Tools/dotnet-monitor/Extensibility/ExtensionNotFoundException.cs, src/Tools/dotnet-monitor/Extensibility/ProgramExtension.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Simplifies the extension manifest to only have three properties:
- Name: The name of the extension e.g. AzureBlobStorage or S3Storage
- ExecutableFileName: The name of the executable entry point if to be launched using its own executable.
- AssemblyFileName: The name of the entry point assembly if to be launched using the shared .NET host (e.g. dotnet.exe).
Everything else that was removed either was unused or would lead to future confusion if we add other extensibility points.
=> Simplified extension manifest

src/Extensions/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressHelper.cs, src/Extensions/S3Storage/S3StorageEgressProvider.cs, src/Extensions/S3Storage/Strings.Designer.cs, src/Extensions/S3Storage/Strings.resx
Re-enables data annotation validation for egress providers; fixes the issue with S3 exceptions double-including their "egress failed" prefix.
=> [Egress Extensibility] Re-enable data annotation validation and other minor logging-related fixes

.github/fabricbot.json
When telling Fabricbot to add a label, it appears that behind the scenes it's actually just toggling the state of the label. See this PR as an example of what happens when changes are pushed currently: https://github.com/dotnet/dotnet-monitor/pull/4083. This change puts an explicit check on the "add label" task, ensuring the label is not already there. All other `needs-review` tasks already had this check in place.
=> Fix `needs-review` label toggling issue

documentation/schema.json, src/Extensions/AzureBlobStorage/AzureBlobEgressProvider.cs, src/Extensions/AzureBlobStorage/AzureBlobEgressProviderOptions.cs, src/Extensions/S3Storage/MultiPartUploadStream.cs, src/Extensions/S3Storage/S3StorageEgressProvider.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IEgressService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperation.cs, src/Tests/CollectionRuleActions.UnitTests/Egress/Pipe/PipeEgressProvider.cs, src/Tools/dotnet-monitor/Egress/EgressProvider.cs, src/Tools/dotnet-monitor/Egress/EgressProviderInternal.cs, src/Tools/dotnet-monitor/Egress/EgressService.cs, src/Tools/dotnet-monitor/Egress/IEgressProvider.cs, src/Tools/dotnet-monitor/Egress/IEgressProviderInternal.cs
Cleaned up our usage of `CopyBufferSize` for Azure & S3. I'll leave comments around certain lines of code down below that need further context.
=> [Egress] Clean-Up For CopyBufferSize

.github/fabricbot.json
Requiring that the `needs-review` label must be in place AND the PR must be merged/closed - this was being triggered when any action on a PR occurred while the `needs-review` label was in place, creating a loop of manually tagging a PR and having it automatically removed. This may have been the true root cause of #4084, though those changes are still good practice to have in place.
=> Tweaking `needs-review` bot

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
Closes #4095 
Represent System.Diagnostics.Metrics Counters as Gauges in Prometheus Exposition Format.
=> Represent SDM Counters as Gauges In Prometheus Exposition Format

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputExtensionRepository.cs, src/Tools/dotnet-monitor/Egress/Configuration/EgressProviderConfigurationProvider.cs, src/Tools/dotnet-monitor/Egress/Configuration/IEgressProviderConfigurationProvider.cs, src/Tools/dotnet-monitor/Egress/EgressService.cs, src/Tools/dotnet-monitor/Egress/Extension/EgressExtension.cs, src/Tools/dotnet-monitor/Egress/Extension/EgressExtensionFactory.cs, src/Tools/dotnet-monitor/Egress/Extension/ExtensionEgressProvider.cs, src/Tools/dotnet-monitor/Egress/Extension/IEgressExtension.cs, src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressExtension.cs, src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressExtensionFactory.cs, src/Tools/dotnet-monitor/Extensibility/FolderExtensionRepository.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
This is a "separation of concerns" fixup PR.
Move the parsing of the egress provider configuration section from `ExtensionEgressProvider` into `EgressExtension`. This allows the `FileSystemEgressExtension` to not manually look up its options from a dictionary but instead using options binding. Move the creation o the `EgressExtension` into a factory so that other callers do not have to provide the myriad of services it requires.
=> Move egress configuration parsing into EgressExtension

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesConfigurations/CollectionRules.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesConfigurations/Templates.json, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/TemplatesTests.cs, src/Tools/dotnet-monitor/Egress/Configuration/EgressConfigurationProvider.cs, src/Tools/dotnet-monitor/Egress/EgressProviderSource.cs, src/Tools/dotnet-monitor/Egress/EgressService.cs, src/Tools/dotnet-monitor/Egress/EgressStartupLogger.cs, src/Tools/dotnet-monitor/Egress/Extension/EgressExtension.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
- Moved enumeration and caching of egress providers into separate class named `EgressProviderSource`.
- Add startup logger that initializes the `EgressProviderSource`, which causes it to log any missing egress providers.
=> Validate configured egress providers at startup

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
The SDM Histogram `LessThan` test has occasional failures - before completely disabling the test, wanted to experiment with pushing the bounds to the extremes (I also did this for the `GreaterThan` test). If instability persists after this change, I'll disable the `LessThan` test.
=> Adjust Bounds For Unstable SDM Histogram Test

eng/Versions.props
Manual backport of #4123 to `release/7.x`
=> Allow VS using repository SDK to build for latest TFM

src/Extensions/Directory.Build.props
Exclude the creation of tool packages for the extensions since we do not plan on shipping the extensions as .NET Tools.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2152275&view=results
=> Do not create tool packages for extensions

eng/pipelines/stages/preparerelease.yml
- Remove the installation of .NET Core 3.1
- Always prebuild the release tool project so the build log is available.
- Upload tool logs and staged assets to consistently named artifacts.
- Rename stage, job, and tasks to better describe what they are doing.
Non release branch test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2152117&view=results
Test release branch test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2152306&view=results
=> Cleanup release preparation stage

src/Microsoft.Diagnostics.Monitoring.Options/FileSystemEgressProviderOptions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/FileSystemEgressExtensionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressExtension.cs
FileSystem egress options validation was accidentally removed in #4082. This change adds it back to the extension implementation and adds tests to check that the validation exists and is correct.
=> Validate FileSystem egress options

src/Extensions/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressHelper.cs, src/Extensions/Microsoft.Diagnostics.Monitoring.Extension.Common/Microsoft.Diagnostics.Monitoring.Extension.Common.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EgressExtensibilityTests.cs
This should have been updated in #4179 and was inadvertently left out. This directly copies the logic being used in that PR to be used in the tests.
I might make some improvements to this testing in the future, but for now this PR should stop builds from failing.
=> Fixing Egress Extensibility Tests To Follow Updated StdIn Protocol

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSourceIdentifierCacheCallback.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionIdentifier.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionIdentifierCache.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/ExceptionIdentifierCacheCallback.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/StackFrameData.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Identification/StackFrameIdentifier.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/CurrentAppDomainExceptionSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventListener.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/ExceptionIdentifierCacheTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/ExceptionIdentifierTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Identification/TestExceptionIdentifierCacheCallback.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/ExceptionPipelineBuilderTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/ExceptionPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/Steps/FilterRepeatExceptionPipelineStepTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/MonitorLibrary.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksWorker.cs, src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionEvents.cs
- Report stack frame information (list of method and IL offset pairs) from exceptions
- Cache stack frame information so that it is not repeated through the event source
- New stack frame information is reported to the event source.
- Added tests to validate caching and event source information.
- Fix call stack gathering in order to get full call stack of thrown exception.
- Fixed TargetFrameworkMonikerTrait attributes on tests to have them correctly run when filtered by TFM (e.g. PR builds only run tests for the latest TFM)
Note: The dotnet-monitor tool does nothing with the stack frame information. This is will be implemented in a follow up PR in order to keep this one simple.
=> Add stack frame information to exceptions event source

documentation/configuration/diagnostic-port-configuration.md
Base on the official [json schema](https://raw.githubusercontent.com/dotnet/dotnet-monitor/main/documentation/schema.json), 
"MaxConnections" has been changed the type from string to int.
Json schema code block:
```        "MaxConnections": {
"type": [
"integer",
"null"
],
"description": "In 'Listen' mode, the maximum amount of connections to accept.",
"format": "int32"
},
```
=> The type of "MaxConnections" is error

eng/cibuild.sh
All of the fixups in the cibuild.sh script are no longer applicable.
=> Remove fixups from cibuild script

eng/pipelines/jobs/build-binaries.yml, eng/pipelines/jobs/build-codeql.yml, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/test-binaries.yml, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestConditions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EgressExtensibilityTests.cs
This change switch all of the build jobs to use CBL Mariner with cross build support for clib and architecture variants.
- Switch to using CBL Mariner as the default container for Linux builds; allow test jobs to override the container to run the tests on distros that have the target clib and architecture types.
- Move the cross-build notion up into the build-binaries job since it's only necessary when building binaries; base codeql job on this job instead of base build job.
- Disable tests the execute the test egress extension on Alpine images for now. The apphost for the extension is glibc x64, so it won't execute on Alpine. Will attempt a solution for this after this PR.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2173397&view=results …
=> Use CBL Mariner build images

eng/pipelines/jobs/build-binaries.yml, eng/pipelines/jobs/build.yml
Arcade pipeline templates now dynamically component governance based on the branch name and the build type. Switch to using the default value (empty string) so that Arcade can make this determination; non-default value are passed directly through to the CG task to explicitly enable or disable the task.
We shouldn't need the carve out for Alpine x64 since transitioning to using CBL Mariner for build.
=> Only disable CG if explicitly set

src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressArtifactSettings.cs, src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressException.cs, src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressHelper.cs, src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressProperties.cs, src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressProvider.cs, src/Microsoft.Diagnostics.Monitoring.Extension.Common/Microsoft.Diagnostics.Monitoring.Extension.Common.csproj, src/Microsoft.Diagnostics.Monitoring.Extension.Common/MonitoringException.cs
Note that `EgressHelper.GetPayload` is still internal only.
=> Change extension common code to be public

.github/workflows/generate-release-notes.yml, eng/Publishing.props
Manual backport of #4551 to release/8.x; conflict was in generate-release-notes.yml because it was manually fixed for the previous preview release.
=> [release/8.x] Stable version file and link

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
Goes along with https://github.com/dotnet/diagnostics/pull/3849 in the diagnostics repo.
=> Enable UpDownCounter For Dotnet-Monitor

.github/dependabot.template.yml, .github/dependabot.yml, .github/workflows/sync-branches.yml
Remove `release/7.0` from dependenabot updates and branch syncing; it will be [out of support on June 14th](https://github.com/dotnet/dotnet-monitor/discussions/3977).
=> Remove release/7.0 from dependabot and syncing

src/Tools/dotnet-monitor/TestAssemblies.cs
The test assembly path for the startup hook and hosting startup assemblies is being calculated incorrectly. This happened to work prior to the single file bundle change, but was broken when adding the assembly name to the path. This change should fix it to correctly locate the assembly that being queried.
=> Fix build output test assembly path

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs
Generate unique ID for each exception instance (that doesn't have an ID already assigned to it). This allows for correlation of exceptions to inner exceptions within .NET Monitor (not yet implemented).
=> Generate unique ID for each exception instance

cspell.json, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionProcessor.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipelineExceptionContext.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionDemultiplexerPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/Steps/ExceptionDemultiplexerPipelineStepTests.cs
These changes add a new step to the exceptions processor list that demultiplexes the `Exception` typed parts of the given `Exception` instance (specifically, it will report the `InnerException` property value, the `AggregateException.InnerExceptions` property value, and the exception itself). This allows for reporting of inner exceptions through the rest of the pipeline and eventually eventing the inner exception information.
=> Capture inner exceptions in startup hook

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventListener.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionEvents.cs
Remove the InnerExceptionId (note this is singular) payload; all inner exceptions whether there is one or multiple are reported through the InnerExceptionIds (note this is plural) payload. I've also removed ThrowingMethodName from the pipeline tests; this property is largely superfluous now that a call stack is available and would have caused more pain in future changes to allow for exceptions that have not been thrown.
=> Remove InnerExceptionId payload and ThrowingMethodName property

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionDemultiplexerPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionInstance.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionInstance.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Pipeline/Steps/ExceptionDemultiplexerPipelineStepTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs, src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs
Add the exception instance ID and inner exception ID information to the exception store. Added a few more tests to validate the inner exception IDs match the exception instance IDs.
Additionally, add support for capturing `ReflectionTypeLoadException.LoaderExceptions` as inner exceptions.
=> Add inner exception information to exception store

eng/AfterSolutionBuild.targets, eng/Build.props, eng/Common.props, eng/Publishing.props, eng/pipelines/jobs/build-archive.yml, src/singlefile/Directory.Build.props, src/singlefile/Directory.Build.targets, src/singlefile/dotnet-monitor/ProjectsToBuild.props, src/singlefile/dotnet-monitor/dotnet-monitor-singlefile.proj
Theses changes allow the publishing of the single file bundles to blob storage accounts and have them marked as non-shipping. It piggybacks of the archive job to copy the built bundles from the `pub` directory to the `artifacts/bundles/Release/NonShipping` directory from which the Publishing.props file will detect it and write entries into BAR manifest as appropriate. Because these files are in the `pub` directory during the signing job, they are also getting signed. The bundles in the `artifacts/bundles/Release/NonShipping` directory are named as `<BundleName>-<RID><BundleExtension>` in order to avoid collisions in the directory and when added to the `BlobArtifacts` artifact in the Azure Pipeline run.
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2201872&view …
=> Publish single file bundle to blob storage

src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Writes the inner exception information to the `/exceptions` route in the format as provided by the `AggregateException` class.
Example code generating exceptions:
```cs
List<Exception> innerInnerExceptions = new(2);
innerInnerExceptions.Add(new InvalidOperationException());
innerInnerExceptions.Add(new ArgumentException());
List<Exception> innerExceptions = new(3);
innerExceptions.Add(new AggregateException(innerInnerExceptions));
try
{
throw new FormatException();
}
catch (Exception ex)
{
innerExceptions.Add(ex);
}
innerExceptions.Add(new TaskCanceledException());
throw new AggregateException(innerExceptions);
```
For `text/plain`, only thrown exceptions are written at the top-level; the remaining unthrown exceptions are written inline with the thrown exceptions.
Example `text/plain` …
=> Report inner exception information in exceptions route

eng/Versions.props, eng/dependabot/Packages.props, eng/dependabot/Versions.props, eng/dependabot/net6.0/Packages.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net7.0/Packages.props, eng/dependabot/net7.0/Versions.props, src/Microsoft.Diagnostics.Monitoring.Extension.Common/EgressHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj
Split the `Microsoft.Extensions.*` package versions along their corresponding .NET runtime versions. Have each project only reference the `Microsoft.Extensions.*` assembly version that corresponds with the TFM.
The `dotnet/installer` updates started failing because a type was moved from `Microsoft.Extensions.Logging` to `Microsoft.Extensions.Logging.Abstractions`. The referenced version of `Microsoft.Extensions.Logging` was set to 7.0.0 which means that when `Microsoft.Extensions.Logging` 7.0.0 is used in concert with `Microsoft.Extensions.Logging.Abstractions` 8.0.0, ambiguous type references would occur.
To solve this, I've split all of the `Microsoft.Extensions.*` versions along their corresponding .NET runtime versions. Thus, the 6.0.*, 7.0.*, and 8.0.* lines of these assemblies are …
=> Move Microsoft.Extensions versions to TFM specific dependabot props

src/Directory.Build.targets, src/Tools/dotnet-monitor/Swagger/SwaggerGenOptionsExtensions.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
The single file bundle experiment is unable to server HTTP requests because the Swagger configuration expects the WebApi XML documentation file to be next to the running executable; this file doesn't exist in the single file bundle mode.
This change embeds the XML documentation file into the dotnet-monitor assembly and updates the Swagger configuration to get the manifest resource instead of the file on disk.
=> Use embedded WebApi documentation file for OpenApi XML comments

eng/Versions.props, eng/dependabot/net6.0/Packages.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net7.0/Packages.props, eng/dependabot/net7.0/Versions.props
Remove the target pack fallback version so that the Microsoft.Extensions.* packages are consistent with the test runtimes. Also remove the unused Microsoft.Extensions.Logging.EventSource version.
=> Remove targeting pack and Microsoft.Extensions.Logging.EventSource versions

documentation/schema.json, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/SchemaGenerationTests.cs
Schema generation test is failing due to change in Microsoft.Extension library version usage. This was not caught in PR because the test was never run in PR.
The schema is not generated with .NET 6 types since that is a subset of the available schema for .NET 6 and .NET 8 variants of the tool within the same package. The test has been updated to execute for each testing target framework (thus it will run in PR) but only invoke the schema generation tool for .NET 6.
=> Generate schema based on .NET 6 types

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/EndpointInfoSourceCallback.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs
Make use of `DiagnosticsClient.ApplyStartupHookAsync` in the exceptions pipeline tests for .NET 8+ targets instead of using the `DOTNET_STARTUP_HOOKS` environment variable.
=> Use ApplyStartupHook diagnostic command in exceptions pipeline tests

dotnet-monitor.yml, eng/pipelines/stages/preparerelease.yml
The update docker tag workflow wasn't ported back from main. This manually ports the latest changes so builds can kick off docker updates.
=> Fix update-docker tag workflow

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Profiler/ProfilerService.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Implement a fallback algorithm for the profiler runtime identifier so that specifying the identifier on the target process is not unconditionally required. This should allow .NET Monitor to detect the runtime identifier if its running in the same process namespace as the target process; it might also work across process namespace boundaries but will require further testing to confirm.
To validate this, I've removed the default setting of the runtime identifier on the target process in tests; any test involving .NET Monitor and the profiler in the target application should now be using the fallback algorithm.
Make best effort to dynamically determine portable runtime identifier without explicit setting.
=> Profiler runtime identifier fallback algorithm

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/FileSystemEgressExtensionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/InProcessFeaturesOptionsBinderTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsSettingsTests.cs
A couple of test classes are missing the TargetFrameworkMonikerTrait attribute, so they don't get run in PR. Added the attribute to the tests that are missing them and removed two tests that should have been removed in the last commit of #4764
=> Enable more tests to run in PR

documentation/README.md, documentation/api/README.md, documentation/api/definitions.md, documentation/api/stacks.md, documentation/configuration/README.md, documentation/configuration/collection-rule-configuration.md, documentation/configuration/in-process-features-configuration.md, documentation/configuration/storage-configuration.md, documentation/experimental.md
Update call stacks documentation to bring it out of experimental. I've also made adjustments to the headers to remove the `[Experimental]` moniker as well as the version number and move that to the next line as `First Available: X.Y` in order to make the links less complicated; for the latter, I can update the rest of the documentation to use the same pattern once we agree on that change.
=> Update call stacks documentation

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/LoggingRunnerAdapter.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectTraceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorCollectRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/TestTimeouts.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
This PR adds a new `--exit-on-stdin-disconnect` command line switch to `dotnet collect`. When specified, this will cause dotnet-monitor to watch stdin, and if it closes, will initiate graceful shutdown.
This also made some minor debuggability improvements to the unit test code to make it faster to see which processes were spawned.
Adds new `--exit-on-stdin-disconnect` command line switch to `dotnet collect`
=> Implement `--exit-on-stdin-disconnect` flag for dotnet-monitor collect

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/DotNetRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestDotNetHost.cs
Allow using `TEST_DOTNET_ROOT` to specify where to find dotnet host executable for testing.
=> Use TEST_DOTNET_ROOT in testing to override dotnet executable location

eng/pipelines/jobs/test-binaries.yml, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Fixtures/AzuriteFixture.cs
Use non-Azure Pipelines environment variable to indicate that Azurite must be initialized for Azurite-based tests.
=> Use environment variable to indicate that Azurite must initialize

eng/build.ps1, eng/build.sh
Remove the restriction that testing cannot be done from a cross build (e.g. x64 host building arm64). The future Helix test project will be relying on the computation of the target runtime identifier, which is only accurately available during a cross build. Our builds currently do not invoke tests during cross builds so it shouldn't be an issue. Additionally, remove the LLDB path calculation for non-Windows builds as it is unused.
=> Remove restriction of running tests in cross build

src/Tools/dotnet-monitor/CollectionRules/CollectionRulePipeline.cs
Currently, `dotnet monitor` emits the `CollectionRuleTriggerType` repeatedly in logs:
This can lead to huge amounts of console spew as this continues to grow every time the collection rule is triggered. The issue appears to have been tied to `triggerScopeRegistration` failing to be properly disposed in a loop.
Prevent overreporting of the collection rule trigger type in console output
=> Fix Collection Rule Trigger Type Console Spew

src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/Profiler/ProfilerService.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
If the process host reports a portable runtime identifier, use that value to determine which profiler variant to use. Additionally, log how the profiler runtime identifier was determined (`ProcessEnvironment`, `ProcessHost`, `ProcessImplicit`).
With these changes, the .NET 8 test applications have their profiler variant determined by the portable runtime identifier (since they respond to the `ProcessInfo3` command) and thus report as `ProcessHost` whereas the lower .NET versions fallback to the `ProcessImplicit` determination.
=> Use portable runtime identifier for profiler enablement when available

src/Tools/dotnet-monitor/StartupHook/StartupHookEndpointInfoSourceCallback.cs
After talking to @schmittjoseph , `OnBeforeResumeAsync` could be called multiple times for the same endpoint. Without this check, it'll repeatedly try to apply the startup hook, even if it already applied (or failed) earlier.
=> Add Check For Existing Key For `ApplyStartupHook`

eng/Helix.CrossTarget.targets, eng/Helix.SingleTarget.targets, eng/Helix.props, eng/Helix.targets, eng/helix/Helix.proj, eng/helix/payload/dotnettest.cmd, eng/helix/payload/dotnettest.sh, src/Directory.Build.props, src/Directory.Build.targets, src/Tests/Directory.Build.targets, src/Tests/Helix.targets
These changes enable the use of Helix for executing tests on a multitude of platforms and architectures. Helix testing is enabled through the use of the `/eng/helix/Helix.proj` project and can be executed on the command line using `build.cmd/sh -projects ./eng/helix/Helix.proj -test -skipnative -skipmanaged` after a successful full build of both native and managed components.
- The `/eng/helix/Helix.proj` project gathers the executable work item information (e.g. `dotnet test` command line) from each participating project (e.g. test projects).
- These work items (e.g. tests) are executed in a set of queues. There are several queues that are employed to get broad coverage of scenarios where .NET Monitor is used; the set of queues on which the work items are executed are determined by the …
=> Add Helix project and supporting targets

.github/fabricbot.json
Joe pointed out that the github-actions bot's comments are causing the `needs-review` label to be incorrectly removed (example [here](https://github.com/dotnet/dotnet-monitor/pull/4903)) - this should hopefully address that issue.
=> Update `Needs-Review` Label For GitHub-Actions Bot Comments

dotnet-monitor.yml, eng/helix/Helix.proj, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/test-binaries.yml
These changes enable the use of Helix for testing but preserve the ability to run the tests on build jobs if we need to flip back to that. If all (if there are any) Helix issues are resolved, we can then remove the ability to run tests via build jobs to simplify the pipeline.
=> Enable Helix testing in builds

src/Directory.Build.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MockTimeProvider.cs
Make C# linter happy by making this property always available so that the evaluation of the Helix work item timeout doesn't fail.
Failing linter run: https://github.com/dotnet/dotnet-monitor/actions/runs/5559265802/jobs/10155182618?pr=4903
Fixed linter run: https://github.com/dotnet/dotnet-monitor/actions/runs/5559414073/jobs/10155503108?pr=4918
=> Always make TestRunnerTestTimeoutMinutes available

src/Microsoft.Diagnostics.Monitoring.WebApi/DumpService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/StreamDefaults.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.TestHostingStartup/BuildOutputSharedLibraryInitializer.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/TestOutputLogger.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/DefaultSharedLibraryInitializerTests.cs, src/Tools/dotnet-monitor/LibrarySharing/DefaultSharedLibraryInitializer.cs, src/Tools/dotnet-monitor/LibrarySharing/DefaultSharedLibraryPathProvider.cs, src/Tools/dotnet-monitor/LibrarySharing/ISharedLibraryInitializer.cs, src/Tools/dotnet-monitor/LibrarySharing/SharedLibraryService.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/Tools/dotnet-monitor/StreamExtensions.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Change the shared library initializer to validate the files in the existing shared directory or write new files instead of relying on a sentinel file and keep the file handles open with read-only shared access. This allows .NET Monitor to confidently share libraries that will be loaded into target applications and know that they have not been tampered with between runs of .NET Monitor. If any file is different than expected, shared library initialization will fail and any feature that is dependent on it will not work.
Example console output:
```
16:58:51 info: Microsoft.Diagnostics.Tools.Monitor.Startup[60]
Tell us about your experience with dotnet monitor: https://aka.ms/dotnet-monitor-survey
16:58:51 info: Microsoft.Diagnostics.Tools.Monitor.Startup[77]
Connection mode: Listen at …
```
=> Verify shared library files integrity

eng/helix/payload/dotnettest.sh, src/Tests/Helix.targets
The Helix runs were not filtering tests for PR builds correctly causing all tests to be skipped!
For example, on non-Windows machines, it would state the following:
```
No test matches the given testcase filter `"TargetFrameworkMoniker=Net80"` in /root/helix/work/correlation/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Release/net6.0/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.dll
```
I've removed the double quotes around the filter argument in the dotnettest.sh script.
On Windows, it would state the following:
```
No test matches the given testcase filter `TargetFrameworkMoniker` in C:\h\w\C20409DE\p\Microsoft.Diagnostics.Monitoring.Tool.UnitTests\Release\net6.0\Microsoft.Diagnostics.Monitoring.Tool.UnitTests.dll
```
I added double quotes to the entire filter argument that is …
=> Fix Helix test filter args

eng/pipelines/dotnet-monitor-cg.yml
Create a daily scheduled pipeline that checks the shipped branches for component governance issues. This is needed since we frequently update release branches with newer package versions and will not get an accurate picture of if the latest shipped binaries have a component governance issue.
=> Add pipeline for component governance scan on shipped code

eng/pipelines/dotnet-monitor-cg.yml, eng/pipelines/jobs/build.yml
The CG pipeline fails to run and enable CG for 7.x and lower. This fixes those issues so that the pipeline runs, CG is unconditionally enabled, and tests are not run.
Example CG pipeline run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2225645&view=results
=> CG pipeline: disable CI/PR triggers and enable CG

eng/pipelines/jobs/build-archive.yml, eng/pipelines/jobs/build-binaries.yml, eng/pipelines/jobs/build.yml, eng/pipelines/jobs/test-binaries.yml
In the 8.0 offering, the musl libc packages are actually packing the glibc variants of the binaries AND publishing with glibc naming (e.g. https://dev.azure.com/dnceng/internal/_build/results?buildId=2222464&view=logs&j=d5728782-5d7f-5e51-ea2d-92c117e26b20&t=93b29a1b-9d48-5ac0-d339-4d509d35665f&l=103). This was likely a regression that occurred when switching to using cross builds, where the build jobs would cross build but the archive jobs did not; the root of the issue is that the target RID for these builds are `linux-x64` and `linux-arm64` instead of `linux-musl-x64` and `linux-musl-arm64` due to the lack of cross build. This has the effect that we have not been publishing musl libc packages since that change occurred.
This change pushes all of the cross build support back into the …
=> Push cross build into base build job

eng/helix/payload/installazurite.cmd, eng/helix/payload/setupnode.cmd
The batch scripts would immediately exit after invoking `npm`; fix this by using `call` to invoke `npm` in order to keep the batch interpreter executing.
=> Use call to keep batch interpreter running

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/EgressExtensibilityTests.cs
The ExtensionResponse_Success and ExtensionResponse_Failure tests frequently fail on non-x64 (and non-glibc Linux) platforms due to the apphost being built for x64 but the installed runtime is not necessarily x64. Disable the tests for now until the app and the corresponding tests can better handle different architectures and libc implementations.
=> Disable extension response tests

src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs
This test is failing with on line 99:
```
Assert.Equal() Failure
Expected: (null)
Actual:   {null}
```
The ExceptionsEventListen intentionally coalesces null to `{null}` to make sure the property is set correctly. Update the test to do the same from the test code to match behavior.
=> Fix ExceptionsEventSource_WriteException_Event to coalesce null value

src/Microsoft.Diagnostics.Monitoring.WebApi/EndpointInfo/IEndpointInfoSource.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/EndpointUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/EndpointInfo/ClientEndpointInfoSource.cs, src/Tools/dotnet-monitor/EndpointInfo/EndpointInfo.cs, src/Tools/dotnet-monitor/EndpointInfo/ScopedEndpointInfo.cs, src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs, src/Tools/dotnet-monitor/FilteredEndpointInfoSource.cs, src/Tools/dotnet-monitor/IDiagnosticLifetimeService.cs, src/Tools/dotnet-monitor/NotSupportedServiceProvider.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
These changes allow establishing services in a per-process scope; the benefit is that features can easily establish per-process state at any point in the lifetime of the diagnostic capability of the target process. Note that this is current only support for listen mode as connect mode does NOT have stable endpoint instances and tracking over the lifetime of the target process.
Example usage of this is in https://github.com/jander-msft/dotnet-monitor/pull/104, where the exception history feature has been converted to make use of the per-process services facility; note that the exceptions service and startup hooks service are greatly simplified. Because exceptions are tracked per-process, the HTTP API can allow reporting of exception history for any target process.
=> Add per-process service support

eng/release/Scripts/UpdateShippedBranch.ps1
Add a new script that force updates/creates the `shipped/*` branch that corresponds to a given release. Once merged in, I'll update our release definition to call it.
=> Add script to update `shipped/*` branches

src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
In #4964, per-process-service scope was added to allow services to be executed in a service scope for each target process. The service scope is disposed after detecting that the process is no longer running/responsive/etc. However, what was missed is that these service scopes were not disposed when .NET Monitor shuts down, thus leaving any kind of operations that were active still in flight (e.g. if a trace is started as part of the service scope, the trace would not be shut down and keep running in the target app).
These changes collect the service scopes as part of `ServerEndpointInfoSource` disposal where each of the scopes is disposed. Additional locking was added to make sure that the service scopes dictionary is not accessed simultaneously.
=> Shutdown process scopes services during tool shutdown.

src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressExtension.cs
Allow other processes to be able to read the target file instead of using an exclusive lock while the egress provider is writing.
=> Allow shared read access for file system egress

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Tools/dotnet-monitor/CollectionRules/Triggers/EventMeterTriggerFactory.cs, src/Tools/dotnet-monitor/Metrics/MetricsOperationFactory.cs
The core change is [here](https://github.com/dotnet/diagnostics/pull/3889) - this is the only piece that requires a change to the `dotnet monitor` repo for now, but the changes in the diagnostics repo do apply for Metrics/LiveMetrics/Triggers. For more context on the problem this is trying to solve, see [here](https://github.com/dotnet/diagnostics/pull/3889#issuecomment-1629262044).
=> Compatibility with 6/7 Runtimes For Multiple `System.Diagnostics.Metrics` Sessions

src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
The callbacks should be invoked in reverse order during diagnostic disconnect so that services that were started later will be the first ones to stop. This allows for proper ordering of detach/disconnect/event handler removing types of operations.
=> Invoke callbacks in reverse order on diagnostic disconnect

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainExceptionProcessor.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainFirstChanceExceptionSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/CurrentAppDomainUnhandledExceptionSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionAvailableEventArgs.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/ExceptionSourceBase.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/GuardedExceptionSourceBase.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/ExceptionPipeline.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionIdSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/UnhandledExceptionEventsPipelineStep.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/CurrentAppDomainFirstChanceExceptionSourceTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/MockExceptionSource.cs, src/Tools/dotnet-monitor/Exceptions/EventExceptionsPipeline.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionEvents.cs
Refactor exception source, pipeline, and event source to allow for processing unhandled exceptions through a separate pipeline instance but reporting them through the same event source instance used for first chance exceptions. This was done by:
- Refactoring `ExceptionSourceBase` to be agnostic of the source of the exception. Add `GuardedExceptionSourceBase` to shared between the first chance and unhandled sources.
- Move ownership of the `ExceptionsEventSource` and exception ID generation to the processor so that it can be shared between the first chance pipeline and the unhandled pipeline.
- Add new `ExceptionInstanceUnhandled` event to `ExceptionsEventSource`.
I've left the handling of the `ExceptionInstanceUnhandled` event in the `EventExceptionsPipeline` alone for now in order to …
=> Report unhandled exceptions through ExceptionsEventSource

documentation/openapi.json, src/Tools/dotnet-monitor/Swagger/SwaggerGenOptionsExtensions.cs
These changes make sure that `TimeSpan` is represented as a formatted string in the OpenAPI; this better describes the expected output (see collection rule details example: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/api/collectionrules-get.md#sample-response) as well as leads to better code generation for generating HTTP clients so that the built-in `TimeSpan` is used rather than generating a new type.
=> Represent TimeSpan as formatted string in OpenAPI

documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs
The HTTP 200 OK result for livemetrics was missing from the OpenAPI. Add it to the route handler and regenerate the OpenAPI document.
=> Add missing livemetrics HTTP 200 OK result

NuGet.config
Add `dotnet8-transport` feed to aid internal builds in acquiring packages.
=> Add dotnet8-transport feed

eng/pipelines/jobs/build.yml
This change updates the runtime source feeds to use the dotnetbuilds internal container to acquire installers from the internal feed.
=> Use dotnetbuilds internal feed for internal builds

eng/helix/Helix.proj, eng/pipelines/jobs/test-binaries.yml
Allow Helix test setup to get the blob storage internal container token to read packages and files from the container.
=> Allow Helix tests to use internal assets

eng/pipelines/jobs/tpn.yml
The TPN job is failing during restore because it cannot access internal builds. Add the internal runtime feeds to enable the restore to succeed.
=> Enable internal runtime feeds for TPN job

eng/Helix.Common.props, eng/Helix.props, eng/helix/Helix.proj, eng/pipelines/jobs/test-binaries.yml, eng/pipelines/jobs/tpn.yml
- Setup private feed usage in the TPN job so it can acquire internal build builds
- Change `dotnetbuilds` internal container token to be passed via environment to avoid escaping/splitting and use the non-based64 encoded variant
- Convert the `IncludeDotnetCli` convenience to an `AdditionalDotNetPackage` so that it may consume the `AdditionalDotNetPackageFeed` list.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2261376&view=results
=> Fix build and test infra to support internal release builds

eng/pipelines/jobs/test-binaries.yml
A value for the `_InternalHelixArgs` variable isn't specified, so it is left in the pipeline definition when expanding everything. It currently doesn't have any negative effect, although the job output does show this is not a recognized cmdlet or function, but it's good to remove it before it does cause issues.
=> Remove unspecified variable

dotnet-monitor.yml
If changes are made in the internal branches that are not yet publicly on GitHub, the SourceLink validation will fail. Skip this validation for the internal release branches.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2262105&view=results
=> Exclude internal release branches from SourceLink validation

eng/pipelines/stages/preparerelease.yml, eng/release/Scripts/AcquireBuild.ps1
- Update the release preparation stage to use the dotnetbuilds internal container SAS tokens.
- Add "continue on error" switches. Even though the correct tokens are used and the expected set of files are gathered, the `darc gather-drop` command will error many errors and exit with a non-zero code when acquiring files from locations that require SAS tokens.
I used [this build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262628&view=results) to test these changes with additional changes to skip all other parts of the building the product and to use the darc drop from [this nearly successful build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2262256&view=results).
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2262651&view=res …
=> Use dotnetbuilds SAS tokens for drop acquisition and continue on error

documentation/api/definitions.md, documentation/api/livemetrics-get.md, documentation/configuration/collection-rule-configuration.md, documentation/configuration/metrics-configuration.md, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.Metrics.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsSettingsTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectLiveMetricsAction.cs, src/Tools/dotnet-monitor/CollectionRules/Options/Actions/CollectLiveMetricsOptionsExtensions.cs
This changes the pipeline settings of the `GET /livemetrics` route to use the Metrics configuration instead of using the default event counters providers. Reasons for change:
- Both `GET /metrics` and `GET /livemetrics` now collect the same providers/counters/meters/instruments/etc. Customers "fall into the pit of success" more easily and don't need to wonder why `/livemetrics` collected a different data specification than `/metrics`.
- Customers are not required to respecify their metrics configuration via `POST /livemetrics` for something they already configured and naturally applies to all metrics scenarios.
- External tooling can now collect live metrics with the same specification that was already configured without having to dig through configuration sources, if has access to those …
=> Update GET livemetrics route to use metrics configuration

eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj
The Arcade infrastructure already defines `XUnitVersion`. Use that property instead of a custom property since the code doesn't require any of the newer functionality.
=> Remove custom XUnit version property

eng/dependabot/Packages.props, eng/dependabot/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj
The recent update of `Microsoft.IdentityModel.Tokens` is incompatible with `Microsoft.AspNetCore.Authentication.*` and `Microsoft.Identity.*` libraries and their implicit dependencies. Instead of dragging the implicit dependencies to higher versions, the IdentityModel references can be removed since they too are implicit of the `Microsoft.AspNetCore.Authentication.*` and `Microsoft.Identity.*` libraries.
=> Remove explicit IdentityModel dependencies

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs
For context: https://github.com/dotnet/runtime/issues/91125
=> [Exceptions] Fix Bug For Missing Callstacks With Eclipsing Exceptions

eng/Publishing.props, eng/pipelines/jobs/pack-sign-publish.yml, src/Directory.Build.targets
Remove the *.version and *.buildversion files from the publishing process. These files were created for two primary purposes and are no longer used.
- dotnet/dotnet-docker relied on these files being published to blob storage to determine the exact update version for each blob group. The update process has moved away from these files by using pipeline resource trigger that pulls a version asset directly from the build.
- The release note generation would use these files after they have been published to blob store to determine the exact version of the produce being built so it can name the notes file with that version. The process is moving away from using these files and will use the in-repository version information instead: #4140
What remains is a small portion of the *.buildversion …
=> Remove version file generation and blob publishing

eng/Publishing.props, eng/pipelines/jobs/pack-sign-publish.yml, src/Directory.Build.targets
Manual backport of #5456 to release/6.x
Conflicts were due to bundle creation, which does not exist in the release/6x branch
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2282433&view=results
=> [release/6.x] Remove version file generation and blob publishing

eng/Publishing.props, eng/pipelines/jobs/pack-sign-publish.yml, src/Directory.Build.targets
Manual backport of #5456 to release/7.2
Conflicts were due to bundle creation, which does not exist in the release/7.2 branch
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2282582&view=results
=> [release/7.2] Remove version file generation and blob publishing

eng/Version.Details.xml
Newer arcade versions (e.g. #5446) are checking the coherency of declared dependencies. It's flagged that the declared coherency between the runtime and aspnetcore frameworks is not correct. Since the product is not using these versions anymore (it is using dependabot to get the latest public versions), remove the coherency attributes in order to pass validation.
=> Remove coherency attributes from frameworks

Directory.Build.props, Directory.Packages.props, eng/Analyzers.props, eng/Versions.props, eng/dependabot/net7.0/Packages.props, eng/dependabot/net7.0/Versions.props, eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj, src/Directory.Build.props, src/Extensions/AzureBlobStorage/AzureBlobStorage.csproj, src/Extensions/S3Storage/S3Storage.csproj, src/Microsoft.Diagnostics.Monitoring.Extension.Common/Microsoft.Diagnostics.Monitoring.Extension.Common.csproj, src/Microsoft.Diagnostics.Monitoring.WebApi/Microsoft.Diagnostics.Monitoring.WebApi.csproj, src/Tests/Directory.Build.props, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp/Microsoft.Diagnostics.Monitoring.EgressExtensibilityApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp/Microsoft.Diagnostics.Monitoring.Profiler.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Directory.Build.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Microsoft.Diagnostics.Monitoring.UnitTestApp.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests.csproj, src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/pkgs/Common.targets
Use central package management. This allows for:
- uniformity of the restored package versions
- package consumers to not have to specify which version of the package to be restored
- pinning of transitive packages without forcing package references
Other noteworthy changes:
- Some packages were implicitly referenced, so they've been removed as explicit package references.
- Projects that reference packages that change their versions based on the current TFM must use `TargetFrameworks` property, even if they do not have multiple TFM for which they are building. An example is Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests.csproj.
- The Microsoft.Diagnostics.Monitoring.TestCommon/Microsoft.Diagnostics.Monitoring.TestCommon.csproj requires an override of the xunit.assert …
=> Use central package management

eng/pipelines/dotnet-monitor-release.yml, eng/release/Scripts/PublishToBlobAccounts.ps1
Update the release pipeline to use storage account container SAS tokens instead of using the account keys directly.
close #4645
=> Update release pipeline to use SAS tokens

documentation/openapi.json, documentation/schema.json, eng/Common.props, eng/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.ConfigurationSchema.UnitTests/SchemaGenerationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/InfoTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/ActionTestsHelper.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs, src/archives/AzureBlobStorage/ProjectsToPublish.props, src/archives/S3Storage/ProjectsToPublish.props, startvs.cmd
These changes remove the net6.0 TFM build of the .NET Monitor binaries such that only net8.0 TFM is built and packaged. The effect is that .NET Monitor 8.0 will only be runnable on systems with .NET 8 installed. This change does not impact the diagnosability of applications that are running on other .NET versions.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2285523&view=results
Remove `net6.0` TFM build and packaging. There is no impact on the ability to monitor .NET 6 (or any other version) applications.
=> Remove net6.0 TFM build and packaging

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ControllerExtensions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Strings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tools/dotnet-monitor/Experimental/ExperimentalStartupLogger.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Instead of returning HTTP 404 for routes that correspond to disabled feature, return HTTP 400 with a detail message:
```bash
curl -k https://localhost:52323/stacks
{"status":400,"detail":"The Call Stacks feature is not enabled."}
```
Disabled features with HTTP routes will return HTTP 400
=> Return HTTP 400 for disabled features

src/Microsoft.Diagnostics.Monitoring.StartupHook/StartupHook.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/StartupHookTests.cs
When parameter capturing is not enabled and no other feature is enabled that requires the profiler, the startup hook will throw a DllNotFoundException exception, which appears in the `/exceptions` history backlog. This happens because the startup hook is attempting to initialize the managed messaging dispatcher, which requires the profiler to have been loaded.
- Add an additional check of whether the profiler is loaded before attempting to initialize the dispatcher.
- Add tests to verify the availability of the dispatcher based on the existence of the profiler.
=> Prevent managed messaging initialization if profiler is not loaded

src/Microsoft.Diagnostics.Monitoring.StartupHook/DiagnosticsBootstrapper.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/StartupHook.cs
This change is a small refactor to make sure that diagnostics are only initialized once for the lifetime of the target application. This is to hedge against the startup hook being accidentally configured to run multiple times (e.g. process connects to .NET Monitor diagnostic server, connection in pruned, and process reconnects again).
=> Ensure diagnostics are only bootstrapped once in target application

eng/Versions.props
Change `release/8.x` to produce stable versions.
=> Use final stable version

eng/release/Scripts/GetBuildVersion.ps1
Changes in #5549 make use of the `GetBuildVersion.ps1` script in order to look up the non-final build version to use as the root of the blob storage publishing. This script didn't exist in the `release/6.x` branch. I made a copy of it from the `release/7.x` branch.
=> [release/6.x] Add GetBuildVersion.ps1 script

eng/release/Scripts/GetBuildVersion.ps1
Manual backport of #3661 and #3660 to `release/7.x`
=> [release/7.x] Fix GetBuildVersion.ps1 to correctly look up the build version

src/archives/AzureBlobStorage/ProjectsToPublish.props, src/archives/S3Storage/ProjectsToPublish.props
The apphosts for the extensions (e.g. `dotnet-monitor-egress-azureblobstorage.exe` and `dotnet-monitor-egress-s3storage.exe`) are not necessary since the extensions are launched using the shared dotnet installation with the extensions entrypoint assembly (see the extension manifest registrations [here](https://github.com/dotnet/dotnet-monitor/blob/main/src/Extensions/AzureBlobStorage/extension.json#L3) and [here](https://github.com/dotnet/dotnet-monitor/blob/main/src/Extensions/S3Storage/extension.json#L3)).
Removing the apphosts will yield a small size savings in the packages and docker images as well as lower our compliance costs for validating them (since they won't exist anymore).
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2310976&view=results
=> Remove the apphost from the extensions

eng/Publishing.props
- Generate a single file containing a mapping of checksums to their corresponding package name; this file will aid in generating dependency updates for .NET Monitor internal builds in the dotnet/dotnet-docker repo. While this example is not from .NET Monitor, it demonstrates the format of the file: https://dotnetcli.blob.core.windows.net/dotnet/checksums/8.0.0-sha.txt
- Generate checksums for non-symbols packages.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2312053&view=results
Corresponding dotnet/dotnet-docker utilization: https://github.com/dotnet/dotnet-docker/pull/4990
=> Generate checksum table file

src/archives/dotnet-monitor-base/Package.props
The `MutatingMonitorProfiler.pdb` symbols are missing from the symbols archive packages. Add them so they are registered when publishing symbols.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2312327&view=results
=> Add mutating profiler symbols to symbols package

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectTraceTests.cs
The currently stopping event timeout (10 seconds) isn't always enough in our CI pipelines. Switch to using the general timeout (3 minutes) for all stopping event tests that expect to be stopped early.
For tests that expect to not be stopped by an event (and thus take the full timeout), use a timeout of 15 seconds to avoid slowing down successful test runs.
=> Increase stopping event test timeouts

.github/workflows/generate-release-notes.yml
Support specifying a custom tag to use as the baseline for release notes
=> Support overriding the baseline tag when generating release notes

eng/pipelines/dotnet-monitor-release.yml
The `Az.Storage` PowerShell module released a new version today that has breaking changes regarding the generation of SAS tokens. This change initially blocked the ability to copy between blob storage accounts that are secured with SAS tokens. To mitigate this, pin the module version until changes can be made to adapt to the breaking change.
=> Pin Az.Storage module version

.github/dependabot.template.yml, .github/dependabot.yml, eng/Versions.props, eng/dependabot/net8.0/Directory.Build.props, eng/dependabot/net8.0/NuGet.config, eng/dependabot/net8.0/Packages.props, eng/dependabot/net8.0/Versions.props, eng/dependabot/net8.0/dependabot.csproj, eng/helix/Helix.proj, global.json
- Use the 8.0 RTM SDK for building binaries
- Switch the test runtime versions to the RTM versions
- Add net8.0 dependabot dependency updates to `main` branch.
- Refactor the dependabot configuration template to update target branches with the TFMs that exist in those branches.
=> Use 8.0 RTM SDK and runtimes

eng/pipelines/dotnet-monitor-compliance.yml, eng/pipelines/scripts/Copy-ApiScanEligible.ps1, eng/pipelines/scripts/Extract-Assets.ps1, eng/release/Scripts/AcquireBuild.ps1
Add a pipeline for running ApiScan on the shipping assets. Shipping assets are downloaded, unpacked, and filtered to what is applicable to ApiScan. All results are uploaded as an artifact on the pipeline. This pipeline requires manual invocation at this time.
Example run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2318464&view=results
=> Add compliance pipeline and scripts

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsStoreTests.cs
Add logging to the ExceptionsStoreTests to help diagnose conditions when failures occur.
=> Add test logging for ExceptionsStoreTests

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleDescriptionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs
The collection rule tests that use a CPU usage trigger are have sporadically not completion, which causes the test to wait for a long time and eventually timeout. Attempt to mitigate by lowering the CPU threshold for these tests.
=> Lower CPU threshold in collection rule integration tests

cspell.json, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/BoxingInstructions.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/BoxingTokensSignatureProvider.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/FunctionProbesManager.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/InstrumentedMethod.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/ProfilerAbi.cs, src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInjector.cpp, src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInjector.h, src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInstrumentation.cpp, src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInstrumentation.h, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/BoxingInstructionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/FunctionProbes/ProfilerAbiTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/MethodResolverTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/ParameterCapturingPipelineTests.cs
Currently the probe management API's managed layer precomputes all boxing tokens and passes only those to the profiler. This has the restriction of not allowing us to send additional information to the profiler for special boxing instruction. e.g.:
- What parameters need an indirect load.
- What parameters are typespecs and need a new metadata token emitted by the profiler.
This PR refactors those APIs, extending the ABI to accept a c-style array of structs (type: `PARAMETER_BOXING_INSTRUCTIONS`). This struct contains a discriminator telling the profiler the type of boxing instruction followed by a fixed-size set of data (to be expanded on in the future).
As an added benefit we can replace the current mechanism for specifying primitive tokens (where we create a fake metadata table with an …
=> [Parameter Capturing] Refactor probe management API to accept more detailed boxing instructions

src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Boxing/BoxingInstructions.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Boxing/BoxingTokensSignatureProvider.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/FunctionProbesManager.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/InstrumentedMethod.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Boxing/BoxingInstructionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/MethodResolverTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/ParameterCapturingPipelineTests.cs
With the upcoming support for typespec related parameters, the current `GetBoxingInstructions` method becomes responsible for too much and will be difficult to read.
To address this, move reflection-only boxing logic into a new method (`GetBoxingInstructionsFromReflection`). Also reorganizes the boxing-related files into a subfolder to help group things together.
There are **no** functional changes in this PR.
=> [Parameter Capturing] Refactor reflection-only boxing logic into new method

eng/pipelines/stages/preparerelease.yml
The `tagBuildOrRelease` task has been disabled/removed from the Azure DevOps organization. Replace with built-in support for tagging builds via Powershell inline script and logging commands.
=> Replace tagBuildOrRelease with Powershell inline script

.github/actions/update-releases-json/index.js
There's currently a bug where when we create a new release for a version that was previously a preview release (e.g. 8.0.0-rc.2 -> 8.0.0 GA) the "Original Release Date" field wasn't being reset to the new GA date. (As seen in https://github.com/dotnet/dotnet-monitor/pull/5687#discussion_r1392996312)  This PR fixes that bug and changes were locally tested.
Closes #5690
=> [releases.json] Clear original date when promoting a preview release to rtm

eng/dependabot/independent/Packages.props
NOTE: `AwsSdkS3Version` is already defined in `eng/dependabot/independent/Versions.props`, we just never had the necessary `PackageReference` for it.
https://github.com/dotnet/dotnet-monitor/blob/da106122009394c318b37dc437c52d24df8b93ba/eng/dependabot/independent/Versions.props#L17
=> Let dependabot manage `AWSSDK.S3`

eng/Versions.props, eng/dependabot/Versions.props
Use a `Versions.props` file that brings in all package versions managed by dependabot. This will minimize differences in `eng/Versions.props` between branches and help with a more automated release branch merge strategy.
=> Simplify dependabot version imports

.github/actions/open-pr/action.yml
Fix the commit author name and email used by our workflows to correctly attribute it to the github bot.  This will results in commits made by it looking like this:
=> Fix github-actions commit author

.github/workflows/check-learning-path-links.yml
Our scheduled workflows should only be running on the main repo and not forks, update `check-learning-path-links` accordingly.
Note that our other scheduled workflows already do this:
https://github.com/dotnet/dotnet-monitor/blob/ef4e70e84376d45119465339f1dc35aea4dab404/.github/workflows/sync-branches.yml#L14
=> Limit learning path automation to main repo

.gitattributes, .github/workflows/sync-branches.yml
This PR updates the (code) sync-branch workflow to understand and preserve branch-specific files during the automated merge. This means a seconds commit to re-apply branch-specific files is **usually** no longer needed. This works by overriding the merge driver for branch-specific files to always prefer the current branch's version of files.
Example PR: https://github.com/schmittjoseph/dotnet-monitor/pull/567
However, merge drivers are only involved if merge conflicts are present for a given file. That means it's possible for purely additive changes in `main` to still be merged into `feature/9.x` via this approach. To handle this we also perform the old approach of re-applying branch-specific files after a merge. If there were any files where this edge case occurs, they will be handled by …
=> Have automated merge commits respect branch-specific files

documentation/api/definitions.md, documentation/api/parameters.md, documentation/openapi.json, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/FunctionProbesStub.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/IFunctionProbes.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/LogEmittingProbes.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Pipeline/CaptureLimitPolicyProbes.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Pipeline/ParameterCapturingPipeline.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Pipeline/PolicyEnforcerProbe.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CaptureParametersConfiguration.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/CaptureLimitPolicyProbesTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/ParameterCapturingPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/TestFunctionProbes.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/FunctionProbes/PerFunctionProbeProxy.cs
Add a new option to parameter capturing that will stop the capturing session after a certain number of times parameters are captured. Note that this refers to the number of "sets" of parameters collected, not the total number of individual parameters. For example if `MyMethod(int a, int b, int c)` is called twice, then that would be 2 sets of parameters.
Update `POST /parameters` to support stopping after a certain number of times parameters are captured.
=> [Parameter Capturing] Add capture limit option

.gitattributes
Manual backport of `.gitattributes` changes in #6130.  This change needs to be manually backported for the initial merge PR to work as expected.
 
=> [feature/9.x] Support automated merges

src/Directory.Build.props
Windows arm64 tests have been failing a lot recently due to test timeouts. Increase our timeout by 10 minutes. Note that these test failures are occurring in `feature/9.x`, but I'm targeting `main` as this change will flow into `feature/9.x` via branch merges.
=> Increase helix test timeouts by 10 minutes

.github/workflows/add-markdown-feedback.yml
The "Add Markdown Feedback" workflow will fail if any of the documentation files have been deleted. Since we don't need to add the feedback links to deleted files, skip them when collecting the file list.
=> Ignore deleted files when check markdown feedback links

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/CollectionRulePipelineTests.cs
`CollectionRulePipeline_EventMeterTriggerTest_Histogram_GreaterThan` has been extremely flaky lately. Skipping this test. Issue tracking the test failure: https://github.com/dotnet/dotnet-monitor/issues/6154
=> Skip `CollectionRulePipeline_EventMeterTriggerTest_Histogram_GreaterThan`

.gitattributes, .github/workflows/sync-branches.yml
Various branch sync improvements:
1. When restoring branch-specific files/folders don't perform an overlay. This means files that appear in the branch being merged from, but not in the target branch, will be removed. The current behavior is resulting these files not being removed.  See https://github.com/dotnet/dotnet-monitor/pull/6168 for an example of this incorrect behavior.
2. Automatically determine the list of branch-specific files from the `.gitattributes` file in the branch being updated. This means our various branches can customize what files they want to preserve the sync-branches workflow will honor it.
=> Branch sync improvements

eng/pipelines/dotnet-monitor-official.yml, eng/pipelines/dotnet-monitor-public.yml
Upcoming changes to official builds will likely require structural differences in the build pipeline compared to how public builds work. For now, create a separate copy of the public and official pipelines under the `/eng/pipelines` folder. Both "new" pipelines are exact copies of the one found at `/dotnet-monitor.yml`.
The plan is to circulate this copy through all of the branches, switch the public build definition to use `/eng/pipelines/dotnet-monitor-public.yml`, and remove the `/dotnet-monitor.yml` pipeline.
=> Bifurcate official pipeline from public pipeline

eng/pipelines/jobs/build.yml, eng/pipelines/templates/pipeline-template.yml
The `*-pt` images are short-term migration images that will be removed in a later infrastructure rollout. Switch to the long-term images.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2403324&view=results
=> Use long-term pool images

eng/pipelines/dotnet-monitor-compliance.yml, eng/release/Scripts/GetBuildVersion.ps1
Run APIScan compliance with two-part version (e.g. `8.0`) instead of full version. This allows bundling all runs for a given major.minor version together such that APIScan service settings can be applied by group instead of each individual build.
=> Run compliance with two-part version

eng/pipelines/jobs/build.yml, eng/pipelines/jobs/pack-sign-publish.yml, eng/pipelines/jobs/sign-binaries.yml
Arcade has fixes for log publishing in the 1ES templates. Remove the disablement / conditional enablement of logs to restore log publishing in the official builds.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2404357&view=results
=> Reenable log publishing

src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/AppCommands.cs
Manual backport of #6299 to release/7.x; only had to change `AppCommands.LogEnvironmentVariables` to report the product version of the only profiler (there is no mutating vs notification-only split in 7.x).
=> [release/7.x] Minimize printing of potential secrets in tests

src/Tests/CollectionRuleActions.UnitTests/EnvironmentVariableActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/AppCommands.cs
- For environment variable tests, only use well-known environment variables instead of reporting all environment variables of the test process.
- For API key generation tests, don't log token claims to test output.
=> Minimize printing of potential secrets in tests

documentation/release-process.md, eng/pipelines/dotnet-monitor-official.yml
Allow multiple branches to automatically update the dotnet/dotnet-docker repository. Example setting is `AutoUpdateDockerBranches = refs/heads/main;refs/heads/feature/9.x`, which means that scheduled builds of the `main` and `feature/9.x` branch will trigger updates in dotnet/dotnet-docker.
=> Allow multiple branches to auto update dotnet-docker

src/Tools/dotnet-monitor/LoggingEventIds.cs, src/Tools/dotnet-monitor/LoggingExtensions.cs, src/Tools/dotnet-monitor/StartupHook/StartupHookValidator.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Condense the log messages shown to the user when `DOTNET_STARTUP_HOOKS` isn't configured into a single message that contains all the necessary information.
=> Condense log messages when `DOTNET_STARTUP_HOOKS` is not properly configured

eng/pipelines/dotnet-monitor-official.yml
Run scheduled builds for `feature/9.x` so that dotnet/dotnet-docker can pick up nightly updates for 9.0.
Corresponding change in dotnet/dotnet-docker: https://github.com/dotnet/dotnet-docker/pull/5314
=> Run scheduled builds for feature/9.x branch

CMakeLists.txt, eng/pipelines/dotnet-monitor-public.yml, eng/pipelines/templates/pipeline-template.yml
Enable spectre-mitigations on Windows native builds. As part of this we need to switch to using the 1ES Windows images during builds as these images have the necessary spectre-mitigated libraries.
Test builds:
- [Internal](https://dev.azure.com/dnceng/internal/_build/results?buildId=2420193)
- [Public](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629290)
NOTE: Devs will need to install the relevant spectre-mitigated libraries on their machines to build the profilers now if they didn't already have them. They are installable via VS, and if you're missing them the build will fail with a message explaining that you're missing them and how to install them.
=> Enable spectre-mitigations for native builds

CMakeLists.txt, eng/pipelines/dotnet-monitor-public.yml, eng/pipelines/templates/pipeline-template.yml
Manual backport of #6398 to release/7.x. Manual port was needed because the mutating profiler doesn't exist in this branch, thus our `CMakeLists.txt` looks a little different in this branch.
=> [release/7.x] Enable spectre-mitigations for native builds

CMakeLists.txt, eng/pipelines/dotnet-monitor-public.yml, eng/pipelines/templates/pipeline-template.yml
Manual backport of #6398 to release/6.x. Manual port was needed because:
- The mutating profiler doesn't exist in this branch, thus our `CMakeLists.txt` looks a little different in this branch.
- The pipelines don't reference `$(DncEngPublicBuildPool)` and `$(DncEngInternalBuildPool)` so the yaml was little different in this branch.
=> [release/6.x] Enable spectre-mitigations for native builds

documentation/openapi.json, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/TraceProfile.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/TraceUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/ActionTestsHelper.cs
Fixes #4605
To make collecting gc-collect only traces easier with dotnet-monitor. I have made this change so that you can have a gc profile.
~Ideally, the class `GcCollectConfiguration` should be part of `Microsoft.Diagnostics.Monitoring.EventPipe.dll`. it will be after https://github.com/dotnet/diagnostics/pull/4568~
> Edit: Merged and consumed.
Add `GcCollect` trace profile for collecting lightweight GC collection events, same as the `gc-collect` profile in the `dotnet-trace` tool.
=> Support collecting GC collect only trace using a simplified profile

eng/dependabot/nuget.org/NuGet.config
The nuget.org dependabot folder is updating based on the nuget.config file at the root of the repository, causing it to use the non-nuget.org feeds to lookup dependencies and prematurely issuing version updates.
Add a nuget.config file in this folder that points to nuget.org so that dependabot only considers package versions on nuget.org.
=> Fix nuget.org dependabot package version scanning source

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerOptionsExtensions.cs
When using API Key auth, enable AAD signing key issuer validation -- this is required by CodeQL. 
We already have an official way of performing AAD auth, so this is change largely a no-op. The full effects of adding this validation are as follows:
-  If an [`OpenIdConnectConfiguration`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.protocols.openidconnect.openidconnectconfiguration?view=msal-web-dotnet-latest) is configured then extra validation will be performed on it. When using API Key auth, we never add this configuration so nothing will happen unless the user somehow has.
- If the API key is derived from an X.509 certificate then we will now validate the lifetime of the certificate (if it is already active and non-expired).
=> Enable AAD signing key issuer validation for API Key auth

eng/pipelines/dotnet-monitor-public.yml, eng/pipelines/jobs/test-binaries.yml
Dotnet Monitor builds are currently failing due to the use of `sudo` to install PowerShell on Linux in `test-binaries.yml`. This circumvents the issue by using `dotnet tool install` to acquire PowerShell on Linux.
=> Remove `sudo` From `test-binaries.yml`

eng/dependabot/independent/Packages.props, eng/dependabot/independent/Versions.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests.csproj, src/Tools/dotnet-monitor/Auth/JwtBearerPostConfigure.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Manual backport of #6459 to release/6.x. Manual backport was needed due to a difference in dependencies. `release/6.x` doesn't have AAD auth, so it doesn't pull in `Microsoft.Identity.Web`. As a result it doesn't have the needed `Microsoft.IdentityModel.Validators` package. Add `Microsoft.IdentityModel.Validators` explicitly.
=> [release/6.x] Enable AAD signing key issuer validation for API Key auth

documentation/api-key-format.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tools/dotnet-monitor/Auth/ApiKey/GeneratedJwtKey.cs, src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerOptionsExtensions.cs, src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerPostConfigure.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyConfiguration.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyPostConfigure.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Enable validation for the `iss` and `exp` fields in the API key token. These fields are now required to be in the token when using API key authentication.
The `generatekey` command will produce a token with the `iss` field set to `https://github.com/dotnet/dotnet-monitor/generatekey+MonitorApiKey` (this is an existing behavior) and the `exp` field set to expire 7 days from when the token was generated (this is a new behavior). The expiration can be overridden with the `--expiration` option.
In the case where a customer is generating their own JWT keys to be used with .NET Monitor, they can override the expected issuer in configuration by setting `Authentication__MonitorApiKey__Issuer` to the value of the issuer that is expected. Setting this is optional; its default value is …
=> Add issuer and expiration validation for API keys

documentation/api-key-format.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tools/dotnet-monitor/Auth/ApiKey/GeneratedJwtKey.cs, src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerOptionsExtensions.cs, src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerPostConfigure.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyConfiguration.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyPostConfigure.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Manual backport of #6456 to `release/8.0`; had to fix merge conflict in `OptionsDisplayStrings` files.
=> [release/8.0] Add issuer and expiration validation for API keys

documentation/api-key-format.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tools/dotnet-monitor/Auth/ApiKey/GeneratedJwtKey.cs, src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerOptionsExtensions.cs, src/Tools/dotnet-monitor/Auth/ApiKey/JwtBearerPostConfigure.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyConfiguration.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyPostConfigure.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/HostBuilder/HostBuilderHelper.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Manual backport of #6456 to `release/7.x`; several merge conflicts on string resources and tests were manually resolved.
=> [release/7.x] Add issuer and expiration validation for API keys

documentation/api-key-format.md, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.WebApi/Auth/AuthConstants.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeySignInfo.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Auth/ApiKey/ApiKeyToken.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/AuthenticationTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/GenerateKeyTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.ApiKey.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tools/dotnet-monitor/Auth/AuthConfiguration.cs, src/Tools/dotnet-monitor/Auth/GeneratedJwtKey.cs, src/Tools/dotnet-monitor/Auth/JwtBearerPostConfigure.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyConfiguration.cs, src/Tools/dotnet-monitor/Auth/MonitorApiKeyPostConfigure.cs, src/Tools/dotnet-monitor/Commands/GenerateApiKeyCommandHandler.cs, src/Tools/dotnet-monitor/Program.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx
Manual backport of #6456 to `release/6.x`; resolved merge conflicts among options strings, test options changes, and `AuthConfiguration` since this was changed in the 7.x timeframe.
=> [release/6.x] Add issuer and expiration validation for API keys

src/Tools/dotnet-monitor/AbstractEventSourcePipeline.cs, src/Tools/dotnet-monitor/EventSourcePipelineProxy.cs
Add a new public `EventSourcePipelineProxy` class. It provides a simple wrapper around the dotnet/diagnostic's internal-only `EventSourcePipeline<T>` class. Changing the visibility of `EventSourcePipeline<T>` class should be a separate and more intentional piece of work. This wrapper will allow us to rapidly make progress and any needed changes in the interim.
=> Add wrapper for `EventSourcePipeline` with increased visibility

eng/pipelines/jobs/build.yml
It seems that .NET 9 Preview 4 requires MacOS 12 at minimum to run. When installing newer Preview 4 candidates, running dotnet will fail with:
```
Failed to load /Users/runner/work/1/s/.dotnet/host/fxr/9.0.0-preview.4.24223.11/libhostfxr.dylib, error: dlopen(/Users/runner/work/1/s/.dotnet/host/fxr/9.0.0-preview.4.24223.11/libhostfxr.dylib, 1): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
Referenced from: /Users/runner/work/1/s/.dotnet/host/fxr/9.0.0-preview.4.24223.11/libhostfxr.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib
```
Update the MacOS version for pipeline jobs to 12.
=> Update MacOS version to 12

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx
The `DisplayAttributeDescription_CollectExceptionsOptions_Filters` resx entry is missing from `release/8.0` likely due to a incomplete backport. I've added it to make sure the schema documentation is correct and to allow easier backporting in the future so that there is not missing information from the schema.
=> Add missing resx entry for schema

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClientExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ParameterCapturingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ParameterCapturingScenario.cs
- The new parameter capturing logic doesn't rely on logs anymore, so I've updated the test scenarios to remove the logs related ones.
- Re-enable ParameterCapturingTests, and replaced the log tests with ones that verify the http response.
=> Update and re-enable ParameterCapturingTests

eng/pipelines/jobs/build-test.yml
The newest version of Azurite seems to not be compatible with node.js 10. I've attempted to update the node.js version to something more modern, but the build images seem to be too old to support the newer versions. Pin the Azurite version for .NET Monitor 7.x.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2440916&view=results
=> [release/7.x] Pin Azurite version to 3.29.0

Directory.Packages.props, documentation/schema.json, eng/Signing.props, src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/RootTests.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyAuthConfigurator.cs, src/Tools/dotnet-monitor/Auth/AzureAd/AzureAdAuthConfigurator.cs, src/Tools/dotnet-monitor/Auth/IAuthenticationConfigurator.cs, src/Tools/dotnet-monitor/Auth/NoAuth/NoAuthConfigurator.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx, src/Tools/dotnet-monitor/Swagger/SwaggerProviderExtensions.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Manual backport of #6146 to `release/8.0`; manually resolved merge conflict in learning path documents due to commit IDs changing.
=> [release/8.0] Replace SwaggerUI and SwaggerScope option with OpenAPI document

documentation/schema.json, eng/Signing.props, src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen/Program.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Options/OptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/RootTests.cs, src/Tools/dotnet-monitor/Auth/ApiKey/MonitorApiKeyAuthConfigurator.cs, src/Tools/dotnet-monitor/Auth/AzureAd/AzureAdAuthConfigurator.cs, src/Tools/dotnet-monitor/Auth/IAuthenticationConfigurator.cs, src/Tools/dotnet-monitor/Auth/NoAuth/NoAuthConfigurator.cs, src/Tools/dotnet-monitor/Startup.cs, src/Tools/dotnet-monitor/Strings.Designer.cs, src/Tools/dotnet-monitor/Strings.resx, src/Tools/dotnet-monitor/Swagger/SwaggerProviderExtensions.cs, src/Tools/dotnet-monitor/dotnet-monitor.csproj
Manual backport of #6146 to `release/7.x`; manually resolved merge conflict in learning path documents due to commit IDs changing and package version tracking is different from 7.x and newer branches.
=> [release/7.x] Replace SwaggerUI and SwaggerScope option with OpenAPI document

eng/dependabot/nuget.org/NuGet.config
For better compliance, the dependabot NuGet.config files should be using Azure Artifacts feeds that are managed by the dotnet team. Instead of using `nuget.org`, use the `dotnet-public` feed, which is public feed mirror of packages that are on nuget.org.
=> Use dotnet-public instead of nuget.org for dependabot

src/Tools/dotnet-monitor/EndpointInfo/ServerEndpointInfoSource.cs
The `_activeEndpointServiceScopes` dictionary is largely protected from simultaneous mutation using the `_activeEndpointsSemaphore` semaphore. However, there is one place where this lock is not taken which is likely causing the issue reported in #6569. Add the semaphore usage so that the dictionary is fully protected.
Fix an issue that could cause monitored processes to fail to resume when in listen mode: [#6569](https://github.com/dotnet/dotnet-monitor/issues/6569)
=> Add semaphore around service scopes dictionary

eng/pipelines/templates/pipeline-template.yml
Replace CBL-Mariner 2.0 build containers with Azure Linux 3.0 build containers.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2443403&view=results
=> Update build container images

documentation/api/definitions.md, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Eventing/AsyncParameterCapturingEventSource.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/Eventing/ParameterCapturingEventSource.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/FunctionProbes/EventSourceEmittingProbes.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/ExpressionBinder.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ObjectFormatting/Formatters/RuntimeFormatters.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ObjectFormatting/ObjectFormatter.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ResolvedParameterInfo.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CapturedParametersResults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/CapturedParametersFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/CapturedParametersTextFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ParameterCapturing/ParameterInfo.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/RequiredMemberAttribute.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/DebuggerDisplayFormatterTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/RuntimeFormattersTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/ObjectFormatting/ObjectFormatterTests.cs, src/Tools/dotnet-monitor/ParameterCapturing/CapturedParameters.cs, src/Tools/dotnet-monitor/ParameterCapturing/CapturedParametersBuilder.cs, src/Tools/dotnet-monitor/ParameterCapturing/EventParameterCapturingPipeline.cs, src/Tools/dotnet-monitor/ParameterCapturing/ParameterCapturingEvents.cs
* Updated the captured parameter result so the value parameter and activity id are nullable strings.
* Introduced `ObjectFormatterResult` which includes the evaluated and formatted parameter value and evaluation metadata flags (`IsNull`, `FailedEval`, `UnsupportedEval`, `EvalHasSideEffects`). `ObjectFormatter now returns objects of the new type.
* `EventSourceEmittingProbes.EnterProbe` doesn't request adding quotes to the formatted value anymore. The quotes were added to easily parse the ILogger output, but we don't have that problem anymore.
* Updated `ParameterCapturingEventSource` to send the new evaluation flags as part of the captured paramater.
* Updated `WebApi.Models.CapturedParameter` to include a new optional property: `EvalFailReason`.
* Updated the formatter tests to support …
=> ParameterCapturing: Remove quotes from string evaluations, include failure reason information make the value nullable

src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingService.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.HostingStartup/ParameterCapturing/ParameterCapturingStrings.resx, src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs, src/Tools/dotnet-monitor/ParameterCapturing/ParameterCapturingEvents.cs
Previously we were using the `ILogger` infrastructure to log probe faults. This PR adds a replacement by using the existing `ParameterCapturingEventSource.FailedToCapture` event with a new reason: `ProbeFaulted`.
While working on this I noticed we stopped using some resource strings so I remove them.
=> Trace probe faults through event source

Directory.Packages.props, documentation/configuration/egress-configuration.md, eng/Signing.props, eng/dependabot/independent/Packages.props, eng/dependabot/independent/Versions.props, src/Extensions/S3Storage/S3Storage.csproj
**Reason for change**
As it stands, the S3 egress provider does not currently support the use of service accounts when running dotnet monitor in kubernetes.
This is one of the two recommended ways to give pods permission to access AWS resources via roles. This tends to be recommended over long lived access keys as it removes the need for regular rotation of credentials etc.
**Details of change made**
The full documentation for this lives [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) on AWS's documentation site. It uses OpenID Connect to do authentication and is natively supported in the existing C# SDK which is already used. However, there is a [note](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.h …
=> [Egress providers - S3 store]  Add support for service accounts when running dotnet monitor in kubernetes

CMakeLists.txt, eng/native/override/configurecompiler.cmake
Use `add_compiler_options` to enable spectre mitigations and sdl checks. This helps pass the spectre mitigation flags to more of the vcxproj properties and SDL checks are enabled.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2452865&view=results
=> Use add_compiler_options to enable spectre mitigations and sdl checks

src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests.csproj, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Boxing/BoxingInstructionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Boxing/MethodDefinitionExtensionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/MethodResolverTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/MethodSignatureTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/DebuggerDisplayFormatterTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/ExpressionBinderTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/CaptureLimitPolicyProbesTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/ParameterCapturingPipelineTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/Pipeline/TestFunctionProbes.cs, src/Tests/Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests/ParameterCapturing/SampleMethods.cs
Enable nullable types in `Microsoft.Diagnostics.Monitoring.HostingStartup.UnitTests.csproj` and fix all build erros. The code changes are needed for when I'll move the tests in `Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests.csproj` where nullable types are already enabled.
=> Enable nullable types in HostingStartup.UnitTests

eng/pipelines/dotnet-monitor-official.yml
There is practically no utility in building the debug variants of the product in the official CI build:
- The official CI build already does not test debug bits.
- The public PR builds already build and run all of the latest TFM tests for debug binaries, which should provide enough coverage for new changes that introduce problems that would only show in debug builds.
- Very little of the source code makes use of debug flags for altering product or test functionality.
- Historically, very few issues have been caught by debug build legs in the CI build.
By removing debug variants from the CI build, compute utilization will be reduced and compliance tooling will not have to consider debug bits.
=> Remove debug legs from CI build

src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs
Fix a race condition when starting the parameter capturing operation. We never waited for the event pipeline to start running before issuing the start IPC command. This means that the parameter capturing operation could start before dotnet-monitor was listening and so it'd never receive the start event.
This issue rarely occurs due to the amount of work parameter capturing does in-proc before starting.
=> [Parameter Capturing] Fix race condition when starting operation

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperationStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/OperationExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Operation/EgressOperationServiceTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleEgressActionBase.cs
When an operation is first created it enters a `Starting` state and typically signals a task completion source once it has started and the operation transitions to a `Running` state. If an error occurs while running the operation transitions to the `Failed` state.
There are 2 edge cases that could cause an operation to get indefinitely stuck in the `Starting` state:
1) If the operation encounters an error (i.e. throws an exception) before it has a chance to transition to the `Running` state, the operation will be stuck in the `Starting` state and never transition to `Failed`.
2) If the operation has a bug and completes without ever signaling the started task completion source (e.g. it should transition from `Starting` -> `Completed`), the operation will be stuck in the `Starting` state. …
=> Prevent operations from getting stuck in the `Starting` state

src/Tools/dotnet-monitor/CollectionRules/ActionListExecutor.cs
While working on another feature I came across a bug where we don't use `ErrorMessage_CouldNotMapToAction` correctly - we weren't supplying the necessary argument to it.
Fix the error log message shown when an action could not be registered.
=> Fix ErrorMessage_CouldNotMapToAction usage

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/OperationsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/EgressOperationStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/IEgressOperationStore.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Operation/OperationExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Operation/EgressOperationServiceTests.cs, src/Tools/dotnet-monitor/CollectionRules/Actions/CollectionRuleEgressActionBase.cs
Manual backport of #6686 to `release/8.0`. Merge conflicts:
- `src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagnosticsControllerBase.cs`: there isn't a second ctor in this branch.
- `src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/ExceptionsController.cs` directly references `EgressOperationStore` and needed to be switched over to the new interface.
=> [release/8.0] Prevent operations from getting stuck in the `Starting` state

eng/Version.Details.xml, eng/Versions.props, eng/helix/Helix.proj
Use the `Microsoft.NET.Sdk` package from `dotnet/sdk` as the key for runtime and framework updates.
=> Use dotnet/sdk for runtime and framework updates

eng/pipelines/jobs/test-binaries.yml
Tests on win-arm64 no longer stall.
closes #6531
=> Remove continue on error for win-arm64 tests

eng/Version.Details.xml, eng/Versions.props, eng/helix/Helix.proj
Based on guidance, use non-final sentinel package for tracking the SDK version.
=> Use sentinel package for installable SDK version

src/Microsoft.Diagnostics.Monitoring.WebApi/RequestThrottling/RequestLimit.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/RequestThrottling/RequestLimitTracker.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/TestHostHelper.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
This PR updates how we configure request limits from being a hard-coded implementation detail to be done via dependency injection. This enables additional request limits to be added via DI.
Note: This PR preserves the current behavior and concepts. There's a few ways we probably want to refactor the request limit tracker / request limit concept but that should be done separately.
=> Configure request limits via DI

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/FunctionProbesTests.cs
`FunctionProbesTests` verify `FunctionProbesManager` and mutating profiler features, it's not verifying the interaction with dotnet-monitor. To simplify the tests I'm proposing using `AppRunner` to execute these scenarios which will also unblock PR #6707 because the startup hook assembly is not loaded in the test application and the `ParameterCapturingService` will not automatically start.
Currently there's only one .NET 6 test which verifies the profiler wasn't loaded. I've decide to keep that test as-is and use the `ScenarioRunner` just for it, because it acually verified that we don't accidently inject the profiler.
=> Refactor FunctionProbesTests to use the AppRunner instead of ScenarioRunner in net7 or higher tests

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ParameterCapturingTests.cs
The parameter capturing tests are still flaky even after the first try to fix them. I think I figured out the root cause for the current issue and this is a fix for it:
* Updated the capturing duration to `CommonTestTimeouts.GeneralTimeout` and set the limit to 1 so it completes as soon as the expected method is called.
* Fixed bug in `ApiClient.CaptureParametersAsync`  to properly compute the total seconds from a `TimeSpan`.
=> ParameterCapturingTests: Increase capture duration and set limit to 1

.github/linters/check-markdown-links-config.json, .github/workflows/check-markdown-links.yml, documentation/api/definitions.md, documentation/api/stacks.md, documentation/configuration/in-process-features-configuration.md
This PR adds a note to "In Process Features Configuration" section to make it clear that it works only in Listen mode.
Based on conversation in issue #6753.
=> Add documentation note about in-process features are only supported in Listen mode.

.github/linters/check-markdown-links-config.json, .github/workflows/check-markdown-links.yml, .github/workflows/submit-linter-suggestions.yml, .github/workflows/submit-to-do-issue.yml, documentation/api/definitions.md, documentation/api/stacks.md, documentation/configuration/in-process-features-configuration.md, eng/Version.Details.xml, eng/Versions.props, eng/dependabot/independent/Versions.props, eng/dependabot/net6.0/Versions.props, eng/dependabot/net7.0/Versions.props, eng/dependabot/net8.0/Versions.props, eng/pipelines/dotnet-monitor-cg.yml, global.json, src/Microsoft.Diagnostics.Monitoring.WebApi/RequestThrottling/RequestLimit.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/RequestThrottling/RequestLimitTracker.cs, src/Profilers/MonitorProfiler/Communication/CommandServer.cpp, src/Profilers/MonitorProfiler/Communication/CommandServer.h, src/Profilers/MonitorProfiler/Communication/MessageCallbackManager.cpp, src/Profilers/MonitorProfiler/Communication/MessageCallbackManager.h, src/Profilers/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/Profilers/MonitorProfiler/MainProfiler/MainProfiler.h, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleDescriptionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/HttpApi/ApiClient.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ParameterCapturingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/TestHostHelper.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs, src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs, src/inc/macros.h
Merge main into `feature/parameter-capturing/startup-hook` to fix some flaky tests.
=> Sync feature/parameter-capturing/startup-hook

cspell.json, src/Profilers/CommonMonitorProfiler/CommonUtilities/ClrData.h, src/Profilers/CommonMonitorProfiler/CommonUtilities/NameCache.cpp, src/Profilers/CommonMonitorProfiler/CommonUtilities/NameCache.h, src/Profilers/CommonMonitorProfiler/CommonUtilities/TypeNameUtilities.cpp, src/Profilers/CommonMonitorProfiler/EventProvider/EventTypeMapping.h, src/Profilers/CommonMonitorProfiler/EventProvider/ProfilerEvent.h
This PR makes infrastructure changes to the notify-only profiler to support us enhancing frame data in our artifacts. There are **no** functional changes in this PR, this is solely focused on profiler infrastructure changes that will be leveraged in future PRs. 
Profiler changes:
- Record the mvid of modules when collecting call stacks.
- Upgrade our event pipe related code to support writing guid payloads.
I've verified that the recorded mvids are correct and that guids we send over eventpipe are deserialized correctly.
=> [Profiler] Record mvid information and add GUID support to event pipe

documentation/api/parameters.md, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ParameterCapturingTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/ScenarioRunner.cs, src/Tools/dotnet-monitor/Commands/CollectCommandHandler.cs
*  Moved the `InProcessFeaturesService` registration before the `ProfilerService` registration because the `IEndpointInfoSourceCallbacks` need to first reach the in process service so it can set the `DotnetMonitor_InProcessFeatures_ParameterCapturing_Enable` environment variable which is later checked by the profiler initialization.
* Reworked `ParameterCapturingTests` to include the new `shouldSuspendTargetApp` arg and added tests to verify the new scenarios: `CapturesParametersNoSuspend` & `AppWithStartupHookFailsInNoSuspend`.
* Updated `ScenarioRunner.SingleTarget()` to support starting the target process befor the monitor process.
* Updated docs.
=> Enable parameter capturing in no suspend mode.

src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/DebuggerDisplayParserTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/ParameterCapturing/ObjectFormatting/Formatters/DebuggerDisplay/ExpressionBinderTests.cs
We have some inline data that was using `null` for parameters not marked a `nullable`.  This is resulting in analyzer failures in `feature/9.x`
=> Fix inline data nullable parameters

eng/pipelines/dotnet-monitor-release.yml, eng/release/Scripts/PublishToBlobAccounts.ps1
Use a managed identity when publishing staged release assets to `dotnetcli` and `dotnetclichecksums` (as well as `monitortestcli` and `monitortestchecksums` in test mode).
Pipeline runs:
- Test account: https://dev.azure.com/dnceng/internal/_build/results?buildId=2483916&view=results
- [Dry] Prod account: https://dev.azure.com/dnceng/internal/_build/results?buildId=2483991&view=results
=> Use managed identity to publish release assets

src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/MetricsController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/TaskCompletionSourceExtensions.cs
This PR has low risk fixes for nullability issues in WebApi.
=> [Nullable Context] `Microsoft.Diagnostics.Monitoring.WebApi` fixes

eng/pipelines/jobs/build.yml, eng/pipelines/jobs/pack-sign-publish.yml, eng/pipelines/jobs/sign-binaries.yml, eng/pipelines/jobs/test-binaries.yml, eng/pipelines/jobs/tpn.yml, eng/pipelines/stages/preparerelease.yml
Manual backport of #6892 to release/8.0; only conflict was for the compliance pipeline, which doesn't exist in release/8.0
=> [release/8.0] Use federated connections for storage account

src/Microsoft.Diagnostics.Monitoring.Options/AuthenticationOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/CollectionRuleMetadata.cs, src/Microsoft.Diagnostics.Monitoring.Options/CorsConfigurationOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/DiagnosticPortOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/DotnetMonitorDebugOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/EgressOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsConfiguration.cs, src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/FileSystemEgressProviderOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/GlobalCounterOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/InProcessFeaturesOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/Microsoft.Diagnostics.Monitoring.Options.csproj, src/Microsoft.Diagnostics.Monitoring.Options/MonitorApiKeyOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/ProcessFilterOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/StorageOptions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/DiagProcessFilter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/DumpService.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsSettingsFactory.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProfilerChannel.cs
Enable nullable aware context for `Microsoft.Diagnostics.Monitoring.Options`.  Just like https://github.com/dotnet/dotnet-monitor/pull/6924 this PR only contains no/low risk changes.
=> [Nullable Context] Enable on `Microsoft.Diagnostics.Monitoring.Options`

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/ExceptionsConfiguration.cs, src/Microsoft.Diagnostics.Monitoring.Options/MetricsOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/ProcessFilterOptions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/ExceptionsSettingsFactory.cs, src/Tools/dotnet-monitor/CollectionRules/Options/CollectionRuleOptions.cs
Now that we have nullable contexts enabled for our schema, we can fix an issue where we were reporting optional lists could be set as a null. 
This PR standardizes **all** of our optional Lists to default to an empty collection and not be nullable and also have setters (we rely on these setters quite a bit in our tests).
Partial fix for #6929 
Additional ref: https://github.com/dotnet/dotnet-monitor/pull/6932/files#r1663237955
=> [Nullable Context] Standardize optional arrays in schema

eng/pipelines/dotnet-monitor-cg.yml
The excluded branches were not correctly specified (they were missing the `v` in the version). This update should actually exclude the branches from being scanned for component governance issues.
=> Fix excluded branches in CG pipeline

documentation/api/definitions.md
Support for the `GcCollect` option was added for trace profiles in https://github.com/dotnet/dotnet-monitor/pull/6348, however, the documentation was never updated. This just updates the docs with similar information to the release note/PR
=> [Docs] Add the `GcCollect` option to TraceProfile in documentation

eng/pipelines/stages/preparerelease.yml
Manually porting `preparerelease.yml` from https://github.com/dotnet/dotnet-monitor/pull/6892 to address staging issue.
=> [release/6.x] Manually Backport `preparerelease.yml` 

.github/dependabot.template.yml, .github/dependabot.yml
The `Azure.Identity` package should be updated with the rest of the Azure SDK dependencies since it is released with the other Azure SDK packages.
=> Move Azure.Identity to azure-sdk-dependencies group

eng/pipelines/dotnet-monitor-compliance.yml, eng/pipelines/dotnet-monitor-release.yml, eng/pipelines/stages/preparerelease.yml, eng/release/Scripts/GetBuildVersion.ps1, eng/release/Scripts/GetDarcBuild.ps1, eng/release/Scripts/GetReleaseVersion.ps1
- Convert GetBuildVersion.ps1 and GetReleaseVersion.ps1 scripts to use `darc` instead of Maestro web api.
- Switch from PowerShell to AzureCLI pipeline task to use the "Darc: Maestro Production" service connection.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2519875&view=logs&j=9c2ccffd-8e7d-5b34-ccf9-d3f1053322e9&t=3f1d8db9-f809-50a5-55bc-cc845894472c
The validation build demonstrates that the GetBuildVersion.ps1 script works as expected. The remainder of the job failed due to the "Publish Using Darc" job not actually publishing bits. I will perform further testing once the changes are merged.
Closes #7079
=> Get build data using darc instead of maestro web api

eng/pipelines/dotnet-monitor-release.yml, eng/pipelines/stages/preparerelease.yml, eng/release/Scripts/GetBuildVersion.ps1, eng/release/Scripts/GetDarcBuild.ps1, eng/release/Scripts/GetReleaseVersion.ps1
Manual backport of #7174 to `release/8.0`; there was minor merge conflicts in some of the files due to drift and the compliance pipeline doesn't exist in 8.0
=> [release/8.0] Get build data using darc instead of maestro web api

eng/pipelines/stages/preparerelease.yml, eng/release/Scripts/GetBuildVersion.ps1, eng/release/Scripts/GetDarcBuild.ps1
Manual backport of #7174 to release/6.x; there was minor merge conflicts in some of the files due to drift and the compliance pipeline, release pipeline, and GetReleaseVersion script don't exist in 6.x
=> [release/6.x] Get build data using darc instead of maestro web api

eng/pipelines/jobs/test-binaries.yml
In #6892, the repository switched to using federated service connections and generating feed tokens on demand. One spot that was missed was the Helix test runs, which required a non-base64 runtime feed token. Add the pipeline step to generate this token and set it on the expected variable.
This is targeting `release/9.x` directly and will be backported to all other branches after approval and validation.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2527864&view=results
=> Get non-base64 runtime feed token for Helix

eng/common/core-templates/steps/get-delegation-sas.yml, eng/pipelines/jobs/test-binaries.yml
- Increase the token expiration for Helix runs. The test job allows Helix up to 2 hours since it can take some time to wait in the Helix queues before tests are run. Don't want the token to expire before the tests get a chance to run.
- Update the get-delegation-sas yaml to retry getting a token if it contains a forward slash. Tokens with forward slashes seem to trip up Helix and cause it to not download the correlation payload. Similar workarounds have been employed elsewhere: https://github.com/dotnet/aspnetcore/blob/release/6.0/eng/common/templates-official/steps/get-delegation-sas.yml#L34
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2528027&view=results
=> Increase token expiration and retry until compatible token

src/Tests/Microsoft.Diagnostics.Monitoring.OpenApiGen.UnitTests/OpenApiGeneratorTests.cs
As seen in PRs such as #7234, new analyzers are failing the name of some async methods and requiring the use of aysnc methods over sync methods within async contexts.
=> Update async usage to conform to analyzer rules

documentation/README.md, documentation/docker-compose.md, documentation/docker.md, documentation/kubernetes.md
This sample is largely the same as the Kubernetes sample, except with a Docker Compose yaml and updated links to point to Docker Compose documentation. Also added cross linking between the Docker and Kubernetes documentation.
=> Add Docker Compose sample and cross link

src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Eventing/ExceptionsEventSource.cs, src/Microsoft.Diagnostics.Monitoring.StartupHook/Exceptions/Pipeline/Steps/ExceptionEventsPipelineStep.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Exceptions/IExceptionInstance.cs, src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/Exceptions/Eventing/ExceptionsEventSourceTests.cs
We have a bug in our in-proc exception collection event source code that results in malformed event payloads whenever an exception doesn't have an activity id. This results in the event pipeline processing the exceptions to be unable to parse the data and drop exceptions.
Below describes the issue, covering what the in-proc event source code is doing and then our pipeline.
In-proc flow:
- Our in-proc code used nullable strings for `ActivityId` and `ExceptionMessage` (side note: `ExceptionMessage` could never actually be null) when declaring the `ExceptionInstance` event.
- When either of these had a null value, we'd instantiate a `PinnedData` with a null value.
- When event source goes to serialize this, it doesn't send anything for this field since it's a 0 length payload.
Event pipeline …
=> Prevent collected exceptions from being dropped due to null event values

documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptions.cs, src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptionsDefaults.cs, src/Microsoft.Diagnostics.Monitoring.Options/AzureAdOptionsExtensions.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/Options/AzureAdOptionsTests.cs, src/Tools/dotnet-monitor/Auth/AzureAd/AzureAdAuthConfigurator.cs
Require setting the `TenantId` property with no default option. Documentation updates will be made in a separate PR targeting `main`.
The `TenantId` property is now required when configuring `AzureAd` authentication.
=> [feature/9.x] Require setting `TenantId` when configuring `AzureAd` authentication

cspell.json, documentation/compatibility/9.0/README.md, documentation/compatibility/README.md, documentation/configuration/azure-ad-authentication-configuration.md
Add documentation for https://github.com/dotnet/dotnet-monitor/pull/7365.
=> Document breaking Entra ID configuration change

.github/actions/learning-path-staleness-check/index.js
I did some looking around, and I think I figured out why the learning path automation is broken. This hasn't been tested, so I'd like to check it in, run the automation, and then iterate if needed - the changes are pretty minimal and pertain only to the automation.
There are two slight bugs that I'm trying to address: the first is that if a line is no longer present in the file, the `newLineNumberFirst` and `newLineNumberLast` in theory are the same (0), in which case we try to apply a suggestion when we shouldn't (in `AssembleOutput`, we check if there's a value for `newLineNumber`, which in JS if the value is 0 this would be false). The second is that we aren't trimming the `prevContentLines`, which could cause issues for changes in tabbing.
The error being thrown was occurring when …
=> Update Learning Path Staleness Check

.github/actions/learning-path-staleness-check/index.js, .github/workflows/check-learning-path-links.yml
Follows https://github.com/dotnet/dotnet-monitor/pull/7383 - I think my diagnosis was correct, but it wasn't a complete fix. I tried this change in my fork and it appeared to resolve the problem: https://github.com/kkeirstead/dotnet-monitor/pull/413. I'll run the automation again and confirm things look right before merging the learning path update.
=> Update Learning Path Staleness Check (Pt. 2)

eng/pipelines/jobs/pack-sign-publish.yml, eng/pipelines/jobs/sign-binaries.yml
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2551971&view=results
=> Add internal build access to pack and sign jobs

eng/helix/Helix.proj
CBL Mariner 2.0 will not be an available image for .NET 9; let's remove the Helix queue for CBL Mariner 2.0 to lighten the Linux x64 test job.
=> Remove CBL Mariner helix queue

documentation/learningPath/aks.md, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DumpTestUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs, src/Tools/dotnet-monitor/RuntimeInfo.cs
The configuration system in coreclr and mono started supporting `DOTNET_` prefix in net6.0. Using `DOTNET_` is preferred because [it has precedence](https://github.com/dotnet/runtime/blob/a3d1e1cdb61a65b64246dee45998f2701c8987b8/src/coreclr/inc/clrconfignocache.h#L81) over `COMPlus_`.
This matches the behavior by prioritizing DOTNET_ prefix and moving COMPlus_ to fallback in product code. Tests are using the new prefix.
=> Replace COMPlus with DOTNET prefix

.github/dependabot.template.yml, .github/dependabot.yml, eng/dependabot/net8.0/Versions.props
The System.Text.Json dependency is part of the TFM dependabot version source, so it should be removed from the independent package group and into the TFM package group. Additionally, add it to the runtime-dependencies group since it is produced by dotnet/runtime and would update with simultaneously with similar dependencies.
=> Move System.Text.Json into runtime-dependencies group

eng/dependabot/net8.0/Packages.props
A double quote is missing from the System.Text.Json PackageReference Version property.
=> Fix net8.0 dependabot Packages.props

eng/helix/Helix.proj
This reverts commit edfddd9acb43f9e8478c96dcd5104e6062a9c96a.
The use of the `VSRedistCommonAspNetCoreSharedFrameworkx6480Version` is causing incompatibilities with the runtime versions that are updated via dependabot. Reverting back to `MicrosoftAspNetCoreApp80Version` to restore the compatible versions. This is how it is set in every other branch.
=> Revert "Fixup package version (#7411)"

.github/dependabot.template.yml, .github/dependabot.yml
The repository uses `Microsoft.NETCore.DotNetHost` to determine the latest runtime version since `Microsoft.NETCore.App.Runtime.*` are platform packages and cannot be used as PackageReferences. Fix the package name in the update group so that it is updated together with the other runtime dependent packages.
=> Fix runtime framework package version name

.github/dependabot.template.yml, .github/dependabot.yml
Manual backport of #7579 to main branch. The dependabot update descriptions need to be in the main branch.
=> Add .NET 9 dependabot updates

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/DumpTestUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/MonitorRunner.cs, src/Tools/dotnet-monitor/ParameterCapturing/CaptureParametersOperation.cs, src/Tools/dotnet-monitor/RuntimeInfo.cs
Manual backport of #7434 to `release/8.0`; only difference is the removal of nullability operators since that was not applied to `release/8.0`.
=> [release/8.0] Replace COMPlus with DOTNET prefix

documentation/api/definitions.md, documentation/api/stacks.md
Our documentation stated that parameter type information is collected as part of the `/stacks` feature -- this isn't the case. Update our documentation.
=> Update documentation around `/stacks` and `parameterTypes`

src/Tests/Microsoft.Diagnostics.Monitoring.StartupHook.UnitTests/BackgroundService/BackgroundServiceTests.cs
Skip the flaky `Stop_WaitsForTheBackgroundTask` test. The test is flaky because the background service only waits up to 1 second when stopping for the executing task. On a resource constrained system this test is more likely to fail.
Example failure: https://dev.azure.com/dnceng-public/public/_build/results?buildId=843507&view=ms.vss-test-web.build-test-results-tab&runId=21880890&resultId=100088&paneView=debug
=> Skip flaky `BackgroundService` test

src/Microsoft.Diagnostics.Monitoring.WebApi/Models/Activity.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/ExceptionInstance.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/JsonStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/NameFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Models/CallStackResultsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/Operation/EgressOperationStoreTests.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsStore.cs
Switch over to using `JsonSerializer` to serialize our exception data instead of manually serializing. This will make it less likely for us to accidentally introduce bugs here, standardize with our other features, and also make writing more complex json tests for `/exceptions` easier.
**This PR does not change the API surface**.
=> Use `JsonSerializer` to serialize exception data

documentation/api/definitions.md, documentation/api/exceptions.md, documentation/api/stacks.md, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/CallStackResults.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/SpeedScopeStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Stacks/TextStacksFormatter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Utilities/StackUtilities.cs, src/Profilers/CommonMonitorProfiler/CommonUtilities/TypeNameUtilities.cpp, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/TestAppScenarios.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/StacksTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/ExceptionsScenario.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/HiddenFrameTestMethods.cs, src/Tests/Microsoft.Diagnostics.Monitoring.UnitTestApp/Scenarios/StacksWorker.cs, src/Tools/dotnet-monitor/Exceptions/ExceptionsOperation.cs
When frames (via their function or declaring type) contain [`StackTraceHiddenAttribute`](https://learn.microsoft.com/dotnet/api/system.diagnostics.stacktracehiddenattribute) they are now hidden from text stack traces. When retrieving json stack traces, they are still included but are identified by a new `hidden` field.
The bulk of this PR is updating our `/exceptions` and `/stacks` functional tests + test infrastructure. Also fix a bug with how our profiler identified hidden functions.
Hide frames with [`StackTraceHiddenAttribute`](https://learn.microsoft.com/dotnet/api/system.diagnostics.stacktracehiddenattribute) from `/exceptions` and `/stacks`. When retrieving json data these frames are still included but are identified by a new `hidden` field.
=> Hide frames with `StackTraceHiddenAttribute` from `/exceptions` and `/stacks`

eng/Versions.props
Switch `feature/9.x` to use official diagnostic releases as we don't need anything from the nightly builds for 9.0 GA.
=> [feature/9.x] Use official diagnostic releases

eng/dependabot/net9.0/Versions.props
Dependabot won't automatically update preview versions, so manually update `System.Text.Json` to unblock other changes. This should only need to be done once, as the next release will be GA.
=> [feature/9.x] Force `System.Text.Json` Update

src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/RetryUtilities.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/EgressTests.cs
`SharedConcurrencyLimitTest` has been extremely flaky recently. The issue appears to be from the fact that:
1. We're running on a resource constrained system.
1. This test runs multiple concurrent traces (3), while also triggering cancellations. This is somewhat intensive inside the test environment.
1. Because of the above 2 reasons, the test app fails its responsiveness check (in Connect mode, taking longer than 3 seconds to respond) when doing additional API calls, causing a test failure.
To fix it, add retry to our API calls in these tests when it appears that the process has failed its liveliness check. For now I've only introduced this retry logic to `EgressTests`. If we find other tests are facing this same issue we can consider moving this retry logic further down inside of our …
=> Add transient failure retry to `SharedConcurrencyLimitTest`

eng/pipelines/jobs/build.yml
Update the MacOS build pool to OSX 15. The built binaries should still be runnable on 10.14+ for x64 and 11.0+ for arm64 because CMAKE_OSX_DEPLOYMENT_TARGET is specified.
=> Update MacOS build pool to OSX 15

documentation/release-process.md
=> Additional notes regarding internal releases

src/Tests/CollectionRuleActions.UnitTests/CollectDumpActionTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/ExceptionsTests.cs
=> Temporarily exclude flaky tests

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ExceptionsStoreTests.cs
Similar to https://github.com/dotnet/dotnet-monitor/pull/7615
=> Temporarily exclude flaky `ExceptionsStore_AddThreeRemoveThreeOutOfOrder_Empty`

eng/Signing.props
Tarball unpack/sign/repack has been enabled in some Arcade updates but it interferes with the current .NET Monitor package signing. .NET Monitor is already signing the contents of packages in the Archive stage; tarball unpack/sign/repack doesn't provide value because the contents are already pre-signed. To mitigate the interference, disable tarball signing for now.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2578097&view=results
=> Disable tarball signing

eng/pipelines/dotnet-monitor-compliance.yml
This is the same treatment applied to the storage account staging stage (https://github.com/dotnet/dotnet-monitor/pull/7410) but applied to the compliance pipeline. This fixes an issue where the compliance pipeline is unable to download the build.
=> Fix AcquireBuild usage in compliance pipeline

eng/pipelines/dotnet-monitor-cg.yml
With .NET Monitor 6 at end-of-life, we can skip scanning the 6.X shipped branches for component governance.
=> Skip CG for version 6 branches

src/Tests/Directory.Builds.props
Newer SDK versions are failing build due to the existence of the `net7.0` target framework being used in the test applications. Use of the EOL target frameworks for testing is desired for some time after EOL has occurred, so the check should be suppressed for the test projects. The removal of EOL target frameworks can be done separately when it is no longer necessary to test with them.
Unblocks #7704
=> Disable EOL check for test projects

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/MetricsFormattingTests.cs
During a refactor, an `AggregatePercentilePayload` concept was built on top of `PercentilePayload`, and was not properly updated in `IsMeter`. It would appear that `UpDownCounterPayload` was also not updated correctly. Formatting tests were added for both to ensure tags were showing up as expected.
Closes https://github.com/dotnet/dotnet-monitor/issues/7654
Fixed an issue with custom tags not showing up for `Histogram` and `UpDownCounter` meters
=> Fix `Histogram/UpDownCounter` Custom Tags Bug

src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs
Replaces the backport https://github.com/dotnet/dotnet-monitor/pull/7744 - just updates `IsMeter` without the tests for custom tags that don't pertain to 8.0.
Fixed bug where `Histogram/UpDownCounter` were not correctly treated as meters.
=> Updated metrics store

eng/pipelines/dotnet-monitor-release.yml, eng/release/Scripts/PublishToBlobAccounts.ps1
These changes update the release pipeline to use dSAS token for accessing the `dotnetcli` storage account so that files can be transferred to it from `dotnetstage` storage account. These changes were used for the .NET Monitor November 2024 releases.
=> Generate dSAS for dotnetcli account

eng/pipelines/dotnet-monitor-cg.yml, eng/pipelines/dotnet-monitor-codeql.yml, eng/pipelines/dotnet-monitor-official.yml, eng/pipelines/dotnet-monitor-public.yml, eng/pipelines/jobs/platform-matrix.yml
The public builds will only run x64 tests (binaries for all architectures are still built). The internal builds will still build and test all architectures.
Internal validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2631743&view=results
=> Only run x64 Helix tests in public

eng/Versions.props, eng/dependabot/net9.0/Packages.props, eng/dependabot/net9.0/Versions.props, global.json
Switch .NET 9 dependencies to those found in the dotnet-public feed instead of using dependency flow.
=> Use dotnet-public net9.0 versions

src/Profilers/MonitorProfiler/Communication/CommandServer.cpp, src/Profilers/MonitorProfiler/Communication/CommandServer.h, src/Profilers/MonitorProfiler/Communication/MessageCallbackManager.cpp, src/Profilers/MonitorProfiler/Communication/MessageCallbackManager.h, src/Profilers/MonitorProfiler/MainProfiler/MainProfiler.cpp, src/Profilers/MutatingMonitorProfiler/ProbeInstrumentation/ProbeInstrumentation.cpp
Use another thread to process non-managed commands in the profiler. This fixes an issue where /parameters (which causes a managed callback in the inproc code) breaks /stacks (which requires a thread that has never ran managed code).
Fix an issue where `/parameters` causes `/stacks` to return CORPROF_E_UNSUPPORTED_CALL_SEQUENCE
=> Force callstacks to only run on untainted threads

eng/helix/Helix.proj
The Helix runner should install the same ASP.NET Core version for which the tests are built. Use the same version variable when specifying the ASP.NET Core additional package for .NET 9.
=> Fix Helix ASP.NET 9.0 version

eng/pipelines/jobs/build-binaries.yml
CMake places a lot of binaries under the `obj/win-x64.Release` output folder during build. Some of the scanning tools flag some of these binaries as not being compliant (e.g. needing to add EnableControlFlowGuard to CompilerIdC.exe). The repository doesn't ship those binaries. To avoid being flagged, delete the `obj/win-x64.Release` folder before uploading it as a build artifact; it is not necessary for downstream consumers of the build.
Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2635369
=> Prevent native obj files from being uploaded to build artifact

documentation/api/definitions.md, documentation/api/process-get.md, documentation/configuration/default-process-configuration.md, documentation/openapi.json, documentation/schema.json, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.Designer.cs, src/Microsoft.Diagnostics.Monitoring.Options/OptionsDisplayStrings.resx, src/Microsoft.Diagnostics.Monitoring.Options/ProcessFilterOptions.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/DiagProcessFilter.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/EndpointInfo/IEndpointInfoSource.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/IDiagnosticServices.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/Models/ProcessInfo.cs, src/Microsoft.Diagnostics.Monitoring.WebApi/ProcessInfoImpl.cs, src/Tests/Microsoft.Diagnostics.Monitoring.TestCommon/Runners/AppRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/Runners/ScenarioRunner.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTestCommon/Options/CollectionRuleOptionsExtensions.cs, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.UnitTests/ActionDependencyAnalyzerTests.cs, src/Tools/dotnet-monitor/EndpointInfo/EndpointInfo.cs, src/Tools/dotnet-monitor/EndpointInfo/ScopedEndpointInfo.cs
=> Add managed entry point to process info and collection rule filters

src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/CollectionRuleTests.cs
Managed entry point assembly name is only available on .NET 8 and higher. Exclude the functional tests from the lower TFMs.
=> Limit managed entry point assembly tests to net8.0 and higher

src/Tests/Microsoft.Diagnostics.Monitoring.WebApi.UnitTests/DefaultProcessConfigurationTests.cs
Some more test failure fixes due to addition of the managed entry point assembly. These tests seem to not run in PR but only run in CI, which I'll investigate separately to get them to run in PR.
=> Update DefaultProcessConfigurationTests for managed entry point assembly

eng/pipelines/dotnet-monitor-publish.yml
=> Add stub release build

src/Directory.Build.props, src/Tests/Microsoft.Diagnostics.Monitoring.Tool.FunctionalTests/LiveMetricsTests.cs
Missed this update in #8035 to run .NET 10 target tests in PR instead of .NET 9.
=> [feature/10.0] Make PR run .NET 10 tests

eng/dependabot/independent/Versions.props
Dependabot is failing to update some dependencies in the `release/8.x` branch "because it would cause a dependency conflict." The [logs](https://github.com/dotnet/dotnet-monitor/actions/runs/14457024012/job/40542366897) are not clear as to what conflict that might be. I've updated the dependencies manually and the build seems to be fine.
=> [release/8.x] Manually update dependencies that dependabot is failing to update

eng/dependabot/independent/Packages.props, eng/dependabot/independent/Versions.props
The `Swashbuckle.AspNetCore` package is no longer used in .NET Monitor 9.1 and later. Remove this dependency from source since it is not used and so that Dependabot doesn't attempt for perform updates.
=> Remove unused Swashbuckle.AspNetCore package

.github/dependabot.template.yml, .github/dependabot.yml
When the `main` branch was updated to build .NET Monitor 9.1, I forgot to update the dependabot configuration to specify that the branch is producing .NET Monitor 9.X versions. With this update, it should now get .NET 9 updates in the net9.0 dependabot versions.
=> Change main to be .NET 9 for dependabot updates

eng/Versions.props
This reverts commit bf764132a3e24d5a7eb8ce461cc15ccfb0499028.
I'm going to revert the version bump in main so that I can merge main to release/9.x again after all of the dependency updates go through. I will then redo the version bump after the merge is completed.
=> Revert "update release information (#8188)"

src/Tools/dotnet-monitor/CommonOptionsExtensions.cs
Porting this part of https://github.com/dotnet/dotnet-monitor/pull/8233 to main.
I don't think this affects the product behavior since the `config show` command doesn't set a Uri.
=> Map Uri config value as string

eng/pipelines/jobs/pack-sign-publish.yml
"C:\.tools\.nuget\packages\microsoft.dotnet.arcade.sdk\10.0.0-beta.25425.114\tools\StrongName.targets" cannot be imported again. It was already imported at "C:\.tools\.nuget\packages\microsoft.dotnet.arcade.sdk\10.0.0-beta.25425.114\tools\Publish.proj (51,3)". This is most likely a build authoring error. This subsequent import will be ignored.
=> [release/10.0] Suppress duplicate imports warning 

eng/pipelines/dotnet-monitor-release.yml, eng/release/Scripts/GetBuildVersion.ps1
=> Use dotnet-monitor asset instead of merge manfest for versioning

src/Tools/dotnet-monitor/dotnet-monitor.csproj, src/archives/dotnet-monitor-base/Package.props
This is a revert for some of the publishing changes. We effectively publish 3 projects (dotnet-monitor, s3 extensions, azure extensions) with overlapping dependencies (e.g. System.CommandLine). The publish step erroneously determines that these dependencies are collisions and removes them for some of the 3 projects we publish. This revert goes back to manually staging out the files.
This is a partial revert of #8554 and #8552
=> Revert publishing files
